FROM golang:1.25-alpine3.22 AS builder
WORKDIR /app

# 安装构建依赖
RUN apk add --no-cache git

# 设置 Go 代理以加速下载并提高稳定性
ENV GOPROXY=https://goproxy.cn,direct

# 复制依赖文件
COPY go.mod go.sum ./
RUN go mod download

# 复制源码并构建
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o migrate cmd/migrate/main.go

FROM alpine:3.22
RUN apk --no-cache add ca-certificates tzdata
WORKDIR /app
COPY --from=builder /app/migrate .
COPY --from=builder /app/internal/config/* ./config/
ENV TZ=UTC
ENTRYPOINT ["./migrate"]
