// Code generated by ent, DO NOT EDIT.

package checkoutsession

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/flexprice/flexprice/internal/types"
)

const (
	// Label holds the string label denoting the checkoutsession type in the database.
	Label = "checkout_session"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldEnvironmentID holds the string denoting the environment_id field in the database.
	FieldEnvironmentID = "environment_id"
	// FieldCustomerID holds the string denoting the customer_id field in the database.
	FieldCustomerID = "customer_id"
	// FieldAction holds the string denoting the action field in the database.
	FieldAction = "action"
	// FieldCheckoutStatus holds the string denoting the checkout_status field in the database.
	FieldCheckoutStatus = "checkout_status"
	// FieldPaymentProvider holds the string denoting the payment_provider field in the database.
	FieldPaymentProvider = "payment_provider"
	// FieldCheckoutInvoiceID holds the string denoting the checkout_invoice_id field in the database.
	FieldCheckoutInvoiceID = "checkout_invoice_id"
	// FieldCheckoutPaymentID holds the string denoting the checkout_payment_id field in the database.
	FieldCheckoutPaymentID = "checkout_payment_id"
	// FieldConfiguration holds the string denoting the configuration field in the database.
	FieldConfiguration = "configuration"
	// FieldResult holds the string denoting the result field in the database.
	FieldResult = "result"
	// FieldProviderResult holds the string denoting the provider_result field in the database.
	FieldProviderResult = "provider_result"
	// FieldIdempotencyKey holds the string denoting the idempotency_key field in the database.
	FieldIdempotencyKey = "idempotency_key"
	// FieldSuccessURL holds the string denoting the success_url field in the database.
	FieldSuccessURL = "success_url"
	// FieldFailureURL holds the string denoting the failure_url field in the database.
	FieldFailureURL = "failure_url"
	// FieldCancelURL holds the string denoting the cancel_url field in the database.
	FieldCancelURL = "cancel_url"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldCancelledAt holds the string denoting the cancelled_at field in the database.
	FieldCancelledAt = "cancelled_at"
	// FieldFailureReason holds the string denoting the failure_reason field in the database.
	FieldFailureReason = "failure_reason"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// Table holds the table name of the checkoutsession in the database.
	Table = "checkout_sessions"
)

// Columns holds all SQL columns for checkoutsession fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldStatus,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldCreatedBy,
	FieldUpdatedBy,
	FieldEnvironmentID,
	FieldCustomerID,
	FieldAction,
	FieldCheckoutStatus,
	FieldPaymentProvider,
	FieldCheckoutInvoiceID,
	FieldCheckoutPaymentID,
	FieldConfiguration,
	FieldResult,
	FieldProviderResult,
	FieldIdempotencyKey,
	FieldSuccessURL,
	FieldFailureURL,
	FieldCancelURL,
	FieldExpiresAt,
	FieldCompletedAt,
	FieldCancelledAt,
	FieldFailureReason,
	FieldMetadata,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	TenantIDValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultEnvironmentID holds the default value on creation for the "environment_id" field.
	DefaultEnvironmentID string
	// CustomerIDValidator is a validator for the "customer_id" field. It is called by the builders before save.
	CustomerIDValidator func(string) error
	// ActionValidator is a validator for the "action" field. It is called by the builders before save.
	ActionValidator func(string) error
	// DefaultCheckoutStatus holds the default value on creation for the "checkout_status" field.
	DefaultCheckoutStatus types.CheckoutStatus
	// PaymentProviderValidator is a validator for the "payment_provider" field. It is called by the builders before save.
	PaymentProviderValidator func(string) error
)

// OrderOption defines the ordering options for the CheckoutSession queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByEnvironmentID orders the results by the environment_id field.
func ByEnvironmentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnvironmentID, opts...).ToFunc()
}

// ByCustomerID orders the results by the customer_id field.
func ByCustomerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomerID, opts...).ToFunc()
}

// ByAction orders the results by the action field.
func ByAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAction, opts...).ToFunc()
}

// ByCheckoutStatus orders the results by the checkout_status field.
func ByCheckoutStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCheckoutStatus, opts...).ToFunc()
}

// ByPaymentProvider orders the results by the payment_provider field.
func ByPaymentProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentProvider, opts...).ToFunc()
}

// ByCheckoutInvoiceID orders the results by the checkout_invoice_id field.
func ByCheckoutInvoiceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCheckoutInvoiceID, opts...).ToFunc()
}

// ByCheckoutPaymentID orders the results by the checkout_payment_id field.
func ByCheckoutPaymentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCheckoutPaymentID, opts...).ToFunc()
}

// ByIdempotencyKey orders the results by the idempotency_key field.
func ByIdempotencyKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKey, opts...).ToFunc()
}

// BySuccessURL orders the results by the success_url field.
func BySuccessURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuccessURL, opts...).ToFunc()
}

// ByFailureURL orders the results by the failure_url field.
func ByFailureURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailureURL, opts...).ToFunc()
}

// ByCancelURL orders the results by the cancel_url field.
func ByCancelURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCancelURL, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByCancelledAt orders the results by the cancelled_at field.
func ByCancelledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCancelledAt, opts...).ToFunc()
}

// ByFailureReason orders the results by the failure_reason field.
func ByFailureReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailureReason, opts...).ToFunc()
}
