// Code generated by ent, DO NOT EDIT.

package checkoutsession

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/flexprice/flexprice/ent/predicate"
	"github.com/flexprice/flexprice/internal/types"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldContainsFold(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldTenantID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldUpdatedBy, v))
}

// EnvironmentID applies equality check predicate on the "environment_id" field. It's identical to EnvironmentIDEQ.
func EnvironmentID(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldEnvironmentID, v))
}

// CustomerID applies equality check predicate on the "customer_id" field. It's identical to CustomerIDEQ.
func CustomerID(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldCustomerID, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v types.CheckoutAction) predicate.CheckoutSession {
	vc := string(v)
	return predicate.CheckoutSession(sql.FieldEQ(FieldAction, vc))
}

// CheckoutStatus applies equality check predicate on the "checkout_status" field. It's identical to CheckoutStatusEQ.
func CheckoutStatus(v types.CheckoutStatus) predicate.CheckoutSession {
	vc := string(v)
	return predicate.CheckoutSession(sql.FieldEQ(FieldCheckoutStatus, vc))
}

// PaymentProvider applies equality check predicate on the "payment_provider" field. It's identical to PaymentProviderEQ.
func PaymentProvider(v types.CheckoutPaymentProvider) predicate.CheckoutSession {
	vc := string(v)
	return predicate.CheckoutSession(sql.FieldEQ(FieldPaymentProvider, vc))
}

// CheckoutInvoiceID applies equality check predicate on the "checkout_invoice_id" field. It's identical to CheckoutInvoiceIDEQ.
func CheckoutInvoiceID(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldCheckoutInvoiceID, v))
}

// CheckoutPaymentID applies equality check predicate on the "checkout_payment_id" field. It's identical to CheckoutPaymentIDEQ.
func CheckoutPaymentID(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldCheckoutPaymentID, v))
}

// IdempotencyKey applies equality check predicate on the "idempotency_key" field. It's identical to IdempotencyKeyEQ.
func IdempotencyKey(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldIdempotencyKey, v))
}

// SuccessURL applies equality check predicate on the "success_url" field. It's identical to SuccessURLEQ.
func SuccessURL(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldSuccessURL, v))
}

// FailureURL applies equality check predicate on the "failure_url" field. It's identical to FailureURLEQ.
func FailureURL(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldFailureURL, v))
}

// CancelURL applies equality check predicate on the "cancel_url" field. It's identical to CancelURLEQ.
func CancelURL(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldCancelURL, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldExpiresAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldCompletedAt, v))
}

// CancelledAt applies equality check predicate on the "cancelled_at" field. It's identical to CancelledAtEQ.
func CancelledAt(v time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldCancelledAt, v))
}

// FailureReason applies equality check predicate on the "failure_reason" field. It's identical to FailureReasonEQ.
func FailureReason(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldFailureReason, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldContainsFold(FieldTenantID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLTE(FieldUpdatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// EnvironmentIDEQ applies the EQ predicate on the "environment_id" field.
func EnvironmentIDEQ(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldEnvironmentID, v))
}

// EnvironmentIDNEQ applies the NEQ predicate on the "environment_id" field.
func EnvironmentIDNEQ(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNEQ(FieldEnvironmentID, v))
}

// EnvironmentIDIn applies the In predicate on the "environment_id" field.
func EnvironmentIDIn(vs ...string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldIn(FieldEnvironmentID, vs...))
}

// EnvironmentIDNotIn applies the NotIn predicate on the "environment_id" field.
func EnvironmentIDNotIn(vs ...string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNotIn(FieldEnvironmentID, vs...))
}

// EnvironmentIDGT applies the GT predicate on the "environment_id" field.
func EnvironmentIDGT(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGT(FieldEnvironmentID, v))
}

// EnvironmentIDGTE applies the GTE predicate on the "environment_id" field.
func EnvironmentIDGTE(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGTE(FieldEnvironmentID, v))
}

// EnvironmentIDLT applies the LT predicate on the "environment_id" field.
func EnvironmentIDLT(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLT(FieldEnvironmentID, v))
}

// EnvironmentIDLTE applies the LTE predicate on the "environment_id" field.
func EnvironmentIDLTE(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLTE(FieldEnvironmentID, v))
}

// EnvironmentIDContains applies the Contains predicate on the "environment_id" field.
func EnvironmentIDContains(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldContains(FieldEnvironmentID, v))
}

// EnvironmentIDHasPrefix applies the HasPrefix predicate on the "environment_id" field.
func EnvironmentIDHasPrefix(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldHasPrefix(FieldEnvironmentID, v))
}

// EnvironmentIDHasSuffix applies the HasSuffix predicate on the "environment_id" field.
func EnvironmentIDHasSuffix(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldHasSuffix(FieldEnvironmentID, v))
}

// EnvironmentIDIsNil applies the IsNil predicate on the "environment_id" field.
func EnvironmentIDIsNil() predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldIsNull(FieldEnvironmentID))
}

// EnvironmentIDNotNil applies the NotNil predicate on the "environment_id" field.
func EnvironmentIDNotNil() predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNotNull(FieldEnvironmentID))
}

// EnvironmentIDEqualFold applies the EqualFold predicate on the "environment_id" field.
func EnvironmentIDEqualFold(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEqualFold(FieldEnvironmentID, v))
}

// EnvironmentIDContainsFold applies the ContainsFold predicate on the "environment_id" field.
func EnvironmentIDContainsFold(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldContainsFold(FieldEnvironmentID, v))
}

// CustomerIDEQ applies the EQ predicate on the "customer_id" field.
func CustomerIDEQ(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldCustomerID, v))
}

// CustomerIDNEQ applies the NEQ predicate on the "customer_id" field.
func CustomerIDNEQ(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNEQ(FieldCustomerID, v))
}

// CustomerIDIn applies the In predicate on the "customer_id" field.
func CustomerIDIn(vs ...string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldIn(FieldCustomerID, vs...))
}

// CustomerIDNotIn applies the NotIn predicate on the "customer_id" field.
func CustomerIDNotIn(vs ...string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNotIn(FieldCustomerID, vs...))
}

// CustomerIDGT applies the GT predicate on the "customer_id" field.
func CustomerIDGT(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGT(FieldCustomerID, v))
}

// CustomerIDGTE applies the GTE predicate on the "customer_id" field.
func CustomerIDGTE(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGTE(FieldCustomerID, v))
}

// CustomerIDLT applies the LT predicate on the "customer_id" field.
func CustomerIDLT(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLT(FieldCustomerID, v))
}

// CustomerIDLTE applies the LTE predicate on the "customer_id" field.
func CustomerIDLTE(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLTE(FieldCustomerID, v))
}

// CustomerIDContains applies the Contains predicate on the "customer_id" field.
func CustomerIDContains(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldContains(FieldCustomerID, v))
}

// CustomerIDHasPrefix applies the HasPrefix predicate on the "customer_id" field.
func CustomerIDHasPrefix(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldHasPrefix(FieldCustomerID, v))
}

// CustomerIDHasSuffix applies the HasSuffix predicate on the "customer_id" field.
func CustomerIDHasSuffix(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldHasSuffix(FieldCustomerID, v))
}

// CustomerIDEqualFold applies the EqualFold predicate on the "customer_id" field.
func CustomerIDEqualFold(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEqualFold(FieldCustomerID, v))
}

// CustomerIDContainsFold applies the ContainsFold predicate on the "customer_id" field.
func CustomerIDContainsFold(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldContainsFold(FieldCustomerID, v))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v types.CheckoutAction) predicate.CheckoutSession {
	vc := string(v)
	return predicate.CheckoutSession(sql.FieldEQ(FieldAction, vc))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v types.CheckoutAction) predicate.CheckoutSession {
	vc := string(v)
	return predicate.CheckoutSession(sql.FieldNEQ(FieldAction, vc))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...types.CheckoutAction) predicate.CheckoutSession {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.CheckoutSession(sql.FieldIn(FieldAction, v...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...types.CheckoutAction) predicate.CheckoutSession {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.CheckoutSession(sql.FieldNotIn(FieldAction, v...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v types.CheckoutAction) predicate.CheckoutSession {
	vc := string(v)
	return predicate.CheckoutSession(sql.FieldGT(FieldAction, vc))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v types.CheckoutAction) predicate.CheckoutSession {
	vc := string(v)
	return predicate.CheckoutSession(sql.FieldGTE(FieldAction, vc))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v types.CheckoutAction) predicate.CheckoutSession {
	vc := string(v)
	return predicate.CheckoutSession(sql.FieldLT(FieldAction, vc))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v types.CheckoutAction) predicate.CheckoutSession {
	vc := string(v)
	return predicate.CheckoutSession(sql.FieldLTE(FieldAction, vc))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v types.CheckoutAction) predicate.CheckoutSession {
	vc := string(v)
	return predicate.CheckoutSession(sql.FieldContains(FieldAction, vc))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v types.CheckoutAction) predicate.CheckoutSession {
	vc := string(v)
	return predicate.CheckoutSession(sql.FieldHasPrefix(FieldAction, vc))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v types.CheckoutAction) predicate.CheckoutSession {
	vc := string(v)
	return predicate.CheckoutSession(sql.FieldHasSuffix(FieldAction, vc))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v types.CheckoutAction) predicate.CheckoutSession {
	vc := string(v)
	return predicate.CheckoutSession(sql.FieldEqualFold(FieldAction, vc))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v types.CheckoutAction) predicate.CheckoutSession {
	vc := string(v)
	return predicate.CheckoutSession(sql.FieldContainsFold(FieldAction, vc))
}

// CheckoutStatusEQ applies the EQ predicate on the "checkout_status" field.
func CheckoutStatusEQ(v types.CheckoutStatus) predicate.CheckoutSession {
	vc := string(v)
	return predicate.CheckoutSession(sql.FieldEQ(FieldCheckoutStatus, vc))
}

// CheckoutStatusNEQ applies the NEQ predicate on the "checkout_status" field.
func CheckoutStatusNEQ(v types.CheckoutStatus) predicate.CheckoutSession {
	vc := string(v)
	return predicate.CheckoutSession(sql.FieldNEQ(FieldCheckoutStatus, vc))
}

// CheckoutStatusIn applies the In predicate on the "checkout_status" field.
func CheckoutStatusIn(vs ...types.CheckoutStatus) predicate.CheckoutSession {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.CheckoutSession(sql.FieldIn(FieldCheckoutStatus, v...))
}

// CheckoutStatusNotIn applies the NotIn predicate on the "checkout_status" field.
func CheckoutStatusNotIn(vs ...types.CheckoutStatus) predicate.CheckoutSession {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.CheckoutSession(sql.FieldNotIn(FieldCheckoutStatus, v...))
}

// CheckoutStatusGT applies the GT predicate on the "checkout_status" field.
func CheckoutStatusGT(v types.CheckoutStatus) predicate.CheckoutSession {
	vc := string(v)
	return predicate.CheckoutSession(sql.FieldGT(FieldCheckoutStatus, vc))
}

// CheckoutStatusGTE applies the GTE predicate on the "checkout_status" field.
func CheckoutStatusGTE(v types.CheckoutStatus) predicate.CheckoutSession {
	vc := string(v)
	return predicate.CheckoutSession(sql.FieldGTE(FieldCheckoutStatus, vc))
}

// CheckoutStatusLT applies the LT predicate on the "checkout_status" field.
func CheckoutStatusLT(v types.CheckoutStatus) predicate.CheckoutSession {
	vc := string(v)
	return predicate.CheckoutSession(sql.FieldLT(FieldCheckoutStatus, vc))
}

// CheckoutStatusLTE applies the LTE predicate on the "checkout_status" field.
func CheckoutStatusLTE(v types.CheckoutStatus) predicate.CheckoutSession {
	vc := string(v)
	return predicate.CheckoutSession(sql.FieldLTE(FieldCheckoutStatus, vc))
}

// CheckoutStatusContains applies the Contains predicate on the "checkout_status" field.
func CheckoutStatusContains(v types.CheckoutStatus) predicate.CheckoutSession {
	vc := string(v)
	return predicate.CheckoutSession(sql.FieldContains(FieldCheckoutStatus, vc))
}

// CheckoutStatusHasPrefix applies the HasPrefix predicate on the "checkout_status" field.
func CheckoutStatusHasPrefix(v types.CheckoutStatus) predicate.CheckoutSession {
	vc := string(v)
	return predicate.CheckoutSession(sql.FieldHasPrefix(FieldCheckoutStatus, vc))
}

// CheckoutStatusHasSuffix applies the HasSuffix predicate on the "checkout_status" field.
func CheckoutStatusHasSuffix(v types.CheckoutStatus) predicate.CheckoutSession {
	vc := string(v)
	return predicate.CheckoutSession(sql.FieldHasSuffix(FieldCheckoutStatus, vc))
}

// CheckoutStatusEqualFold applies the EqualFold predicate on the "checkout_status" field.
func CheckoutStatusEqualFold(v types.CheckoutStatus) predicate.CheckoutSession {
	vc := string(v)
	return predicate.CheckoutSession(sql.FieldEqualFold(FieldCheckoutStatus, vc))
}

// CheckoutStatusContainsFold applies the ContainsFold predicate on the "checkout_status" field.
func CheckoutStatusContainsFold(v types.CheckoutStatus) predicate.CheckoutSession {
	vc := string(v)
	return predicate.CheckoutSession(sql.FieldContainsFold(FieldCheckoutStatus, vc))
}

// PaymentProviderEQ applies the EQ predicate on the "payment_provider" field.
func PaymentProviderEQ(v types.CheckoutPaymentProvider) predicate.CheckoutSession {
	vc := string(v)
	return predicate.CheckoutSession(sql.FieldEQ(FieldPaymentProvider, vc))
}

// PaymentProviderNEQ applies the NEQ predicate on the "payment_provider" field.
func PaymentProviderNEQ(v types.CheckoutPaymentProvider) predicate.CheckoutSession {
	vc := string(v)
	return predicate.CheckoutSession(sql.FieldNEQ(FieldPaymentProvider, vc))
}

// PaymentProviderIn applies the In predicate on the "payment_provider" field.
func PaymentProviderIn(vs ...types.CheckoutPaymentProvider) predicate.CheckoutSession {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.CheckoutSession(sql.FieldIn(FieldPaymentProvider, v...))
}

// PaymentProviderNotIn applies the NotIn predicate on the "payment_provider" field.
func PaymentProviderNotIn(vs ...types.CheckoutPaymentProvider) predicate.CheckoutSession {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.CheckoutSession(sql.FieldNotIn(FieldPaymentProvider, v...))
}

// PaymentProviderGT applies the GT predicate on the "payment_provider" field.
func PaymentProviderGT(v types.CheckoutPaymentProvider) predicate.CheckoutSession {
	vc := string(v)
	return predicate.CheckoutSession(sql.FieldGT(FieldPaymentProvider, vc))
}

// PaymentProviderGTE applies the GTE predicate on the "payment_provider" field.
func PaymentProviderGTE(v types.CheckoutPaymentProvider) predicate.CheckoutSession {
	vc := string(v)
	return predicate.CheckoutSession(sql.FieldGTE(FieldPaymentProvider, vc))
}

// PaymentProviderLT applies the LT predicate on the "payment_provider" field.
func PaymentProviderLT(v types.CheckoutPaymentProvider) predicate.CheckoutSession {
	vc := string(v)
	return predicate.CheckoutSession(sql.FieldLT(FieldPaymentProvider, vc))
}

// PaymentProviderLTE applies the LTE predicate on the "payment_provider" field.
func PaymentProviderLTE(v types.CheckoutPaymentProvider) predicate.CheckoutSession {
	vc := string(v)
	return predicate.CheckoutSession(sql.FieldLTE(FieldPaymentProvider, vc))
}

// PaymentProviderContains applies the Contains predicate on the "payment_provider" field.
func PaymentProviderContains(v types.CheckoutPaymentProvider) predicate.CheckoutSession {
	vc := string(v)
	return predicate.CheckoutSession(sql.FieldContains(FieldPaymentProvider, vc))
}

// PaymentProviderHasPrefix applies the HasPrefix predicate on the "payment_provider" field.
func PaymentProviderHasPrefix(v types.CheckoutPaymentProvider) predicate.CheckoutSession {
	vc := string(v)
	return predicate.CheckoutSession(sql.FieldHasPrefix(FieldPaymentProvider, vc))
}

// PaymentProviderHasSuffix applies the HasSuffix predicate on the "payment_provider" field.
func PaymentProviderHasSuffix(v types.CheckoutPaymentProvider) predicate.CheckoutSession {
	vc := string(v)
	return predicate.CheckoutSession(sql.FieldHasSuffix(FieldPaymentProvider, vc))
}

// PaymentProviderEqualFold applies the EqualFold predicate on the "payment_provider" field.
func PaymentProviderEqualFold(v types.CheckoutPaymentProvider) predicate.CheckoutSession {
	vc := string(v)
	return predicate.CheckoutSession(sql.FieldEqualFold(FieldPaymentProvider, vc))
}

// PaymentProviderContainsFold applies the ContainsFold predicate on the "payment_provider" field.
func PaymentProviderContainsFold(v types.CheckoutPaymentProvider) predicate.CheckoutSession {
	vc := string(v)
	return predicate.CheckoutSession(sql.FieldContainsFold(FieldPaymentProvider, vc))
}

// CheckoutInvoiceIDEQ applies the EQ predicate on the "checkout_invoice_id" field.
func CheckoutInvoiceIDEQ(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldCheckoutInvoiceID, v))
}

// CheckoutInvoiceIDNEQ applies the NEQ predicate on the "checkout_invoice_id" field.
func CheckoutInvoiceIDNEQ(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNEQ(FieldCheckoutInvoiceID, v))
}

// CheckoutInvoiceIDIn applies the In predicate on the "checkout_invoice_id" field.
func CheckoutInvoiceIDIn(vs ...string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldIn(FieldCheckoutInvoiceID, vs...))
}

// CheckoutInvoiceIDNotIn applies the NotIn predicate on the "checkout_invoice_id" field.
func CheckoutInvoiceIDNotIn(vs ...string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNotIn(FieldCheckoutInvoiceID, vs...))
}

// CheckoutInvoiceIDGT applies the GT predicate on the "checkout_invoice_id" field.
func CheckoutInvoiceIDGT(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGT(FieldCheckoutInvoiceID, v))
}

// CheckoutInvoiceIDGTE applies the GTE predicate on the "checkout_invoice_id" field.
func CheckoutInvoiceIDGTE(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGTE(FieldCheckoutInvoiceID, v))
}

// CheckoutInvoiceIDLT applies the LT predicate on the "checkout_invoice_id" field.
func CheckoutInvoiceIDLT(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLT(FieldCheckoutInvoiceID, v))
}

// CheckoutInvoiceIDLTE applies the LTE predicate on the "checkout_invoice_id" field.
func CheckoutInvoiceIDLTE(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLTE(FieldCheckoutInvoiceID, v))
}

// CheckoutInvoiceIDContains applies the Contains predicate on the "checkout_invoice_id" field.
func CheckoutInvoiceIDContains(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldContains(FieldCheckoutInvoiceID, v))
}

// CheckoutInvoiceIDHasPrefix applies the HasPrefix predicate on the "checkout_invoice_id" field.
func CheckoutInvoiceIDHasPrefix(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldHasPrefix(FieldCheckoutInvoiceID, v))
}

// CheckoutInvoiceIDHasSuffix applies the HasSuffix predicate on the "checkout_invoice_id" field.
func CheckoutInvoiceIDHasSuffix(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldHasSuffix(FieldCheckoutInvoiceID, v))
}

// CheckoutInvoiceIDIsNil applies the IsNil predicate on the "checkout_invoice_id" field.
func CheckoutInvoiceIDIsNil() predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldIsNull(FieldCheckoutInvoiceID))
}

// CheckoutInvoiceIDNotNil applies the NotNil predicate on the "checkout_invoice_id" field.
func CheckoutInvoiceIDNotNil() predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNotNull(FieldCheckoutInvoiceID))
}

// CheckoutInvoiceIDEqualFold applies the EqualFold predicate on the "checkout_invoice_id" field.
func CheckoutInvoiceIDEqualFold(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEqualFold(FieldCheckoutInvoiceID, v))
}

// CheckoutInvoiceIDContainsFold applies the ContainsFold predicate on the "checkout_invoice_id" field.
func CheckoutInvoiceIDContainsFold(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldContainsFold(FieldCheckoutInvoiceID, v))
}

// CheckoutPaymentIDEQ applies the EQ predicate on the "checkout_payment_id" field.
func CheckoutPaymentIDEQ(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldCheckoutPaymentID, v))
}

// CheckoutPaymentIDNEQ applies the NEQ predicate on the "checkout_payment_id" field.
func CheckoutPaymentIDNEQ(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNEQ(FieldCheckoutPaymentID, v))
}

// CheckoutPaymentIDIn applies the In predicate on the "checkout_payment_id" field.
func CheckoutPaymentIDIn(vs ...string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldIn(FieldCheckoutPaymentID, vs...))
}

// CheckoutPaymentIDNotIn applies the NotIn predicate on the "checkout_payment_id" field.
func CheckoutPaymentIDNotIn(vs ...string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNotIn(FieldCheckoutPaymentID, vs...))
}

// CheckoutPaymentIDGT applies the GT predicate on the "checkout_payment_id" field.
func CheckoutPaymentIDGT(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGT(FieldCheckoutPaymentID, v))
}

// CheckoutPaymentIDGTE applies the GTE predicate on the "checkout_payment_id" field.
func CheckoutPaymentIDGTE(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGTE(FieldCheckoutPaymentID, v))
}

// CheckoutPaymentIDLT applies the LT predicate on the "checkout_payment_id" field.
func CheckoutPaymentIDLT(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLT(FieldCheckoutPaymentID, v))
}

// CheckoutPaymentIDLTE applies the LTE predicate on the "checkout_payment_id" field.
func CheckoutPaymentIDLTE(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLTE(FieldCheckoutPaymentID, v))
}

// CheckoutPaymentIDContains applies the Contains predicate on the "checkout_payment_id" field.
func CheckoutPaymentIDContains(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldContains(FieldCheckoutPaymentID, v))
}

// CheckoutPaymentIDHasPrefix applies the HasPrefix predicate on the "checkout_payment_id" field.
func CheckoutPaymentIDHasPrefix(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldHasPrefix(FieldCheckoutPaymentID, v))
}

// CheckoutPaymentIDHasSuffix applies the HasSuffix predicate on the "checkout_payment_id" field.
func CheckoutPaymentIDHasSuffix(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldHasSuffix(FieldCheckoutPaymentID, v))
}

// CheckoutPaymentIDIsNil applies the IsNil predicate on the "checkout_payment_id" field.
func CheckoutPaymentIDIsNil() predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldIsNull(FieldCheckoutPaymentID))
}

// CheckoutPaymentIDNotNil applies the NotNil predicate on the "checkout_payment_id" field.
func CheckoutPaymentIDNotNil() predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNotNull(FieldCheckoutPaymentID))
}

// CheckoutPaymentIDEqualFold applies the EqualFold predicate on the "checkout_payment_id" field.
func CheckoutPaymentIDEqualFold(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEqualFold(FieldCheckoutPaymentID, v))
}

// CheckoutPaymentIDContainsFold applies the ContainsFold predicate on the "checkout_payment_id" field.
func CheckoutPaymentIDContainsFold(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldContainsFold(FieldCheckoutPaymentID, v))
}

// PaymentProviderConfigIsNil applies the IsNil predicate on the "payment_provider_config" field.
func PaymentProviderConfigIsNil() predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldIsNull(FieldPaymentProviderConfig))
}

// PaymentProviderConfigNotNil applies the NotNil predicate on the "payment_provider_config" field.
func PaymentProviderConfigNotNil() predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNotNull(FieldPaymentProviderConfig))
}

// ResultIsNil applies the IsNil predicate on the "result" field.
func ResultIsNil() predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldIsNull(FieldResult))
}

// ResultNotNil applies the NotNil predicate on the "result" field.
func ResultNotNil() predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNotNull(FieldResult))
}

// ProviderResultIsNil applies the IsNil predicate on the "provider_result" field.
func ProviderResultIsNil() predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldIsNull(FieldProviderResult))
}

// ProviderResultNotNil applies the NotNil predicate on the "provider_result" field.
func ProviderResultNotNil() predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNotNull(FieldProviderResult))
}

// IdempotencyKeyEQ applies the EQ predicate on the "idempotency_key" field.
func IdempotencyKeyEQ(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyNEQ applies the NEQ predicate on the "idempotency_key" field.
func IdempotencyKeyNEQ(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyIn applies the In predicate on the "idempotency_key" field.
func IdempotencyKeyIn(vs ...string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyNotIn applies the NotIn predicate on the "idempotency_key" field.
func IdempotencyKeyNotIn(vs ...string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNotIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyGT applies the GT predicate on the "idempotency_key" field.
func IdempotencyKeyGT(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGT(FieldIdempotencyKey, v))
}

// IdempotencyKeyGTE applies the GTE predicate on the "idempotency_key" field.
func IdempotencyKeyGTE(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyLT applies the LT predicate on the "idempotency_key" field.
func IdempotencyKeyLT(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLT(FieldIdempotencyKey, v))
}

// IdempotencyKeyLTE applies the LTE predicate on the "idempotency_key" field.
func IdempotencyKeyLTE(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyContains applies the Contains predicate on the "idempotency_key" field.
func IdempotencyKeyContains(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldContains(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasPrefix applies the HasPrefix predicate on the "idempotency_key" field.
func IdempotencyKeyHasPrefix(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldHasPrefix(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasSuffix applies the HasSuffix predicate on the "idempotency_key" field.
func IdempotencyKeyHasSuffix(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldHasSuffix(FieldIdempotencyKey, v))
}

// IdempotencyKeyIsNil applies the IsNil predicate on the "idempotency_key" field.
func IdempotencyKeyIsNil() predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldIsNull(FieldIdempotencyKey))
}

// IdempotencyKeyNotNil applies the NotNil predicate on the "idempotency_key" field.
func IdempotencyKeyNotNil() predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNotNull(FieldIdempotencyKey))
}

// IdempotencyKeyEqualFold applies the EqualFold predicate on the "idempotency_key" field.
func IdempotencyKeyEqualFold(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEqualFold(FieldIdempotencyKey, v))
}

// IdempotencyKeyContainsFold applies the ContainsFold predicate on the "idempotency_key" field.
func IdempotencyKeyContainsFold(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldContainsFold(FieldIdempotencyKey, v))
}

// SuccessURLEQ applies the EQ predicate on the "success_url" field.
func SuccessURLEQ(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldSuccessURL, v))
}

// SuccessURLNEQ applies the NEQ predicate on the "success_url" field.
func SuccessURLNEQ(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNEQ(FieldSuccessURL, v))
}

// SuccessURLIn applies the In predicate on the "success_url" field.
func SuccessURLIn(vs ...string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldIn(FieldSuccessURL, vs...))
}

// SuccessURLNotIn applies the NotIn predicate on the "success_url" field.
func SuccessURLNotIn(vs ...string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNotIn(FieldSuccessURL, vs...))
}

// SuccessURLGT applies the GT predicate on the "success_url" field.
func SuccessURLGT(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGT(FieldSuccessURL, v))
}

// SuccessURLGTE applies the GTE predicate on the "success_url" field.
func SuccessURLGTE(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGTE(FieldSuccessURL, v))
}

// SuccessURLLT applies the LT predicate on the "success_url" field.
func SuccessURLLT(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLT(FieldSuccessURL, v))
}

// SuccessURLLTE applies the LTE predicate on the "success_url" field.
func SuccessURLLTE(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLTE(FieldSuccessURL, v))
}

// SuccessURLContains applies the Contains predicate on the "success_url" field.
func SuccessURLContains(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldContains(FieldSuccessURL, v))
}

// SuccessURLHasPrefix applies the HasPrefix predicate on the "success_url" field.
func SuccessURLHasPrefix(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldHasPrefix(FieldSuccessURL, v))
}

// SuccessURLHasSuffix applies the HasSuffix predicate on the "success_url" field.
func SuccessURLHasSuffix(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldHasSuffix(FieldSuccessURL, v))
}

// SuccessURLIsNil applies the IsNil predicate on the "success_url" field.
func SuccessURLIsNil() predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldIsNull(FieldSuccessURL))
}

// SuccessURLNotNil applies the NotNil predicate on the "success_url" field.
func SuccessURLNotNil() predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNotNull(FieldSuccessURL))
}

// SuccessURLEqualFold applies the EqualFold predicate on the "success_url" field.
func SuccessURLEqualFold(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEqualFold(FieldSuccessURL, v))
}

// SuccessURLContainsFold applies the ContainsFold predicate on the "success_url" field.
func SuccessURLContainsFold(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldContainsFold(FieldSuccessURL, v))
}

// FailureURLEQ applies the EQ predicate on the "failure_url" field.
func FailureURLEQ(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldFailureURL, v))
}

// FailureURLNEQ applies the NEQ predicate on the "failure_url" field.
func FailureURLNEQ(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNEQ(FieldFailureURL, v))
}

// FailureURLIn applies the In predicate on the "failure_url" field.
func FailureURLIn(vs ...string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldIn(FieldFailureURL, vs...))
}

// FailureURLNotIn applies the NotIn predicate on the "failure_url" field.
func FailureURLNotIn(vs ...string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNotIn(FieldFailureURL, vs...))
}

// FailureURLGT applies the GT predicate on the "failure_url" field.
func FailureURLGT(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGT(FieldFailureURL, v))
}

// FailureURLGTE applies the GTE predicate on the "failure_url" field.
func FailureURLGTE(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGTE(FieldFailureURL, v))
}

// FailureURLLT applies the LT predicate on the "failure_url" field.
func FailureURLLT(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLT(FieldFailureURL, v))
}

// FailureURLLTE applies the LTE predicate on the "failure_url" field.
func FailureURLLTE(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLTE(FieldFailureURL, v))
}

// FailureURLContains applies the Contains predicate on the "failure_url" field.
func FailureURLContains(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldContains(FieldFailureURL, v))
}

// FailureURLHasPrefix applies the HasPrefix predicate on the "failure_url" field.
func FailureURLHasPrefix(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldHasPrefix(FieldFailureURL, v))
}

// FailureURLHasSuffix applies the HasSuffix predicate on the "failure_url" field.
func FailureURLHasSuffix(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldHasSuffix(FieldFailureURL, v))
}

// FailureURLIsNil applies the IsNil predicate on the "failure_url" field.
func FailureURLIsNil() predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldIsNull(FieldFailureURL))
}

// FailureURLNotNil applies the NotNil predicate on the "failure_url" field.
func FailureURLNotNil() predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNotNull(FieldFailureURL))
}

// FailureURLEqualFold applies the EqualFold predicate on the "failure_url" field.
func FailureURLEqualFold(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEqualFold(FieldFailureURL, v))
}

// FailureURLContainsFold applies the ContainsFold predicate on the "failure_url" field.
func FailureURLContainsFold(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldContainsFold(FieldFailureURL, v))
}

// CancelURLEQ applies the EQ predicate on the "cancel_url" field.
func CancelURLEQ(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldCancelURL, v))
}

// CancelURLNEQ applies the NEQ predicate on the "cancel_url" field.
func CancelURLNEQ(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNEQ(FieldCancelURL, v))
}

// CancelURLIn applies the In predicate on the "cancel_url" field.
func CancelURLIn(vs ...string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldIn(FieldCancelURL, vs...))
}

// CancelURLNotIn applies the NotIn predicate on the "cancel_url" field.
func CancelURLNotIn(vs ...string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNotIn(FieldCancelURL, vs...))
}

// CancelURLGT applies the GT predicate on the "cancel_url" field.
func CancelURLGT(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGT(FieldCancelURL, v))
}

// CancelURLGTE applies the GTE predicate on the "cancel_url" field.
func CancelURLGTE(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGTE(FieldCancelURL, v))
}

// CancelURLLT applies the LT predicate on the "cancel_url" field.
func CancelURLLT(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLT(FieldCancelURL, v))
}

// CancelURLLTE applies the LTE predicate on the "cancel_url" field.
func CancelURLLTE(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLTE(FieldCancelURL, v))
}

// CancelURLContains applies the Contains predicate on the "cancel_url" field.
func CancelURLContains(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldContains(FieldCancelURL, v))
}

// CancelURLHasPrefix applies the HasPrefix predicate on the "cancel_url" field.
func CancelURLHasPrefix(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldHasPrefix(FieldCancelURL, v))
}

// CancelURLHasSuffix applies the HasSuffix predicate on the "cancel_url" field.
func CancelURLHasSuffix(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldHasSuffix(FieldCancelURL, v))
}

// CancelURLIsNil applies the IsNil predicate on the "cancel_url" field.
func CancelURLIsNil() predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldIsNull(FieldCancelURL))
}

// CancelURLNotNil applies the NotNil predicate on the "cancel_url" field.
func CancelURLNotNil() predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNotNull(FieldCancelURL))
}

// CancelURLEqualFold applies the EqualFold predicate on the "cancel_url" field.
func CancelURLEqualFold(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEqualFold(FieldCancelURL, v))
}

// CancelURLContainsFold applies the ContainsFold predicate on the "cancel_url" field.
func CancelURLContainsFold(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldContainsFold(FieldCancelURL, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNotNull(FieldExpiresAt))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNotNull(FieldCompletedAt))
}

// CancelledAtEQ applies the EQ predicate on the "cancelled_at" field.
func CancelledAtEQ(v time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldCancelledAt, v))
}

// CancelledAtNEQ applies the NEQ predicate on the "cancelled_at" field.
func CancelledAtNEQ(v time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNEQ(FieldCancelledAt, v))
}

// CancelledAtIn applies the In predicate on the "cancelled_at" field.
func CancelledAtIn(vs ...time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldIn(FieldCancelledAt, vs...))
}

// CancelledAtNotIn applies the NotIn predicate on the "cancelled_at" field.
func CancelledAtNotIn(vs ...time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNotIn(FieldCancelledAt, vs...))
}

// CancelledAtGT applies the GT predicate on the "cancelled_at" field.
func CancelledAtGT(v time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGT(FieldCancelledAt, v))
}

// CancelledAtGTE applies the GTE predicate on the "cancelled_at" field.
func CancelledAtGTE(v time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGTE(FieldCancelledAt, v))
}

// CancelledAtLT applies the LT predicate on the "cancelled_at" field.
func CancelledAtLT(v time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLT(FieldCancelledAt, v))
}

// CancelledAtLTE applies the LTE predicate on the "cancelled_at" field.
func CancelledAtLTE(v time.Time) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLTE(FieldCancelledAt, v))
}

// CancelledAtIsNil applies the IsNil predicate on the "cancelled_at" field.
func CancelledAtIsNil() predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldIsNull(FieldCancelledAt))
}

// CancelledAtNotNil applies the NotNil predicate on the "cancelled_at" field.
func CancelledAtNotNil() predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNotNull(FieldCancelledAt))
}

// FailureReasonEQ applies the EQ predicate on the "failure_reason" field.
func FailureReasonEQ(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEQ(FieldFailureReason, v))
}

// FailureReasonNEQ applies the NEQ predicate on the "failure_reason" field.
func FailureReasonNEQ(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNEQ(FieldFailureReason, v))
}

// FailureReasonIn applies the In predicate on the "failure_reason" field.
func FailureReasonIn(vs ...string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldIn(FieldFailureReason, vs...))
}

// FailureReasonNotIn applies the NotIn predicate on the "failure_reason" field.
func FailureReasonNotIn(vs ...string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNotIn(FieldFailureReason, vs...))
}

// FailureReasonGT applies the GT predicate on the "failure_reason" field.
func FailureReasonGT(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGT(FieldFailureReason, v))
}

// FailureReasonGTE applies the GTE predicate on the "failure_reason" field.
func FailureReasonGTE(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldGTE(FieldFailureReason, v))
}

// FailureReasonLT applies the LT predicate on the "failure_reason" field.
func FailureReasonLT(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLT(FieldFailureReason, v))
}

// FailureReasonLTE applies the LTE predicate on the "failure_reason" field.
func FailureReasonLTE(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldLTE(FieldFailureReason, v))
}

// FailureReasonContains applies the Contains predicate on the "failure_reason" field.
func FailureReasonContains(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldContains(FieldFailureReason, v))
}

// FailureReasonHasPrefix applies the HasPrefix predicate on the "failure_reason" field.
func FailureReasonHasPrefix(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldHasPrefix(FieldFailureReason, v))
}

// FailureReasonHasSuffix applies the HasSuffix predicate on the "failure_reason" field.
func FailureReasonHasSuffix(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldHasSuffix(FieldFailureReason, v))
}

// FailureReasonIsNil applies the IsNil predicate on the "failure_reason" field.
func FailureReasonIsNil() predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldIsNull(FieldFailureReason))
}

// FailureReasonNotNil applies the NotNil predicate on the "failure_reason" field.
func FailureReasonNotNil() predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNotNull(FieldFailureReason))
}

// FailureReasonEqualFold applies the EqualFold predicate on the "failure_reason" field.
func FailureReasonEqualFold(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldEqualFold(FieldFailureReason, v))
}

// FailureReasonContainsFold applies the ContainsFold predicate on the "failure_reason" field.
func FailureReasonContainsFold(v string) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldContainsFold(FieldFailureReason, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.FieldNotNull(FieldMetadata))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CheckoutSession) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CheckoutSession) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CheckoutSession) predicate.CheckoutSession {
	return predicate.CheckoutSession(sql.NotPredicates(p))
}
