// Code generated by ent, DO NOT EDIT.

package usagerecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/flexprice/flexprice/ent/predicate"
	"github.com/shopspring/decimal"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldContainsFold(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEQ(FieldTenantID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEQ(FieldUpdatedBy, v))
}

// EnvironmentID applies equality check predicate on the "environment_id" field. It's identical to EnvironmentIDEQ.
func EnvironmentID(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEQ(FieldEnvironmentID, v))
}

// CustomerID applies equality check predicate on the "customer_id" field. It's identical to CustomerIDEQ.
func CustomerID(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEQ(FieldCustomerID, v))
}

// CustomerExternalID applies equality check predicate on the "customer_external_id" field. It's identical to CustomerExternalIDEQ.
func CustomerExternalID(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEQ(FieldCustomerExternalID, v))
}

// SubscriptionID applies equality check predicate on the "subscription_id" field. It's identical to SubscriptionIDEQ.
func SubscriptionID(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEQ(FieldSubscriptionID, v))
}

// PlanID applies equality check predicate on the "plan_id" field. It's identical to PlanIDEQ.
func PlanID(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEQ(FieldPlanID, v))
}

// Quantity applies equality check predicate on the "quantity" field. It's identical to QuantityEQ.
func Quantity(v decimal.Decimal) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEQ(FieldQuantity, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v decimal.Decimal) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEQ(FieldAmount, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEQ(FieldCurrency, v))
}

// PeriodStart applies equality check predicate on the "period_start" field. It's identical to PeriodStartEQ.
func PeriodStart(v time.Time) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEQ(FieldPeriodStart, v))
}

// PeriodEnd applies equality check predicate on the "period_end" field. It's identical to PeriodEndEQ.
func PeriodEnd(v time.Time) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEQ(FieldPeriodEnd, v))
}

// AllProvidersSynced applies equality check predicate on the "all_providers_synced" field. It's identical to AllProvidersSyncedEQ.
func AllProvidersSynced(v bool) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEQ(FieldAllProvidersSynced, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldContainsFold(FieldTenantID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldLTE(FieldUpdatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// EnvironmentIDEQ applies the EQ predicate on the "environment_id" field.
func EnvironmentIDEQ(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEQ(FieldEnvironmentID, v))
}

// EnvironmentIDNEQ applies the NEQ predicate on the "environment_id" field.
func EnvironmentIDNEQ(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNEQ(FieldEnvironmentID, v))
}

// EnvironmentIDIn applies the In predicate on the "environment_id" field.
func EnvironmentIDIn(vs ...string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldIn(FieldEnvironmentID, vs...))
}

// EnvironmentIDNotIn applies the NotIn predicate on the "environment_id" field.
func EnvironmentIDNotIn(vs ...string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNotIn(FieldEnvironmentID, vs...))
}

// EnvironmentIDGT applies the GT predicate on the "environment_id" field.
func EnvironmentIDGT(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldGT(FieldEnvironmentID, v))
}

// EnvironmentIDGTE applies the GTE predicate on the "environment_id" field.
func EnvironmentIDGTE(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldGTE(FieldEnvironmentID, v))
}

// EnvironmentIDLT applies the LT predicate on the "environment_id" field.
func EnvironmentIDLT(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldLT(FieldEnvironmentID, v))
}

// EnvironmentIDLTE applies the LTE predicate on the "environment_id" field.
func EnvironmentIDLTE(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldLTE(FieldEnvironmentID, v))
}

// EnvironmentIDContains applies the Contains predicate on the "environment_id" field.
func EnvironmentIDContains(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldContains(FieldEnvironmentID, v))
}

// EnvironmentIDHasPrefix applies the HasPrefix predicate on the "environment_id" field.
func EnvironmentIDHasPrefix(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldHasPrefix(FieldEnvironmentID, v))
}

// EnvironmentIDHasSuffix applies the HasSuffix predicate on the "environment_id" field.
func EnvironmentIDHasSuffix(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldHasSuffix(FieldEnvironmentID, v))
}

// EnvironmentIDIsNil applies the IsNil predicate on the "environment_id" field.
func EnvironmentIDIsNil() predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldIsNull(FieldEnvironmentID))
}

// EnvironmentIDNotNil applies the NotNil predicate on the "environment_id" field.
func EnvironmentIDNotNil() predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNotNull(FieldEnvironmentID))
}

// EnvironmentIDEqualFold applies the EqualFold predicate on the "environment_id" field.
func EnvironmentIDEqualFold(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEqualFold(FieldEnvironmentID, v))
}

// EnvironmentIDContainsFold applies the ContainsFold predicate on the "environment_id" field.
func EnvironmentIDContainsFold(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldContainsFold(FieldEnvironmentID, v))
}

// CustomerIDEQ applies the EQ predicate on the "customer_id" field.
func CustomerIDEQ(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEQ(FieldCustomerID, v))
}

// CustomerIDNEQ applies the NEQ predicate on the "customer_id" field.
func CustomerIDNEQ(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNEQ(FieldCustomerID, v))
}

// CustomerIDIn applies the In predicate on the "customer_id" field.
func CustomerIDIn(vs ...string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldIn(FieldCustomerID, vs...))
}

// CustomerIDNotIn applies the NotIn predicate on the "customer_id" field.
func CustomerIDNotIn(vs ...string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNotIn(FieldCustomerID, vs...))
}

// CustomerIDGT applies the GT predicate on the "customer_id" field.
func CustomerIDGT(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldGT(FieldCustomerID, v))
}

// CustomerIDGTE applies the GTE predicate on the "customer_id" field.
func CustomerIDGTE(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldGTE(FieldCustomerID, v))
}

// CustomerIDLT applies the LT predicate on the "customer_id" field.
func CustomerIDLT(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldLT(FieldCustomerID, v))
}

// CustomerIDLTE applies the LTE predicate on the "customer_id" field.
func CustomerIDLTE(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldLTE(FieldCustomerID, v))
}

// CustomerIDContains applies the Contains predicate on the "customer_id" field.
func CustomerIDContains(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldContains(FieldCustomerID, v))
}

// CustomerIDHasPrefix applies the HasPrefix predicate on the "customer_id" field.
func CustomerIDHasPrefix(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldHasPrefix(FieldCustomerID, v))
}

// CustomerIDHasSuffix applies the HasSuffix predicate on the "customer_id" field.
func CustomerIDHasSuffix(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldHasSuffix(FieldCustomerID, v))
}

// CustomerIDEqualFold applies the EqualFold predicate on the "customer_id" field.
func CustomerIDEqualFold(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEqualFold(FieldCustomerID, v))
}

// CustomerIDContainsFold applies the ContainsFold predicate on the "customer_id" field.
func CustomerIDContainsFold(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldContainsFold(FieldCustomerID, v))
}

// CustomerExternalIDEQ applies the EQ predicate on the "customer_external_id" field.
func CustomerExternalIDEQ(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEQ(FieldCustomerExternalID, v))
}

// CustomerExternalIDNEQ applies the NEQ predicate on the "customer_external_id" field.
func CustomerExternalIDNEQ(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNEQ(FieldCustomerExternalID, v))
}

// CustomerExternalIDIn applies the In predicate on the "customer_external_id" field.
func CustomerExternalIDIn(vs ...string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldIn(FieldCustomerExternalID, vs...))
}

// CustomerExternalIDNotIn applies the NotIn predicate on the "customer_external_id" field.
func CustomerExternalIDNotIn(vs ...string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNotIn(FieldCustomerExternalID, vs...))
}

// CustomerExternalIDGT applies the GT predicate on the "customer_external_id" field.
func CustomerExternalIDGT(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldGT(FieldCustomerExternalID, v))
}

// CustomerExternalIDGTE applies the GTE predicate on the "customer_external_id" field.
func CustomerExternalIDGTE(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldGTE(FieldCustomerExternalID, v))
}

// CustomerExternalIDLT applies the LT predicate on the "customer_external_id" field.
func CustomerExternalIDLT(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldLT(FieldCustomerExternalID, v))
}

// CustomerExternalIDLTE applies the LTE predicate on the "customer_external_id" field.
func CustomerExternalIDLTE(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldLTE(FieldCustomerExternalID, v))
}

// CustomerExternalIDContains applies the Contains predicate on the "customer_external_id" field.
func CustomerExternalIDContains(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldContains(FieldCustomerExternalID, v))
}

// CustomerExternalIDHasPrefix applies the HasPrefix predicate on the "customer_external_id" field.
func CustomerExternalIDHasPrefix(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldHasPrefix(FieldCustomerExternalID, v))
}

// CustomerExternalIDHasSuffix applies the HasSuffix predicate on the "customer_external_id" field.
func CustomerExternalIDHasSuffix(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldHasSuffix(FieldCustomerExternalID, v))
}

// CustomerExternalIDIsNil applies the IsNil predicate on the "customer_external_id" field.
func CustomerExternalIDIsNil() predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldIsNull(FieldCustomerExternalID))
}

// CustomerExternalIDNotNil applies the NotNil predicate on the "customer_external_id" field.
func CustomerExternalIDNotNil() predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNotNull(FieldCustomerExternalID))
}

// CustomerExternalIDEqualFold applies the EqualFold predicate on the "customer_external_id" field.
func CustomerExternalIDEqualFold(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEqualFold(FieldCustomerExternalID, v))
}

// CustomerExternalIDContainsFold applies the ContainsFold predicate on the "customer_external_id" field.
func CustomerExternalIDContainsFold(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldContainsFold(FieldCustomerExternalID, v))
}

// SubscriptionIDEQ applies the EQ predicate on the "subscription_id" field.
func SubscriptionIDEQ(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEQ(FieldSubscriptionID, v))
}

// SubscriptionIDNEQ applies the NEQ predicate on the "subscription_id" field.
func SubscriptionIDNEQ(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNEQ(FieldSubscriptionID, v))
}

// SubscriptionIDIn applies the In predicate on the "subscription_id" field.
func SubscriptionIDIn(vs ...string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldIn(FieldSubscriptionID, vs...))
}

// SubscriptionIDNotIn applies the NotIn predicate on the "subscription_id" field.
func SubscriptionIDNotIn(vs ...string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNotIn(FieldSubscriptionID, vs...))
}

// SubscriptionIDGT applies the GT predicate on the "subscription_id" field.
func SubscriptionIDGT(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldGT(FieldSubscriptionID, v))
}

// SubscriptionIDGTE applies the GTE predicate on the "subscription_id" field.
func SubscriptionIDGTE(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldGTE(FieldSubscriptionID, v))
}

// SubscriptionIDLT applies the LT predicate on the "subscription_id" field.
func SubscriptionIDLT(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldLT(FieldSubscriptionID, v))
}

// SubscriptionIDLTE applies the LTE predicate on the "subscription_id" field.
func SubscriptionIDLTE(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldLTE(FieldSubscriptionID, v))
}

// SubscriptionIDContains applies the Contains predicate on the "subscription_id" field.
func SubscriptionIDContains(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldContains(FieldSubscriptionID, v))
}

// SubscriptionIDHasPrefix applies the HasPrefix predicate on the "subscription_id" field.
func SubscriptionIDHasPrefix(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldHasPrefix(FieldSubscriptionID, v))
}

// SubscriptionIDHasSuffix applies the HasSuffix predicate on the "subscription_id" field.
func SubscriptionIDHasSuffix(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldHasSuffix(FieldSubscriptionID, v))
}

// SubscriptionIDEqualFold applies the EqualFold predicate on the "subscription_id" field.
func SubscriptionIDEqualFold(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEqualFold(FieldSubscriptionID, v))
}

// SubscriptionIDContainsFold applies the ContainsFold predicate on the "subscription_id" field.
func SubscriptionIDContainsFold(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldContainsFold(FieldSubscriptionID, v))
}

// PlanIDEQ applies the EQ predicate on the "plan_id" field.
func PlanIDEQ(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEQ(FieldPlanID, v))
}

// PlanIDNEQ applies the NEQ predicate on the "plan_id" field.
func PlanIDNEQ(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNEQ(FieldPlanID, v))
}

// PlanIDIn applies the In predicate on the "plan_id" field.
func PlanIDIn(vs ...string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldIn(FieldPlanID, vs...))
}

// PlanIDNotIn applies the NotIn predicate on the "plan_id" field.
func PlanIDNotIn(vs ...string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNotIn(FieldPlanID, vs...))
}

// PlanIDGT applies the GT predicate on the "plan_id" field.
func PlanIDGT(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldGT(FieldPlanID, v))
}

// PlanIDGTE applies the GTE predicate on the "plan_id" field.
func PlanIDGTE(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldGTE(FieldPlanID, v))
}

// PlanIDLT applies the LT predicate on the "plan_id" field.
func PlanIDLT(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldLT(FieldPlanID, v))
}

// PlanIDLTE applies the LTE predicate on the "plan_id" field.
func PlanIDLTE(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldLTE(FieldPlanID, v))
}

// PlanIDContains applies the Contains predicate on the "plan_id" field.
func PlanIDContains(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldContains(FieldPlanID, v))
}

// PlanIDHasPrefix applies the HasPrefix predicate on the "plan_id" field.
func PlanIDHasPrefix(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldHasPrefix(FieldPlanID, v))
}

// PlanIDHasSuffix applies the HasSuffix predicate on the "plan_id" field.
func PlanIDHasSuffix(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldHasSuffix(FieldPlanID, v))
}

// PlanIDEqualFold applies the EqualFold predicate on the "plan_id" field.
func PlanIDEqualFold(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEqualFold(FieldPlanID, v))
}

// PlanIDContainsFold applies the ContainsFold predicate on the "plan_id" field.
func PlanIDContainsFold(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldContainsFold(FieldPlanID, v))
}

// QuantityEQ applies the EQ predicate on the "quantity" field.
func QuantityEQ(v decimal.Decimal) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEQ(FieldQuantity, v))
}

// QuantityNEQ applies the NEQ predicate on the "quantity" field.
func QuantityNEQ(v decimal.Decimal) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNEQ(FieldQuantity, v))
}

// QuantityIn applies the In predicate on the "quantity" field.
func QuantityIn(vs ...decimal.Decimal) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldIn(FieldQuantity, vs...))
}

// QuantityNotIn applies the NotIn predicate on the "quantity" field.
func QuantityNotIn(vs ...decimal.Decimal) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNotIn(FieldQuantity, vs...))
}

// QuantityGT applies the GT predicate on the "quantity" field.
func QuantityGT(v decimal.Decimal) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldGT(FieldQuantity, v))
}

// QuantityGTE applies the GTE predicate on the "quantity" field.
func QuantityGTE(v decimal.Decimal) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldGTE(FieldQuantity, v))
}

// QuantityLT applies the LT predicate on the "quantity" field.
func QuantityLT(v decimal.Decimal) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldLT(FieldQuantity, v))
}

// QuantityLTE applies the LTE predicate on the "quantity" field.
func QuantityLTE(v decimal.Decimal) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldLTE(FieldQuantity, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v decimal.Decimal) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v decimal.Decimal) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...decimal.Decimal) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...decimal.Decimal) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v decimal.Decimal) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v decimal.Decimal) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v decimal.Decimal) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v decimal.Decimal) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldLTE(FieldAmount, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldContainsFold(FieldCurrency, v))
}

// PeriodStartEQ applies the EQ predicate on the "period_start" field.
func PeriodStartEQ(v time.Time) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEQ(FieldPeriodStart, v))
}

// PeriodStartNEQ applies the NEQ predicate on the "period_start" field.
func PeriodStartNEQ(v time.Time) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNEQ(FieldPeriodStart, v))
}

// PeriodStartIn applies the In predicate on the "period_start" field.
func PeriodStartIn(vs ...time.Time) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldIn(FieldPeriodStart, vs...))
}

// PeriodStartNotIn applies the NotIn predicate on the "period_start" field.
func PeriodStartNotIn(vs ...time.Time) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNotIn(FieldPeriodStart, vs...))
}

// PeriodStartGT applies the GT predicate on the "period_start" field.
func PeriodStartGT(v time.Time) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldGT(FieldPeriodStart, v))
}

// PeriodStartGTE applies the GTE predicate on the "period_start" field.
func PeriodStartGTE(v time.Time) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldGTE(FieldPeriodStart, v))
}

// PeriodStartLT applies the LT predicate on the "period_start" field.
func PeriodStartLT(v time.Time) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldLT(FieldPeriodStart, v))
}

// PeriodStartLTE applies the LTE predicate on the "period_start" field.
func PeriodStartLTE(v time.Time) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldLTE(FieldPeriodStart, v))
}

// PeriodEndEQ applies the EQ predicate on the "period_end" field.
func PeriodEndEQ(v time.Time) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEQ(FieldPeriodEnd, v))
}

// PeriodEndNEQ applies the NEQ predicate on the "period_end" field.
func PeriodEndNEQ(v time.Time) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNEQ(FieldPeriodEnd, v))
}

// PeriodEndIn applies the In predicate on the "period_end" field.
func PeriodEndIn(vs ...time.Time) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldIn(FieldPeriodEnd, vs...))
}

// PeriodEndNotIn applies the NotIn predicate on the "period_end" field.
func PeriodEndNotIn(vs ...time.Time) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNotIn(FieldPeriodEnd, vs...))
}

// PeriodEndGT applies the GT predicate on the "period_end" field.
func PeriodEndGT(v time.Time) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldGT(FieldPeriodEnd, v))
}

// PeriodEndGTE applies the GTE predicate on the "period_end" field.
func PeriodEndGTE(v time.Time) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldGTE(FieldPeriodEnd, v))
}

// PeriodEndLT applies the LT predicate on the "period_end" field.
func PeriodEndLT(v time.Time) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldLT(FieldPeriodEnd, v))
}

// PeriodEndLTE applies the LTE predicate on the "period_end" field.
func PeriodEndLTE(v time.Time) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldLTE(FieldPeriodEnd, v))
}

// SyncsIsNil applies the IsNil predicate on the "syncs" field.
func SyncsIsNil() predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldIsNull(FieldSyncs))
}

// SyncsNotNil applies the NotNil predicate on the "syncs" field.
func SyncsNotNil() predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNotNull(FieldSyncs))
}

// AllProvidersSyncedEQ applies the EQ predicate on the "all_providers_synced" field.
func AllProvidersSyncedEQ(v bool) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldEQ(FieldAllProvidersSynced, v))
}

// AllProvidersSyncedNEQ applies the NEQ predicate on the "all_providers_synced" field.
func AllProvidersSyncedNEQ(v bool) predicate.UsageRecord {
	return predicate.UsageRecord(sql.FieldNEQ(FieldAllProvidersSynced, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UsageRecord) predicate.UsageRecord {
	return predicate.UsageRecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UsageRecord) predicate.UsageRecord {
	return predicate.UsageRecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UsageRecord) predicate.UsageRecord {
	return predicate.UsageRecord(sql.NotPredicates(p))
}
