// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/flexprice/flexprice/ent/checkoutsession"
	"github.com/flexprice/flexprice/internal/types"
)

// CheckoutSession is the model entity for the CheckoutSession schema.
type CheckoutSession struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID string `json:"tenant_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy string `json:"updated_by,omitempty"`
	// EnvironmentID holds the value of the "environment_id" field.
	EnvironmentID string `json:"environment_id,omitempty"`
	// CustomerID holds the value of the "customer_id" field.
	CustomerID string `json:"customer_id,omitempty"`
	// Action holds the value of the "action" field.
	Action types.CheckoutAction `json:"action,omitempty"`
	// CheckoutStatus holds the value of the "checkout_status" field.
	CheckoutStatus types.CheckoutStatus `json:"checkout_status,omitempty"`
	// PaymentProvider holds the value of the "payment_provider" field.
	PaymentProvider types.CheckoutPaymentProvider `json:"payment_provider,omitempty"`
	// CheckoutInvoiceID holds the value of the "checkout_invoice_id" field.
	CheckoutInvoiceID *string `json:"checkout_invoice_id,omitempty"`
	// CheckoutPaymentID holds the value of the "checkout_payment_id" field.
	CheckoutPaymentID *string `json:"checkout_payment_id,omitempty"`
	// Configuration holds the value of the "configuration" field.
	Configuration types.CheckoutConfiguration `json:"configuration,omitempty"`
	// Result holds the value of the "result" field.
	Result *types.CheckoutResult `json:"result,omitempty"`
	// ProviderResult holds the value of the "provider_result" field.
	ProviderResult *types.CheckoutProviderResult `json:"provider_result,omitempty"`
	// IdempotencyKey holds the value of the "idempotency_key" field.
	IdempotencyKey *string `json:"idempotency_key,omitempty"`
	// SuccessURL holds the value of the "success_url" field.
	SuccessURL *string `json:"success_url,omitempty"`
	// FailureURL holds the value of the "failure_url" field.
	FailureURL *string `json:"failure_url,omitempty"`
	// CancelURL holds the value of the "cancel_url" field.
	CancelURL *string `json:"cancel_url,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// CancelledAt holds the value of the "cancelled_at" field.
	CancelledAt *time.Time `json:"cancelled_at,omitempty"`
	// FailureReason holds the value of the "failure_reason" field.
	FailureReason *string `json:"failure_reason,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata     map[string]string `json:"metadata,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CheckoutSession) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case checkoutsession.FieldConfiguration, checkoutsession.FieldResult, checkoutsession.FieldProviderResult, checkoutsession.FieldMetadata:
			values[i] = new([]byte)
		case checkoutsession.FieldID, checkoutsession.FieldTenantID, checkoutsession.FieldStatus, checkoutsession.FieldCreatedBy, checkoutsession.FieldUpdatedBy, checkoutsession.FieldEnvironmentID, checkoutsession.FieldCustomerID, checkoutsession.FieldAction, checkoutsession.FieldCheckoutStatus, checkoutsession.FieldPaymentProvider, checkoutsession.FieldCheckoutInvoiceID, checkoutsession.FieldCheckoutPaymentID, checkoutsession.FieldIdempotencyKey, checkoutsession.FieldSuccessURL, checkoutsession.FieldFailureURL, checkoutsession.FieldCancelURL, checkoutsession.FieldFailureReason:
			values[i] = new(sql.NullString)
		case checkoutsession.FieldCreatedAt, checkoutsession.FieldUpdatedAt, checkoutsession.FieldExpiresAt, checkoutsession.FieldCompletedAt, checkoutsession.FieldCancelledAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CheckoutSession fields.
func (cs *CheckoutSession) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case checkoutsession.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				cs.ID = value.String
			}
		case checkoutsession.FieldTenantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				cs.TenantID = value.String
			}
		case checkoutsession.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				cs.Status = value.String
			}
		case checkoutsession.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				cs.CreatedAt = value.Time
			}
		case checkoutsession.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				cs.UpdatedAt = value.Time
			}
		case checkoutsession.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				cs.CreatedBy = value.String
			}
		case checkoutsession.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				cs.UpdatedBy = value.String
			}
		case checkoutsession.FieldEnvironmentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field environment_id", values[i])
			} else if value.Valid {
				cs.EnvironmentID = value.String
			}
		case checkoutsession.FieldCustomerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field customer_id", values[i])
			} else if value.Valid {
				cs.CustomerID = value.String
			}
		case checkoutsession.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				cs.Action = types.CheckoutAction(value.String)
			}
		case checkoutsession.FieldCheckoutStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field checkout_status", values[i])
			} else if value.Valid {
				cs.CheckoutStatus = types.CheckoutStatus(value.String)
			}
		case checkoutsession.FieldPaymentProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_provider", values[i])
			} else if value.Valid {
				cs.PaymentProvider = types.CheckoutPaymentProvider(value.String)
			}
		case checkoutsession.FieldCheckoutInvoiceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field checkout_invoice_id", values[i])
			} else if value.Valid {
				cs.CheckoutInvoiceID = new(string)
				*cs.CheckoutInvoiceID = value.String
			}
		case checkoutsession.FieldCheckoutPaymentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field checkout_payment_id", values[i])
			} else if value.Valid {
				cs.CheckoutPaymentID = new(string)
				*cs.CheckoutPaymentID = value.String
			}
		case checkoutsession.FieldConfiguration:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field configuration", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &cs.Configuration); err != nil {
					return fmt.Errorf("unmarshal field configuration: %w", err)
				}
			}
		case checkoutsession.FieldResult:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field result", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &cs.Result); err != nil {
					return fmt.Errorf("unmarshal field result: %w", err)
				}
			}
		case checkoutsession.FieldProviderResult:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field provider_result", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &cs.ProviderResult); err != nil {
					return fmt.Errorf("unmarshal field provider_result: %w", err)
				}
			}
		case checkoutsession.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				cs.IdempotencyKey = new(string)
				*cs.IdempotencyKey = value.String
			}
		case checkoutsession.FieldSuccessURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field success_url", values[i])
			} else if value.Valid {
				cs.SuccessURL = new(string)
				*cs.SuccessURL = value.String
			}
		case checkoutsession.FieldFailureURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field failure_url", values[i])
			} else if value.Valid {
				cs.FailureURL = new(string)
				*cs.FailureURL = value.String
			}
		case checkoutsession.FieldCancelURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cancel_url", values[i])
			} else if value.Valid {
				cs.CancelURL = new(string)
				*cs.CancelURL = value.String
			}
		case checkoutsession.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				cs.ExpiresAt = new(time.Time)
				*cs.ExpiresAt = value.Time
			}
		case checkoutsession.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				cs.CompletedAt = new(time.Time)
				*cs.CompletedAt = value.Time
			}
		case checkoutsession.FieldCancelledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field cancelled_at", values[i])
			} else if value.Valid {
				cs.CancelledAt = new(time.Time)
				*cs.CancelledAt = value.Time
			}
		case checkoutsession.FieldFailureReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field failure_reason", values[i])
			} else if value.Valid {
				cs.FailureReason = new(string)
				*cs.FailureReason = value.String
			}
		case checkoutsession.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &cs.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		default:
			cs.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CheckoutSession.
// This includes values selected through modifiers, order, etc.
func (cs *CheckoutSession) Value(name string) (ent.Value, error) {
	return cs.selectValues.Get(name)
}

// Update returns a builder for updating this CheckoutSession.
// Note that you need to call CheckoutSession.Unwrap() before calling this method if this CheckoutSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (cs *CheckoutSession) Update() *CheckoutSessionUpdateOne {
	return NewCheckoutSessionClient(cs.config).UpdateOne(cs)
}

// Unwrap unwraps the CheckoutSession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (cs *CheckoutSession) Unwrap() *CheckoutSession {
	_tx, ok := cs.config.driver.(*txDriver)
	if !ok {
		panic("ent: CheckoutSession is not a transactional entity")
	}
	cs.config.driver = _tx.drv
	return cs
}

// String implements the fmt.Stringer.
func (cs *CheckoutSession) String() string {
	var builder strings.Builder
	builder.WriteString("CheckoutSession(")
	builder.WriteString(fmt.Sprintf("id=%v, ", cs.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(cs.TenantID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(cs.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(cs.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(cs.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(cs.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(cs.UpdatedBy)
	builder.WriteString(", ")
	builder.WriteString("environment_id=")
	builder.WriteString(cs.EnvironmentID)
	builder.WriteString(", ")
	builder.WriteString("customer_id=")
	builder.WriteString(cs.CustomerID)
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(fmt.Sprintf("%v", cs.Action))
	builder.WriteString(", ")
	builder.WriteString("checkout_status=")
	builder.WriteString(fmt.Sprintf("%v", cs.CheckoutStatus))
	builder.WriteString(", ")
	builder.WriteString("payment_provider=")
	builder.WriteString(fmt.Sprintf("%v", cs.PaymentProvider))
	builder.WriteString(", ")
	if v := cs.CheckoutInvoiceID; v != nil {
		builder.WriteString("checkout_invoice_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := cs.CheckoutPaymentID; v != nil {
		builder.WriteString("checkout_payment_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("configuration=")
	builder.WriteString(fmt.Sprintf("%v", cs.Configuration))
	builder.WriteString(", ")
	builder.WriteString("result=")
	builder.WriteString(fmt.Sprintf("%v", cs.Result))
	builder.WriteString(", ")
	builder.WriteString("provider_result=")
	builder.WriteString(fmt.Sprintf("%v", cs.ProviderResult))
	builder.WriteString(", ")
	if v := cs.IdempotencyKey; v != nil {
		builder.WriteString("idempotency_key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := cs.SuccessURL; v != nil {
		builder.WriteString("success_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := cs.FailureURL; v != nil {
		builder.WriteString("failure_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := cs.CancelURL; v != nil {
		builder.WriteString("cancel_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := cs.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := cs.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := cs.CancelledAt; v != nil {
		builder.WriteString("cancelled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := cs.FailureReason; v != nil {
		builder.WriteString("failure_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", cs.Metadata))
	builder.WriteByte(')')
	return builder.String()
}

// CheckoutSessions is a parsable slice of CheckoutSession.
type CheckoutSessions []*CheckoutSession
