// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/checkoutsession"
	"github.com/flexprice/flexprice/ent/predicate"
)

// CheckoutSessionQuery is the builder for querying CheckoutSession entities.
type CheckoutSessionQuery struct {
	config
	ctx        *QueryContext
	order      []checkoutsession.OrderOption
	inters     []Interceptor
	predicates []predicate.CheckoutSession
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CheckoutSessionQuery builder.
func (csq *CheckoutSessionQuery) Where(ps ...predicate.CheckoutSession) *CheckoutSessionQuery {
	csq.predicates = append(csq.predicates, ps...)
	return csq
}

// Limit the number of records to be returned by this query.
func (csq *CheckoutSessionQuery) Limit(limit int) *CheckoutSessionQuery {
	csq.ctx.Limit = &limit
	return csq
}

// Offset to start from.
func (csq *CheckoutSessionQuery) Offset(offset int) *CheckoutSessionQuery {
	csq.ctx.Offset = &offset
	return csq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (csq *CheckoutSessionQuery) Unique(unique bool) *CheckoutSessionQuery {
	csq.ctx.Unique = &unique
	return csq
}

// Order specifies how the records should be ordered.
func (csq *CheckoutSessionQuery) Order(o ...checkoutsession.OrderOption) *CheckoutSessionQuery {
	csq.order = append(csq.order, o...)
	return csq
}

// First returns the first CheckoutSession entity from the query.
// Returns a *NotFoundError when no CheckoutSession was found.
func (csq *CheckoutSessionQuery) First(ctx context.Context) (*CheckoutSession, error) {
	nodes, err := csq.Limit(1).All(setContextOp(ctx, csq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{checkoutsession.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (csq *CheckoutSessionQuery) FirstX(ctx context.Context) *CheckoutSession {
	node, err := csq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CheckoutSession ID from the query.
// Returns a *NotFoundError when no CheckoutSession ID was found.
func (csq *CheckoutSessionQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = csq.Limit(1).IDs(setContextOp(ctx, csq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{checkoutsession.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (csq *CheckoutSessionQuery) FirstIDX(ctx context.Context) string {
	id, err := csq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CheckoutSession entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CheckoutSession entity is found.
// Returns a *NotFoundError when no CheckoutSession entities are found.
func (csq *CheckoutSessionQuery) Only(ctx context.Context) (*CheckoutSession, error) {
	nodes, err := csq.Limit(2).All(setContextOp(ctx, csq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{checkoutsession.Label}
	default:
		return nil, &NotSingularError{checkoutsession.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (csq *CheckoutSessionQuery) OnlyX(ctx context.Context) *CheckoutSession {
	node, err := csq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CheckoutSession ID in the query.
// Returns a *NotSingularError when more than one CheckoutSession ID is found.
// Returns a *NotFoundError when no entities are found.
func (csq *CheckoutSessionQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = csq.Limit(2).IDs(setContextOp(ctx, csq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{checkoutsession.Label}
	default:
		err = &NotSingularError{checkoutsession.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (csq *CheckoutSessionQuery) OnlyIDX(ctx context.Context) string {
	id, err := csq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CheckoutSessions.
func (csq *CheckoutSessionQuery) All(ctx context.Context) ([]*CheckoutSession, error) {
	ctx = setContextOp(ctx, csq.ctx, ent.OpQueryAll)
	if err := csq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CheckoutSession, *CheckoutSessionQuery]()
	return withInterceptors[[]*CheckoutSession](ctx, csq, qr, csq.inters)
}

// AllX is like All, but panics if an error occurs.
func (csq *CheckoutSessionQuery) AllX(ctx context.Context) []*CheckoutSession {
	nodes, err := csq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CheckoutSession IDs.
func (csq *CheckoutSessionQuery) IDs(ctx context.Context) (ids []string, err error) {
	if csq.ctx.Unique == nil && csq.path != nil {
		csq.Unique(true)
	}
	ctx = setContextOp(ctx, csq.ctx, ent.OpQueryIDs)
	if err = csq.Select(checkoutsession.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (csq *CheckoutSessionQuery) IDsX(ctx context.Context) []string {
	ids, err := csq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (csq *CheckoutSessionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, csq.ctx, ent.OpQueryCount)
	if err := csq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, csq, querierCount[*CheckoutSessionQuery](), csq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (csq *CheckoutSessionQuery) CountX(ctx context.Context) int {
	count, err := csq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (csq *CheckoutSessionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, csq.ctx, ent.OpQueryExist)
	switch _, err := csq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (csq *CheckoutSessionQuery) ExistX(ctx context.Context) bool {
	exist, err := csq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CheckoutSessionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (csq *CheckoutSessionQuery) Clone() *CheckoutSessionQuery {
	if csq == nil {
		return nil
	}
	return &CheckoutSessionQuery{
		config:     csq.config,
		ctx:        csq.ctx.Clone(),
		order:      append([]checkoutsession.OrderOption{}, csq.order...),
		inters:     append([]Interceptor{}, csq.inters...),
		predicates: append([]predicate.CheckoutSession{}, csq.predicates...),
		// clone intermediate query.
		sql:  csq.sql.Clone(),
		path: csq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CheckoutSession.Query().
//		GroupBy(checkoutsession.FieldTenantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (csq *CheckoutSessionQuery) GroupBy(field string, fields ...string) *CheckoutSessionGroupBy {
	csq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CheckoutSessionGroupBy{build: csq}
	grbuild.flds = &csq.ctx.Fields
	grbuild.label = checkoutsession.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//	}
//
//	client.CheckoutSession.Query().
//		Select(checkoutsession.FieldTenantID).
//		Scan(ctx, &v)
func (csq *CheckoutSessionQuery) Select(fields ...string) *CheckoutSessionSelect {
	csq.ctx.Fields = append(csq.ctx.Fields, fields...)
	sbuild := &CheckoutSessionSelect{CheckoutSessionQuery: csq}
	sbuild.label = checkoutsession.Label
	sbuild.flds, sbuild.scan = &csq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CheckoutSessionSelect configured with the given aggregations.
func (csq *CheckoutSessionQuery) Aggregate(fns ...AggregateFunc) *CheckoutSessionSelect {
	return csq.Select().Aggregate(fns...)
}

func (csq *CheckoutSessionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range csq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, csq); err != nil {
				return err
			}
		}
	}
	for _, f := range csq.ctx.Fields {
		if !checkoutsession.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if csq.path != nil {
		prev, err := csq.path(ctx)
		if err != nil {
			return err
		}
		csq.sql = prev
	}
	return nil
}

func (csq *CheckoutSessionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CheckoutSession, error) {
	var (
		nodes = []*CheckoutSession{}
		_spec = csq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CheckoutSession).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CheckoutSession{config: csq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, csq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (csq *CheckoutSessionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := csq.querySpec()
	_spec.Node.Columns = csq.ctx.Fields
	if len(csq.ctx.Fields) > 0 {
		_spec.Unique = csq.ctx.Unique != nil && *csq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, csq.driver, _spec)
}

func (csq *CheckoutSessionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(checkoutsession.Table, checkoutsession.Columns, sqlgraph.NewFieldSpec(checkoutsession.FieldID, field.TypeString))
	_spec.From = csq.sql
	if unique := csq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if csq.path != nil {
		_spec.Unique = true
	}
	if fields := csq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, checkoutsession.FieldID)
		for i := range fields {
			if fields[i] != checkoutsession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := csq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := csq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := csq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := csq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (csq *CheckoutSessionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(csq.driver.Dialect())
	t1 := builder.Table(checkoutsession.Table)
	columns := csq.ctx.Fields
	if len(columns) == 0 {
		columns = checkoutsession.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if csq.sql != nil {
		selector = csq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if csq.ctx.Unique != nil && *csq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range csq.predicates {
		p(selector)
	}
	for _, p := range csq.order {
		p(selector)
	}
	if offset := csq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := csq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CheckoutSessionGroupBy is the group-by builder for CheckoutSession entities.
type CheckoutSessionGroupBy struct {
	selector
	build *CheckoutSessionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (csgb *CheckoutSessionGroupBy) Aggregate(fns ...AggregateFunc) *CheckoutSessionGroupBy {
	csgb.fns = append(csgb.fns, fns...)
	return csgb
}

// Scan applies the selector query and scans the result into the given value.
func (csgb *CheckoutSessionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, csgb.build.ctx, ent.OpQueryGroupBy)
	if err := csgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CheckoutSessionQuery, *CheckoutSessionGroupBy](ctx, csgb.build, csgb, csgb.build.inters, v)
}

func (csgb *CheckoutSessionGroupBy) sqlScan(ctx context.Context, root *CheckoutSessionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(csgb.fns))
	for _, fn := range csgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*csgb.flds)+len(csgb.fns))
		for _, f := range *csgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*csgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := csgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CheckoutSessionSelect is the builder for selecting fields of CheckoutSession entities.
type CheckoutSessionSelect struct {
	*CheckoutSessionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (css *CheckoutSessionSelect) Aggregate(fns ...AggregateFunc) *CheckoutSessionSelect {
	css.fns = append(css.fns, fns...)
	return css
}

// Scan applies the selector query and scans the result into the given value.
func (css *CheckoutSessionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, css.ctx, ent.OpQuerySelect)
	if err := css.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CheckoutSessionQuery, *CheckoutSessionSelect](ctx, css.CheckoutSessionQuery, css, css.inters, v)
}

func (css *CheckoutSessionSelect) sqlScan(ctx context.Context, root *CheckoutSessionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(css.fns))
	for _, fn := range css.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*css.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := css.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
