// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/checkoutsession"
	"github.com/flexprice/flexprice/internal/types"
)

// CheckoutSessionCreate is the builder for creating a CheckoutSession entity.
type CheckoutSessionCreate struct {
	config
	mutation *CheckoutSessionMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (csc *CheckoutSessionCreate) SetTenantID(s string) *CheckoutSessionCreate {
	csc.mutation.SetTenantID(s)
	return csc
}

// SetStatus sets the "status" field.
func (csc *CheckoutSessionCreate) SetStatus(s string) *CheckoutSessionCreate {
	csc.mutation.SetStatus(s)
	return csc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (csc *CheckoutSessionCreate) SetNillableStatus(s *string) *CheckoutSessionCreate {
	if s != nil {
		csc.SetStatus(*s)
	}
	return csc
}

// SetCreatedAt sets the "created_at" field.
func (csc *CheckoutSessionCreate) SetCreatedAt(t time.Time) *CheckoutSessionCreate {
	csc.mutation.SetCreatedAt(t)
	return csc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (csc *CheckoutSessionCreate) SetNillableCreatedAt(t *time.Time) *CheckoutSessionCreate {
	if t != nil {
		csc.SetCreatedAt(*t)
	}
	return csc
}

// SetUpdatedAt sets the "updated_at" field.
func (csc *CheckoutSessionCreate) SetUpdatedAt(t time.Time) *CheckoutSessionCreate {
	csc.mutation.SetUpdatedAt(t)
	return csc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (csc *CheckoutSessionCreate) SetNillableUpdatedAt(t *time.Time) *CheckoutSessionCreate {
	if t != nil {
		csc.SetUpdatedAt(*t)
	}
	return csc
}

// SetCreatedBy sets the "created_by" field.
func (csc *CheckoutSessionCreate) SetCreatedBy(s string) *CheckoutSessionCreate {
	csc.mutation.SetCreatedBy(s)
	return csc
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (csc *CheckoutSessionCreate) SetNillableCreatedBy(s *string) *CheckoutSessionCreate {
	if s != nil {
		csc.SetCreatedBy(*s)
	}
	return csc
}

// SetUpdatedBy sets the "updated_by" field.
func (csc *CheckoutSessionCreate) SetUpdatedBy(s string) *CheckoutSessionCreate {
	csc.mutation.SetUpdatedBy(s)
	return csc
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (csc *CheckoutSessionCreate) SetNillableUpdatedBy(s *string) *CheckoutSessionCreate {
	if s != nil {
		csc.SetUpdatedBy(*s)
	}
	return csc
}

// SetEnvironmentID sets the "environment_id" field.
func (csc *CheckoutSessionCreate) SetEnvironmentID(s string) *CheckoutSessionCreate {
	csc.mutation.SetEnvironmentID(s)
	return csc
}

// SetNillableEnvironmentID sets the "environment_id" field if the given value is not nil.
func (csc *CheckoutSessionCreate) SetNillableEnvironmentID(s *string) *CheckoutSessionCreate {
	if s != nil {
		csc.SetEnvironmentID(*s)
	}
	return csc
}

// SetCustomerID sets the "customer_id" field.
func (csc *CheckoutSessionCreate) SetCustomerID(s string) *CheckoutSessionCreate {
	csc.mutation.SetCustomerID(s)
	return csc
}

// SetAction sets the "action" field.
func (csc *CheckoutSessionCreate) SetAction(ta types.CheckoutAction) *CheckoutSessionCreate {
	csc.mutation.SetAction(ta)
	return csc
}

// SetCheckoutStatus sets the "checkout_status" field.
func (csc *CheckoutSessionCreate) SetCheckoutStatus(ts types.CheckoutStatus) *CheckoutSessionCreate {
	csc.mutation.SetCheckoutStatus(ts)
	return csc
}

// SetNillableCheckoutStatus sets the "checkout_status" field if the given value is not nil.
func (csc *CheckoutSessionCreate) SetNillableCheckoutStatus(ts *types.CheckoutStatus) *CheckoutSessionCreate {
	if ts != nil {
		csc.SetCheckoutStatus(*ts)
	}
	return csc
}

// SetPaymentProvider sets the "payment_provider" field.
func (csc *CheckoutSessionCreate) SetPaymentProvider(tpp types.CheckoutPaymentProvider) *CheckoutSessionCreate {
	csc.mutation.SetPaymentProvider(tpp)
	return csc
}

// SetCheckoutInvoiceID sets the "checkout_invoice_id" field.
func (csc *CheckoutSessionCreate) SetCheckoutInvoiceID(s string) *CheckoutSessionCreate {
	csc.mutation.SetCheckoutInvoiceID(s)
	return csc
}

// SetNillableCheckoutInvoiceID sets the "checkout_invoice_id" field if the given value is not nil.
func (csc *CheckoutSessionCreate) SetNillableCheckoutInvoiceID(s *string) *CheckoutSessionCreate {
	if s != nil {
		csc.SetCheckoutInvoiceID(*s)
	}
	return csc
}

// SetCheckoutPaymentID sets the "checkout_payment_id" field.
func (csc *CheckoutSessionCreate) SetCheckoutPaymentID(s string) *CheckoutSessionCreate {
	csc.mutation.SetCheckoutPaymentID(s)
	return csc
}

// SetNillableCheckoutPaymentID sets the "checkout_payment_id" field if the given value is not nil.
func (csc *CheckoutSessionCreate) SetNillableCheckoutPaymentID(s *string) *CheckoutSessionCreate {
	if s != nil {
		csc.SetCheckoutPaymentID(*s)
	}
	return csc
}

// SetConfiguration sets the "configuration" field.
func (csc *CheckoutSessionCreate) SetConfiguration(tc types.CheckoutConfiguration) *CheckoutSessionCreate {
	csc.mutation.SetConfiguration(tc)
	return csc
}

// SetResult sets the "result" field.
func (csc *CheckoutSessionCreate) SetResult(tr *types.CheckoutResult) *CheckoutSessionCreate {
	csc.mutation.SetResult(tr)
	return csc
}

// SetProviderResult sets the "provider_result" field.
func (csc *CheckoutSessionCreate) SetProviderResult(tpr *types.CheckoutProviderResult) *CheckoutSessionCreate {
	csc.mutation.SetProviderResult(tpr)
	return csc
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (csc *CheckoutSessionCreate) SetIdempotencyKey(s string) *CheckoutSessionCreate {
	csc.mutation.SetIdempotencyKey(s)
	return csc
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (csc *CheckoutSessionCreate) SetNillableIdempotencyKey(s *string) *CheckoutSessionCreate {
	if s != nil {
		csc.SetIdempotencyKey(*s)
	}
	return csc
}

// SetSuccessURL sets the "success_url" field.
func (csc *CheckoutSessionCreate) SetSuccessURL(s string) *CheckoutSessionCreate {
	csc.mutation.SetSuccessURL(s)
	return csc
}

// SetNillableSuccessURL sets the "success_url" field if the given value is not nil.
func (csc *CheckoutSessionCreate) SetNillableSuccessURL(s *string) *CheckoutSessionCreate {
	if s != nil {
		csc.SetSuccessURL(*s)
	}
	return csc
}

// SetFailureURL sets the "failure_url" field.
func (csc *CheckoutSessionCreate) SetFailureURL(s string) *CheckoutSessionCreate {
	csc.mutation.SetFailureURL(s)
	return csc
}

// SetNillableFailureURL sets the "failure_url" field if the given value is not nil.
func (csc *CheckoutSessionCreate) SetNillableFailureURL(s *string) *CheckoutSessionCreate {
	if s != nil {
		csc.SetFailureURL(*s)
	}
	return csc
}

// SetCancelURL sets the "cancel_url" field.
func (csc *CheckoutSessionCreate) SetCancelURL(s string) *CheckoutSessionCreate {
	csc.mutation.SetCancelURL(s)
	return csc
}

// SetNillableCancelURL sets the "cancel_url" field if the given value is not nil.
func (csc *CheckoutSessionCreate) SetNillableCancelURL(s *string) *CheckoutSessionCreate {
	if s != nil {
		csc.SetCancelURL(*s)
	}
	return csc
}

// SetExpiresAt sets the "expires_at" field.
func (csc *CheckoutSessionCreate) SetExpiresAt(t time.Time) *CheckoutSessionCreate {
	csc.mutation.SetExpiresAt(t)
	return csc
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (csc *CheckoutSessionCreate) SetNillableExpiresAt(t *time.Time) *CheckoutSessionCreate {
	if t != nil {
		csc.SetExpiresAt(*t)
	}
	return csc
}

// SetCompletedAt sets the "completed_at" field.
func (csc *CheckoutSessionCreate) SetCompletedAt(t time.Time) *CheckoutSessionCreate {
	csc.mutation.SetCompletedAt(t)
	return csc
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (csc *CheckoutSessionCreate) SetNillableCompletedAt(t *time.Time) *CheckoutSessionCreate {
	if t != nil {
		csc.SetCompletedAt(*t)
	}
	return csc
}

// SetCancelledAt sets the "cancelled_at" field.
func (csc *CheckoutSessionCreate) SetCancelledAt(t time.Time) *CheckoutSessionCreate {
	csc.mutation.SetCancelledAt(t)
	return csc
}

// SetNillableCancelledAt sets the "cancelled_at" field if the given value is not nil.
func (csc *CheckoutSessionCreate) SetNillableCancelledAt(t *time.Time) *CheckoutSessionCreate {
	if t != nil {
		csc.SetCancelledAt(*t)
	}
	return csc
}

// SetFailureReason sets the "failure_reason" field.
func (csc *CheckoutSessionCreate) SetFailureReason(s string) *CheckoutSessionCreate {
	csc.mutation.SetFailureReason(s)
	return csc
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (csc *CheckoutSessionCreate) SetNillableFailureReason(s *string) *CheckoutSessionCreate {
	if s != nil {
		csc.SetFailureReason(*s)
	}
	return csc
}

// SetMetadata sets the "metadata" field.
func (csc *CheckoutSessionCreate) SetMetadata(m map[string]string) *CheckoutSessionCreate {
	csc.mutation.SetMetadata(m)
	return csc
}

// SetID sets the "id" field.
func (csc *CheckoutSessionCreate) SetID(s string) *CheckoutSessionCreate {
	csc.mutation.SetID(s)
	return csc
}

// Mutation returns the CheckoutSessionMutation object of the builder.
func (csc *CheckoutSessionCreate) Mutation() *CheckoutSessionMutation {
	return csc.mutation
}

// Save creates the CheckoutSession in the database.
func (csc *CheckoutSessionCreate) Save(ctx context.Context) (*CheckoutSession, error) {
	csc.defaults()
	return withHooks(ctx, csc.sqlSave, csc.mutation, csc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (csc *CheckoutSessionCreate) SaveX(ctx context.Context) *CheckoutSession {
	v, err := csc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (csc *CheckoutSessionCreate) Exec(ctx context.Context) error {
	_, err := csc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (csc *CheckoutSessionCreate) ExecX(ctx context.Context) {
	if err := csc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (csc *CheckoutSessionCreate) defaults() {
	if _, ok := csc.mutation.Status(); !ok {
		v := checkoutsession.DefaultStatus
		csc.mutation.SetStatus(v)
	}
	if _, ok := csc.mutation.CreatedAt(); !ok {
		v := checkoutsession.DefaultCreatedAt()
		csc.mutation.SetCreatedAt(v)
	}
	if _, ok := csc.mutation.UpdatedAt(); !ok {
		v := checkoutsession.DefaultUpdatedAt()
		csc.mutation.SetUpdatedAt(v)
	}
	if _, ok := csc.mutation.EnvironmentID(); !ok {
		v := checkoutsession.DefaultEnvironmentID
		csc.mutation.SetEnvironmentID(v)
	}
	if _, ok := csc.mutation.CheckoutStatus(); !ok {
		v := checkoutsession.DefaultCheckoutStatus
		csc.mutation.SetCheckoutStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (csc *CheckoutSessionCreate) check() error {
	if _, ok := csc.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "CheckoutSession.tenant_id"`)}
	}
	if v, ok := csc.mutation.TenantID(); ok {
		if err := checkoutsession.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "CheckoutSession.tenant_id": %w`, err)}
		}
	}
	if _, ok := csc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "CheckoutSession.status"`)}
	}
	if _, ok := csc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CheckoutSession.created_at"`)}
	}
	if _, ok := csc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CheckoutSession.updated_at"`)}
	}
	if _, ok := csc.mutation.CustomerID(); !ok {
		return &ValidationError{Name: "customer_id", err: errors.New(`ent: missing required field "CheckoutSession.customer_id"`)}
	}
	if v, ok := csc.mutation.CustomerID(); ok {
		if err := checkoutsession.CustomerIDValidator(v); err != nil {
			return &ValidationError{Name: "customer_id", err: fmt.Errorf(`ent: validator failed for field "CheckoutSession.customer_id": %w`, err)}
		}
	}
	if _, ok := csc.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "CheckoutSession.action"`)}
	}
	if v, ok := csc.mutation.Action(); ok {
		if err := checkoutsession.ActionValidator(string(v)); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "CheckoutSession.action": %w`, err)}
		}
	}
	if _, ok := csc.mutation.CheckoutStatus(); !ok {
		return &ValidationError{Name: "checkout_status", err: errors.New(`ent: missing required field "CheckoutSession.checkout_status"`)}
	}
	if v, ok := csc.mutation.CheckoutStatus(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "checkout_status", err: fmt.Errorf(`ent: validator failed for field "CheckoutSession.checkout_status": %w`, err)}
		}
	}
	if _, ok := csc.mutation.PaymentProvider(); !ok {
		return &ValidationError{Name: "payment_provider", err: errors.New(`ent: missing required field "CheckoutSession.payment_provider"`)}
	}
	if v, ok := csc.mutation.PaymentProvider(); ok {
		if err := checkoutsession.PaymentProviderValidator(string(v)); err != nil {
			return &ValidationError{Name: "payment_provider", err: fmt.Errorf(`ent: validator failed for field "CheckoutSession.payment_provider": %w`, err)}
		}
	}
	if _, ok := csc.mutation.Configuration(); !ok {
		return &ValidationError{Name: "configuration", err: errors.New(`ent: missing required field "CheckoutSession.configuration"`)}
	}
	return nil
}

func (csc *CheckoutSessionCreate) sqlSave(ctx context.Context) (*CheckoutSession, error) {
	if err := csc.check(); err != nil {
		return nil, err
	}
	_node, _spec := csc.createSpec()
	if err := sqlgraph.CreateNode(ctx, csc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected CheckoutSession.ID type: %T", _spec.ID.Value)
		}
	}
	csc.mutation.id = &_node.ID
	csc.mutation.done = true
	return _node, nil
}

func (csc *CheckoutSessionCreate) createSpec() (*CheckoutSession, *sqlgraph.CreateSpec) {
	var (
		_node = &CheckoutSession{config: csc.config}
		_spec = sqlgraph.NewCreateSpec(checkoutsession.Table, sqlgraph.NewFieldSpec(checkoutsession.FieldID, field.TypeString))
	)
	if id, ok := csc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := csc.mutation.TenantID(); ok {
		_spec.SetField(checkoutsession.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := csc.mutation.Status(); ok {
		_spec.SetField(checkoutsession.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := csc.mutation.CreatedAt(); ok {
		_spec.SetField(checkoutsession.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := csc.mutation.UpdatedAt(); ok {
		_spec.SetField(checkoutsession.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := csc.mutation.CreatedBy(); ok {
		_spec.SetField(checkoutsession.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := csc.mutation.UpdatedBy(); ok {
		_spec.SetField(checkoutsession.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := csc.mutation.EnvironmentID(); ok {
		_spec.SetField(checkoutsession.FieldEnvironmentID, field.TypeString, value)
		_node.EnvironmentID = value
	}
	if value, ok := csc.mutation.CustomerID(); ok {
		_spec.SetField(checkoutsession.FieldCustomerID, field.TypeString, value)
		_node.CustomerID = value
	}
	if value, ok := csc.mutation.Action(); ok {
		_spec.SetField(checkoutsession.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := csc.mutation.CheckoutStatus(); ok {
		_spec.SetField(checkoutsession.FieldCheckoutStatus, field.TypeString, value)
		_node.CheckoutStatus = value
	}
	if value, ok := csc.mutation.PaymentProvider(); ok {
		_spec.SetField(checkoutsession.FieldPaymentProvider, field.TypeString, value)
		_node.PaymentProvider = value
	}
	if value, ok := csc.mutation.CheckoutInvoiceID(); ok {
		_spec.SetField(checkoutsession.FieldCheckoutInvoiceID, field.TypeString, value)
		_node.CheckoutInvoiceID = &value
	}
	if value, ok := csc.mutation.CheckoutPaymentID(); ok {
		_spec.SetField(checkoutsession.FieldCheckoutPaymentID, field.TypeString, value)
		_node.CheckoutPaymentID = &value
	}
	if value, ok := csc.mutation.Configuration(); ok {
		_spec.SetField(checkoutsession.FieldConfiguration, field.TypeJSON, value)
		_node.Configuration = value
	}
	if value, ok := csc.mutation.Result(); ok {
		_spec.SetField(checkoutsession.FieldResult, field.TypeJSON, value)
		_node.Result = value
	}
	if value, ok := csc.mutation.ProviderResult(); ok {
		_spec.SetField(checkoutsession.FieldProviderResult, field.TypeJSON, value)
		_node.ProviderResult = value
	}
	if value, ok := csc.mutation.IdempotencyKey(); ok {
		_spec.SetField(checkoutsession.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = &value
	}
	if value, ok := csc.mutation.SuccessURL(); ok {
		_spec.SetField(checkoutsession.FieldSuccessURL, field.TypeString, value)
		_node.SuccessURL = &value
	}
	if value, ok := csc.mutation.FailureURL(); ok {
		_spec.SetField(checkoutsession.FieldFailureURL, field.TypeString, value)
		_node.FailureURL = &value
	}
	if value, ok := csc.mutation.CancelURL(); ok {
		_spec.SetField(checkoutsession.FieldCancelURL, field.TypeString, value)
		_node.CancelURL = &value
	}
	if value, ok := csc.mutation.ExpiresAt(); ok {
		_spec.SetField(checkoutsession.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := csc.mutation.CompletedAt(); ok {
		_spec.SetField(checkoutsession.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := csc.mutation.CancelledAt(); ok {
		_spec.SetField(checkoutsession.FieldCancelledAt, field.TypeTime, value)
		_node.CancelledAt = &value
	}
	if value, ok := csc.mutation.FailureReason(); ok {
		_spec.SetField(checkoutsession.FieldFailureReason, field.TypeString, value)
		_node.FailureReason = &value
	}
	if value, ok := csc.mutation.Metadata(); ok {
		_spec.SetField(checkoutsession.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	return _node, _spec
}

// CheckoutSessionCreateBulk is the builder for creating many CheckoutSession entities in bulk.
type CheckoutSessionCreateBulk struct {
	config
	err      error
	builders []*CheckoutSessionCreate
}

// Save creates the CheckoutSession entities in the database.
func (cscb *CheckoutSessionCreateBulk) Save(ctx context.Context) ([]*CheckoutSession, error) {
	if cscb.err != nil {
		return nil, cscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(cscb.builders))
	nodes := make([]*CheckoutSession, len(cscb.builders))
	mutators := make([]Mutator, len(cscb.builders))
	for i := range cscb.builders {
		func(i int, root context.Context) {
			builder := cscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CheckoutSessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, cscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, cscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, cscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (cscb *CheckoutSessionCreateBulk) SaveX(ctx context.Context) []*CheckoutSession {
	v, err := cscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cscb *CheckoutSessionCreateBulk) Exec(ctx context.Context) error {
	_, err := cscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cscb *CheckoutSessionCreateBulk) ExecX(ctx context.Context) {
	if err := cscb.Exec(ctx); err != nil {
		panic(err)
	}
}
