// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/checkoutsession"
	"github.com/flexprice/flexprice/ent/predicate"
	"github.com/flexprice/flexprice/internal/types"
)

// CheckoutSessionUpdate is the builder for updating CheckoutSession entities.
type CheckoutSessionUpdate struct {
	config
	hooks    []Hook
	mutation *CheckoutSessionMutation
}

// Where appends a list predicates to the CheckoutSessionUpdate builder.
func (csu *CheckoutSessionUpdate) Where(ps ...predicate.CheckoutSession) *CheckoutSessionUpdate {
	csu.mutation.Where(ps...)
	return csu
}

// SetStatus sets the "status" field.
func (csu *CheckoutSessionUpdate) SetStatus(s string) *CheckoutSessionUpdate {
	csu.mutation.SetStatus(s)
	return csu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (csu *CheckoutSessionUpdate) SetNillableStatus(s *string) *CheckoutSessionUpdate {
	if s != nil {
		csu.SetStatus(*s)
	}
	return csu
}

// SetUpdatedAt sets the "updated_at" field.
func (csu *CheckoutSessionUpdate) SetUpdatedAt(t time.Time) *CheckoutSessionUpdate {
	csu.mutation.SetUpdatedAt(t)
	return csu
}

// SetUpdatedBy sets the "updated_by" field.
func (csu *CheckoutSessionUpdate) SetUpdatedBy(s string) *CheckoutSessionUpdate {
	csu.mutation.SetUpdatedBy(s)
	return csu
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (csu *CheckoutSessionUpdate) SetNillableUpdatedBy(s *string) *CheckoutSessionUpdate {
	if s != nil {
		csu.SetUpdatedBy(*s)
	}
	return csu
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (csu *CheckoutSessionUpdate) ClearUpdatedBy() *CheckoutSessionUpdate {
	csu.mutation.ClearUpdatedBy()
	return csu
}

// SetCheckoutStatus sets the "checkout_status" field.
func (csu *CheckoutSessionUpdate) SetCheckoutStatus(ts types.CheckoutStatus) *CheckoutSessionUpdate {
	csu.mutation.SetCheckoutStatus(ts)
	return csu
}

// SetNillableCheckoutStatus sets the "checkout_status" field if the given value is not nil.
func (csu *CheckoutSessionUpdate) SetNillableCheckoutStatus(ts *types.CheckoutStatus) *CheckoutSessionUpdate {
	if ts != nil {
		csu.SetCheckoutStatus(*ts)
	}
	return csu
}

// SetCheckoutInvoiceID sets the "checkout_invoice_id" field.
func (csu *CheckoutSessionUpdate) SetCheckoutInvoiceID(s string) *CheckoutSessionUpdate {
	csu.mutation.SetCheckoutInvoiceID(s)
	return csu
}

// SetNillableCheckoutInvoiceID sets the "checkout_invoice_id" field if the given value is not nil.
func (csu *CheckoutSessionUpdate) SetNillableCheckoutInvoiceID(s *string) *CheckoutSessionUpdate {
	if s != nil {
		csu.SetCheckoutInvoiceID(*s)
	}
	return csu
}

// ClearCheckoutInvoiceID clears the value of the "checkout_invoice_id" field.
func (csu *CheckoutSessionUpdate) ClearCheckoutInvoiceID() *CheckoutSessionUpdate {
	csu.mutation.ClearCheckoutInvoiceID()
	return csu
}

// SetCheckoutPaymentID sets the "checkout_payment_id" field.
func (csu *CheckoutSessionUpdate) SetCheckoutPaymentID(s string) *CheckoutSessionUpdate {
	csu.mutation.SetCheckoutPaymentID(s)
	return csu
}

// SetNillableCheckoutPaymentID sets the "checkout_payment_id" field if the given value is not nil.
func (csu *CheckoutSessionUpdate) SetNillableCheckoutPaymentID(s *string) *CheckoutSessionUpdate {
	if s != nil {
		csu.SetCheckoutPaymentID(*s)
	}
	return csu
}

// ClearCheckoutPaymentID clears the value of the "checkout_payment_id" field.
func (csu *CheckoutSessionUpdate) ClearCheckoutPaymentID() *CheckoutSessionUpdate {
	csu.mutation.ClearCheckoutPaymentID()
	return csu
}

// SetConfiguration sets the "configuration" field.
func (csu *CheckoutSessionUpdate) SetConfiguration(tc types.CheckoutConfiguration) *CheckoutSessionUpdate {
	csu.mutation.SetConfiguration(tc)
	return csu
}

// SetNillableConfiguration sets the "configuration" field if the given value is not nil.
func (csu *CheckoutSessionUpdate) SetNillableConfiguration(tc *types.CheckoutConfiguration) *CheckoutSessionUpdate {
	if tc != nil {
		csu.SetConfiguration(*tc)
	}
	return csu
}

// SetPaymentProviderConfig sets the "payment_provider_config" field.
func (csu *CheckoutSessionUpdate) SetPaymentProviderConfig(tppc *types.CheckoutPaymentProviderConfig) *CheckoutSessionUpdate {
	csu.mutation.SetPaymentProviderConfig(tppc)
	return csu
}

// ClearPaymentProviderConfig clears the value of the "payment_provider_config" field.
func (csu *CheckoutSessionUpdate) ClearPaymentProviderConfig() *CheckoutSessionUpdate {
	csu.mutation.ClearPaymentProviderConfig()
	return csu
}

// SetResult sets the "result" field.
func (csu *CheckoutSessionUpdate) SetResult(tr *types.CheckoutResult) *CheckoutSessionUpdate {
	csu.mutation.SetResult(tr)
	return csu
}

// ClearResult clears the value of the "result" field.
func (csu *CheckoutSessionUpdate) ClearResult() *CheckoutSessionUpdate {
	csu.mutation.ClearResult()
	return csu
}

// SetProviderResult sets the "provider_result" field.
func (csu *CheckoutSessionUpdate) SetProviderResult(tpr *types.CheckoutProviderResult) *CheckoutSessionUpdate {
	csu.mutation.SetProviderResult(tpr)
	return csu
}

// ClearProviderResult clears the value of the "provider_result" field.
func (csu *CheckoutSessionUpdate) ClearProviderResult() *CheckoutSessionUpdate {
	csu.mutation.ClearProviderResult()
	return csu
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (csu *CheckoutSessionUpdate) SetIdempotencyKey(s string) *CheckoutSessionUpdate {
	csu.mutation.SetIdempotencyKey(s)
	return csu
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (csu *CheckoutSessionUpdate) SetNillableIdempotencyKey(s *string) *CheckoutSessionUpdate {
	if s != nil {
		csu.SetIdempotencyKey(*s)
	}
	return csu
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (csu *CheckoutSessionUpdate) ClearIdempotencyKey() *CheckoutSessionUpdate {
	csu.mutation.ClearIdempotencyKey()
	return csu
}

// SetSuccessURL sets the "success_url" field.
func (csu *CheckoutSessionUpdate) SetSuccessURL(s string) *CheckoutSessionUpdate {
	csu.mutation.SetSuccessURL(s)
	return csu
}

// SetNillableSuccessURL sets the "success_url" field if the given value is not nil.
func (csu *CheckoutSessionUpdate) SetNillableSuccessURL(s *string) *CheckoutSessionUpdate {
	if s != nil {
		csu.SetSuccessURL(*s)
	}
	return csu
}

// ClearSuccessURL clears the value of the "success_url" field.
func (csu *CheckoutSessionUpdate) ClearSuccessURL() *CheckoutSessionUpdate {
	csu.mutation.ClearSuccessURL()
	return csu
}

// SetFailureURL sets the "failure_url" field.
func (csu *CheckoutSessionUpdate) SetFailureURL(s string) *CheckoutSessionUpdate {
	csu.mutation.SetFailureURL(s)
	return csu
}

// SetNillableFailureURL sets the "failure_url" field if the given value is not nil.
func (csu *CheckoutSessionUpdate) SetNillableFailureURL(s *string) *CheckoutSessionUpdate {
	if s != nil {
		csu.SetFailureURL(*s)
	}
	return csu
}

// ClearFailureURL clears the value of the "failure_url" field.
func (csu *CheckoutSessionUpdate) ClearFailureURL() *CheckoutSessionUpdate {
	csu.mutation.ClearFailureURL()
	return csu
}

// SetCancelURL sets the "cancel_url" field.
func (csu *CheckoutSessionUpdate) SetCancelURL(s string) *CheckoutSessionUpdate {
	csu.mutation.SetCancelURL(s)
	return csu
}

// SetNillableCancelURL sets the "cancel_url" field if the given value is not nil.
func (csu *CheckoutSessionUpdate) SetNillableCancelURL(s *string) *CheckoutSessionUpdate {
	if s != nil {
		csu.SetCancelURL(*s)
	}
	return csu
}

// ClearCancelURL clears the value of the "cancel_url" field.
func (csu *CheckoutSessionUpdate) ClearCancelURL() *CheckoutSessionUpdate {
	csu.mutation.ClearCancelURL()
	return csu
}

// SetExpiresAt sets the "expires_at" field.
func (csu *CheckoutSessionUpdate) SetExpiresAt(t time.Time) *CheckoutSessionUpdate {
	csu.mutation.SetExpiresAt(t)
	return csu
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (csu *CheckoutSessionUpdate) SetNillableExpiresAt(t *time.Time) *CheckoutSessionUpdate {
	if t != nil {
		csu.SetExpiresAt(*t)
	}
	return csu
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (csu *CheckoutSessionUpdate) ClearExpiresAt() *CheckoutSessionUpdate {
	csu.mutation.ClearExpiresAt()
	return csu
}

// SetCompletedAt sets the "completed_at" field.
func (csu *CheckoutSessionUpdate) SetCompletedAt(t time.Time) *CheckoutSessionUpdate {
	csu.mutation.SetCompletedAt(t)
	return csu
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (csu *CheckoutSessionUpdate) SetNillableCompletedAt(t *time.Time) *CheckoutSessionUpdate {
	if t != nil {
		csu.SetCompletedAt(*t)
	}
	return csu
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (csu *CheckoutSessionUpdate) ClearCompletedAt() *CheckoutSessionUpdate {
	csu.mutation.ClearCompletedAt()
	return csu
}

// SetCancelledAt sets the "cancelled_at" field.
func (csu *CheckoutSessionUpdate) SetCancelledAt(t time.Time) *CheckoutSessionUpdate {
	csu.mutation.SetCancelledAt(t)
	return csu
}

// SetNillableCancelledAt sets the "cancelled_at" field if the given value is not nil.
func (csu *CheckoutSessionUpdate) SetNillableCancelledAt(t *time.Time) *CheckoutSessionUpdate {
	if t != nil {
		csu.SetCancelledAt(*t)
	}
	return csu
}

// ClearCancelledAt clears the value of the "cancelled_at" field.
func (csu *CheckoutSessionUpdate) ClearCancelledAt() *CheckoutSessionUpdate {
	csu.mutation.ClearCancelledAt()
	return csu
}

// SetFailureReason sets the "failure_reason" field.
func (csu *CheckoutSessionUpdate) SetFailureReason(s string) *CheckoutSessionUpdate {
	csu.mutation.SetFailureReason(s)
	return csu
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (csu *CheckoutSessionUpdate) SetNillableFailureReason(s *string) *CheckoutSessionUpdate {
	if s != nil {
		csu.SetFailureReason(*s)
	}
	return csu
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (csu *CheckoutSessionUpdate) ClearFailureReason() *CheckoutSessionUpdate {
	csu.mutation.ClearFailureReason()
	return csu
}

// SetMetadata sets the "metadata" field.
func (csu *CheckoutSessionUpdate) SetMetadata(m map[string]string) *CheckoutSessionUpdate {
	csu.mutation.SetMetadata(m)
	return csu
}

// ClearMetadata clears the value of the "metadata" field.
func (csu *CheckoutSessionUpdate) ClearMetadata() *CheckoutSessionUpdate {
	csu.mutation.ClearMetadata()
	return csu
}

// Mutation returns the CheckoutSessionMutation object of the builder.
func (csu *CheckoutSessionUpdate) Mutation() *CheckoutSessionMutation {
	return csu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (csu *CheckoutSessionUpdate) Save(ctx context.Context) (int, error) {
	csu.defaults()
	return withHooks(ctx, csu.sqlSave, csu.mutation, csu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (csu *CheckoutSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := csu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (csu *CheckoutSessionUpdate) Exec(ctx context.Context) error {
	_, err := csu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (csu *CheckoutSessionUpdate) ExecX(ctx context.Context) {
	if err := csu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (csu *CheckoutSessionUpdate) defaults() {
	if _, ok := csu.mutation.UpdatedAt(); !ok {
		v := checkoutsession.UpdateDefaultUpdatedAt()
		csu.mutation.SetUpdatedAt(v)
	}
}

func (csu *CheckoutSessionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(checkoutsession.Table, checkoutsession.Columns, sqlgraph.NewFieldSpec(checkoutsession.FieldID, field.TypeString))
	if ps := csu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := csu.mutation.Status(); ok {
		_spec.SetField(checkoutsession.FieldStatus, field.TypeString, value)
	}
	if value, ok := csu.mutation.UpdatedAt(); ok {
		_spec.SetField(checkoutsession.FieldUpdatedAt, field.TypeTime, value)
	}
	if csu.mutation.CreatedByCleared() {
		_spec.ClearField(checkoutsession.FieldCreatedBy, field.TypeString)
	}
	if value, ok := csu.mutation.UpdatedBy(); ok {
		_spec.SetField(checkoutsession.FieldUpdatedBy, field.TypeString, value)
	}
	if csu.mutation.UpdatedByCleared() {
		_spec.ClearField(checkoutsession.FieldUpdatedBy, field.TypeString)
	}
	if csu.mutation.EnvironmentIDCleared() {
		_spec.ClearField(checkoutsession.FieldEnvironmentID, field.TypeString)
	}
	if value, ok := csu.mutation.CheckoutStatus(); ok {
		_spec.SetField(checkoutsession.FieldCheckoutStatus, field.TypeString, value)
	}
	if value, ok := csu.mutation.CheckoutInvoiceID(); ok {
		_spec.SetField(checkoutsession.FieldCheckoutInvoiceID, field.TypeString, value)
	}
	if csu.mutation.CheckoutInvoiceIDCleared() {
		_spec.ClearField(checkoutsession.FieldCheckoutInvoiceID, field.TypeString)
	}
	if value, ok := csu.mutation.CheckoutPaymentID(); ok {
		_spec.SetField(checkoutsession.FieldCheckoutPaymentID, field.TypeString, value)
	}
	if csu.mutation.CheckoutPaymentIDCleared() {
		_spec.ClearField(checkoutsession.FieldCheckoutPaymentID, field.TypeString)
	}
	if value, ok := csu.mutation.Configuration(); ok {
		_spec.SetField(checkoutsession.FieldConfiguration, field.TypeJSON, value)
	}
	if value, ok := csu.mutation.PaymentProviderConfig(); ok {
		_spec.SetField(checkoutsession.FieldPaymentProviderConfig, field.TypeJSON, value)
	}
	if csu.mutation.PaymentProviderConfigCleared() {
		_spec.ClearField(checkoutsession.FieldPaymentProviderConfig, field.TypeJSON)
	}
	if value, ok := csu.mutation.Result(); ok {
		_spec.SetField(checkoutsession.FieldResult, field.TypeJSON, value)
	}
	if csu.mutation.ResultCleared() {
		_spec.ClearField(checkoutsession.FieldResult, field.TypeJSON)
	}
	if value, ok := csu.mutation.ProviderResult(); ok {
		_spec.SetField(checkoutsession.FieldProviderResult, field.TypeJSON, value)
	}
	if csu.mutation.ProviderResultCleared() {
		_spec.ClearField(checkoutsession.FieldProviderResult, field.TypeJSON)
	}
	if value, ok := csu.mutation.IdempotencyKey(); ok {
		_spec.SetField(checkoutsession.FieldIdempotencyKey, field.TypeString, value)
	}
	if csu.mutation.IdempotencyKeyCleared() {
		_spec.ClearField(checkoutsession.FieldIdempotencyKey, field.TypeString)
	}
	if value, ok := csu.mutation.SuccessURL(); ok {
		_spec.SetField(checkoutsession.FieldSuccessURL, field.TypeString, value)
	}
	if csu.mutation.SuccessURLCleared() {
		_spec.ClearField(checkoutsession.FieldSuccessURL, field.TypeString)
	}
	if value, ok := csu.mutation.FailureURL(); ok {
		_spec.SetField(checkoutsession.FieldFailureURL, field.TypeString, value)
	}
	if csu.mutation.FailureURLCleared() {
		_spec.ClearField(checkoutsession.FieldFailureURL, field.TypeString)
	}
	if value, ok := csu.mutation.CancelURL(); ok {
		_spec.SetField(checkoutsession.FieldCancelURL, field.TypeString, value)
	}
	if csu.mutation.CancelURLCleared() {
		_spec.ClearField(checkoutsession.FieldCancelURL, field.TypeString)
	}
	if value, ok := csu.mutation.ExpiresAt(); ok {
		_spec.SetField(checkoutsession.FieldExpiresAt, field.TypeTime, value)
	}
	if csu.mutation.ExpiresAtCleared() {
		_spec.ClearField(checkoutsession.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := csu.mutation.CompletedAt(); ok {
		_spec.SetField(checkoutsession.FieldCompletedAt, field.TypeTime, value)
	}
	if csu.mutation.CompletedAtCleared() {
		_spec.ClearField(checkoutsession.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := csu.mutation.CancelledAt(); ok {
		_spec.SetField(checkoutsession.FieldCancelledAt, field.TypeTime, value)
	}
	if csu.mutation.CancelledAtCleared() {
		_spec.ClearField(checkoutsession.FieldCancelledAt, field.TypeTime)
	}
	if value, ok := csu.mutation.FailureReason(); ok {
		_spec.SetField(checkoutsession.FieldFailureReason, field.TypeString, value)
	}
	if csu.mutation.FailureReasonCleared() {
		_spec.ClearField(checkoutsession.FieldFailureReason, field.TypeString)
	}
	if value, ok := csu.mutation.Metadata(); ok {
		_spec.SetField(checkoutsession.FieldMetadata, field.TypeJSON, value)
	}
	if csu.mutation.MetadataCleared() {
		_spec.ClearField(checkoutsession.FieldMetadata, field.TypeJSON)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, csu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{checkoutsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	csu.mutation.done = true
	return n, nil
}

// CheckoutSessionUpdateOne is the builder for updating a single CheckoutSession entity.
type CheckoutSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CheckoutSessionMutation
}

// SetStatus sets the "status" field.
func (csuo *CheckoutSessionUpdateOne) SetStatus(s string) *CheckoutSessionUpdateOne {
	csuo.mutation.SetStatus(s)
	return csuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (csuo *CheckoutSessionUpdateOne) SetNillableStatus(s *string) *CheckoutSessionUpdateOne {
	if s != nil {
		csuo.SetStatus(*s)
	}
	return csuo
}

// SetUpdatedAt sets the "updated_at" field.
func (csuo *CheckoutSessionUpdateOne) SetUpdatedAt(t time.Time) *CheckoutSessionUpdateOne {
	csuo.mutation.SetUpdatedAt(t)
	return csuo
}

// SetUpdatedBy sets the "updated_by" field.
func (csuo *CheckoutSessionUpdateOne) SetUpdatedBy(s string) *CheckoutSessionUpdateOne {
	csuo.mutation.SetUpdatedBy(s)
	return csuo
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (csuo *CheckoutSessionUpdateOne) SetNillableUpdatedBy(s *string) *CheckoutSessionUpdateOne {
	if s != nil {
		csuo.SetUpdatedBy(*s)
	}
	return csuo
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (csuo *CheckoutSessionUpdateOne) ClearUpdatedBy() *CheckoutSessionUpdateOne {
	csuo.mutation.ClearUpdatedBy()
	return csuo
}

// SetCheckoutStatus sets the "checkout_status" field.
func (csuo *CheckoutSessionUpdateOne) SetCheckoutStatus(ts types.CheckoutStatus) *CheckoutSessionUpdateOne {
	csuo.mutation.SetCheckoutStatus(ts)
	return csuo
}

// SetNillableCheckoutStatus sets the "checkout_status" field if the given value is not nil.
func (csuo *CheckoutSessionUpdateOne) SetNillableCheckoutStatus(ts *types.CheckoutStatus) *CheckoutSessionUpdateOne {
	if ts != nil {
		csuo.SetCheckoutStatus(*ts)
	}
	return csuo
}

// SetCheckoutInvoiceID sets the "checkout_invoice_id" field.
func (csuo *CheckoutSessionUpdateOne) SetCheckoutInvoiceID(s string) *CheckoutSessionUpdateOne {
	csuo.mutation.SetCheckoutInvoiceID(s)
	return csuo
}

// SetNillableCheckoutInvoiceID sets the "checkout_invoice_id" field if the given value is not nil.
func (csuo *CheckoutSessionUpdateOne) SetNillableCheckoutInvoiceID(s *string) *CheckoutSessionUpdateOne {
	if s != nil {
		csuo.SetCheckoutInvoiceID(*s)
	}
	return csuo
}

// ClearCheckoutInvoiceID clears the value of the "checkout_invoice_id" field.
func (csuo *CheckoutSessionUpdateOne) ClearCheckoutInvoiceID() *CheckoutSessionUpdateOne {
	csuo.mutation.ClearCheckoutInvoiceID()
	return csuo
}

// SetCheckoutPaymentID sets the "checkout_payment_id" field.
func (csuo *CheckoutSessionUpdateOne) SetCheckoutPaymentID(s string) *CheckoutSessionUpdateOne {
	csuo.mutation.SetCheckoutPaymentID(s)
	return csuo
}

// SetNillableCheckoutPaymentID sets the "checkout_payment_id" field if the given value is not nil.
func (csuo *CheckoutSessionUpdateOne) SetNillableCheckoutPaymentID(s *string) *CheckoutSessionUpdateOne {
	if s != nil {
		csuo.SetCheckoutPaymentID(*s)
	}
	return csuo
}

// ClearCheckoutPaymentID clears the value of the "checkout_payment_id" field.
func (csuo *CheckoutSessionUpdateOne) ClearCheckoutPaymentID() *CheckoutSessionUpdateOne {
	csuo.mutation.ClearCheckoutPaymentID()
	return csuo
}

// SetConfiguration sets the "configuration" field.
func (csuo *CheckoutSessionUpdateOne) SetConfiguration(tc types.CheckoutConfiguration) *CheckoutSessionUpdateOne {
	csuo.mutation.SetConfiguration(tc)
	return csuo
}

// SetNillableConfiguration sets the "configuration" field if the given value is not nil.
func (csuo *CheckoutSessionUpdateOne) SetNillableConfiguration(tc *types.CheckoutConfiguration) *CheckoutSessionUpdateOne {
	if tc != nil {
		csuo.SetConfiguration(*tc)
	}
	return csuo
}

// SetPaymentProviderConfig sets the "payment_provider_config" field.
func (csuo *CheckoutSessionUpdateOne) SetPaymentProviderConfig(tppc *types.CheckoutPaymentProviderConfig) *CheckoutSessionUpdateOne {
	csuo.mutation.SetPaymentProviderConfig(tppc)
	return csuo
}

// ClearPaymentProviderConfig clears the value of the "payment_provider_config" field.
func (csuo *CheckoutSessionUpdateOne) ClearPaymentProviderConfig() *CheckoutSessionUpdateOne {
	csuo.mutation.ClearPaymentProviderConfig()
	return csuo
}

// SetResult sets the "result" field.
func (csuo *CheckoutSessionUpdateOne) SetResult(tr *types.CheckoutResult) *CheckoutSessionUpdateOne {
	csuo.mutation.SetResult(tr)
	return csuo
}

// ClearResult clears the value of the "result" field.
func (csuo *CheckoutSessionUpdateOne) ClearResult() *CheckoutSessionUpdateOne {
	csuo.mutation.ClearResult()
	return csuo
}

// SetProviderResult sets the "provider_result" field.
func (csuo *CheckoutSessionUpdateOne) SetProviderResult(tpr *types.CheckoutProviderResult) *CheckoutSessionUpdateOne {
	csuo.mutation.SetProviderResult(tpr)
	return csuo
}

// ClearProviderResult clears the value of the "provider_result" field.
func (csuo *CheckoutSessionUpdateOne) ClearProviderResult() *CheckoutSessionUpdateOne {
	csuo.mutation.ClearProviderResult()
	return csuo
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (csuo *CheckoutSessionUpdateOne) SetIdempotencyKey(s string) *CheckoutSessionUpdateOne {
	csuo.mutation.SetIdempotencyKey(s)
	return csuo
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (csuo *CheckoutSessionUpdateOne) SetNillableIdempotencyKey(s *string) *CheckoutSessionUpdateOne {
	if s != nil {
		csuo.SetIdempotencyKey(*s)
	}
	return csuo
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (csuo *CheckoutSessionUpdateOne) ClearIdempotencyKey() *CheckoutSessionUpdateOne {
	csuo.mutation.ClearIdempotencyKey()
	return csuo
}

// SetSuccessURL sets the "success_url" field.
func (csuo *CheckoutSessionUpdateOne) SetSuccessURL(s string) *CheckoutSessionUpdateOne {
	csuo.mutation.SetSuccessURL(s)
	return csuo
}

// SetNillableSuccessURL sets the "success_url" field if the given value is not nil.
func (csuo *CheckoutSessionUpdateOne) SetNillableSuccessURL(s *string) *CheckoutSessionUpdateOne {
	if s != nil {
		csuo.SetSuccessURL(*s)
	}
	return csuo
}

// ClearSuccessURL clears the value of the "success_url" field.
func (csuo *CheckoutSessionUpdateOne) ClearSuccessURL() *CheckoutSessionUpdateOne {
	csuo.mutation.ClearSuccessURL()
	return csuo
}

// SetFailureURL sets the "failure_url" field.
func (csuo *CheckoutSessionUpdateOne) SetFailureURL(s string) *CheckoutSessionUpdateOne {
	csuo.mutation.SetFailureURL(s)
	return csuo
}

// SetNillableFailureURL sets the "failure_url" field if the given value is not nil.
func (csuo *CheckoutSessionUpdateOne) SetNillableFailureURL(s *string) *CheckoutSessionUpdateOne {
	if s != nil {
		csuo.SetFailureURL(*s)
	}
	return csuo
}

// ClearFailureURL clears the value of the "failure_url" field.
func (csuo *CheckoutSessionUpdateOne) ClearFailureURL() *CheckoutSessionUpdateOne {
	csuo.mutation.ClearFailureURL()
	return csuo
}

// SetCancelURL sets the "cancel_url" field.
func (csuo *CheckoutSessionUpdateOne) SetCancelURL(s string) *CheckoutSessionUpdateOne {
	csuo.mutation.SetCancelURL(s)
	return csuo
}

// SetNillableCancelURL sets the "cancel_url" field if the given value is not nil.
func (csuo *CheckoutSessionUpdateOne) SetNillableCancelURL(s *string) *CheckoutSessionUpdateOne {
	if s != nil {
		csuo.SetCancelURL(*s)
	}
	return csuo
}

// ClearCancelURL clears the value of the "cancel_url" field.
func (csuo *CheckoutSessionUpdateOne) ClearCancelURL() *CheckoutSessionUpdateOne {
	csuo.mutation.ClearCancelURL()
	return csuo
}

// SetExpiresAt sets the "expires_at" field.
func (csuo *CheckoutSessionUpdateOne) SetExpiresAt(t time.Time) *CheckoutSessionUpdateOne {
	csuo.mutation.SetExpiresAt(t)
	return csuo
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (csuo *CheckoutSessionUpdateOne) SetNillableExpiresAt(t *time.Time) *CheckoutSessionUpdateOne {
	if t != nil {
		csuo.SetExpiresAt(*t)
	}
	return csuo
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (csuo *CheckoutSessionUpdateOne) ClearExpiresAt() *CheckoutSessionUpdateOne {
	csuo.mutation.ClearExpiresAt()
	return csuo
}

// SetCompletedAt sets the "completed_at" field.
func (csuo *CheckoutSessionUpdateOne) SetCompletedAt(t time.Time) *CheckoutSessionUpdateOne {
	csuo.mutation.SetCompletedAt(t)
	return csuo
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (csuo *CheckoutSessionUpdateOne) SetNillableCompletedAt(t *time.Time) *CheckoutSessionUpdateOne {
	if t != nil {
		csuo.SetCompletedAt(*t)
	}
	return csuo
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (csuo *CheckoutSessionUpdateOne) ClearCompletedAt() *CheckoutSessionUpdateOne {
	csuo.mutation.ClearCompletedAt()
	return csuo
}

// SetCancelledAt sets the "cancelled_at" field.
func (csuo *CheckoutSessionUpdateOne) SetCancelledAt(t time.Time) *CheckoutSessionUpdateOne {
	csuo.mutation.SetCancelledAt(t)
	return csuo
}

// SetNillableCancelledAt sets the "cancelled_at" field if the given value is not nil.
func (csuo *CheckoutSessionUpdateOne) SetNillableCancelledAt(t *time.Time) *CheckoutSessionUpdateOne {
	if t != nil {
		csuo.SetCancelledAt(*t)
	}
	return csuo
}

// ClearCancelledAt clears the value of the "cancelled_at" field.
func (csuo *CheckoutSessionUpdateOne) ClearCancelledAt() *CheckoutSessionUpdateOne {
	csuo.mutation.ClearCancelledAt()
	return csuo
}

// SetFailureReason sets the "failure_reason" field.
func (csuo *CheckoutSessionUpdateOne) SetFailureReason(s string) *CheckoutSessionUpdateOne {
	csuo.mutation.SetFailureReason(s)
	return csuo
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (csuo *CheckoutSessionUpdateOne) SetNillableFailureReason(s *string) *CheckoutSessionUpdateOne {
	if s != nil {
		csuo.SetFailureReason(*s)
	}
	return csuo
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (csuo *CheckoutSessionUpdateOne) ClearFailureReason() *CheckoutSessionUpdateOne {
	csuo.mutation.ClearFailureReason()
	return csuo
}

// SetMetadata sets the "metadata" field.
func (csuo *CheckoutSessionUpdateOne) SetMetadata(m map[string]string) *CheckoutSessionUpdateOne {
	csuo.mutation.SetMetadata(m)
	return csuo
}

// ClearMetadata clears the value of the "metadata" field.
func (csuo *CheckoutSessionUpdateOne) ClearMetadata() *CheckoutSessionUpdateOne {
	csuo.mutation.ClearMetadata()
	return csuo
}

// Mutation returns the CheckoutSessionMutation object of the builder.
func (csuo *CheckoutSessionUpdateOne) Mutation() *CheckoutSessionMutation {
	return csuo.mutation
}

// Where appends a list predicates to the CheckoutSessionUpdate builder.
func (csuo *CheckoutSessionUpdateOne) Where(ps ...predicate.CheckoutSession) *CheckoutSessionUpdateOne {
	csuo.mutation.Where(ps...)
	return csuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (csuo *CheckoutSessionUpdateOne) Select(field string, fields ...string) *CheckoutSessionUpdateOne {
	csuo.fields = append([]string{field}, fields...)
	return csuo
}

// Save executes the query and returns the updated CheckoutSession entity.
func (csuo *CheckoutSessionUpdateOne) Save(ctx context.Context) (*CheckoutSession, error) {
	csuo.defaults()
	return withHooks(ctx, csuo.sqlSave, csuo.mutation, csuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (csuo *CheckoutSessionUpdateOne) SaveX(ctx context.Context) *CheckoutSession {
	node, err := csuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (csuo *CheckoutSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := csuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (csuo *CheckoutSessionUpdateOne) ExecX(ctx context.Context) {
	if err := csuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (csuo *CheckoutSessionUpdateOne) defaults() {
	if _, ok := csuo.mutation.UpdatedAt(); !ok {
		v := checkoutsession.UpdateDefaultUpdatedAt()
		csuo.mutation.SetUpdatedAt(v)
	}
}

func (csuo *CheckoutSessionUpdateOne) sqlSave(ctx context.Context) (_node *CheckoutSession, err error) {
	_spec := sqlgraph.NewUpdateSpec(checkoutsession.Table, checkoutsession.Columns, sqlgraph.NewFieldSpec(checkoutsession.FieldID, field.TypeString))
	id, ok := csuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CheckoutSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := csuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, checkoutsession.FieldID)
		for _, f := range fields {
			if !checkoutsession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != checkoutsession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := csuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := csuo.mutation.Status(); ok {
		_spec.SetField(checkoutsession.FieldStatus, field.TypeString, value)
	}
	if value, ok := csuo.mutation.UpdatedAt(); ok {
		_spec.SetField(checkoutsession.FieldUpdatedAt, field.TypeTime, value)
	}
	if csuo.mutation.CreatedByCleared() {
		_spec.ClearField(checkoutsession.FieldCreatedBy, field.TypeString)
	}
	if value, ok := csuo.mutation.UpdatedBy(); ok {
		_spec.SetField(checkoutsession.FieldUpdatedBy, field.TypeString, value)
	}
	if csuo.mutation.UpdatedByCleared() {
		_spec.ClearField(checkoutsession.FieldUpdatedBy, field.TypeString)
	}
	if csuo.mutation.EnvironmentIDCleared() {
		_spec.ClearField(checkoutsession.FieldEnvironmentID, field.TypeString)
	}
	if value, ok := csuo.mutation.CheckoutStatus(); ok {
		_spec.SetField(checkoutsession.FieldCheckoutStatus, field.TypeString, value)
	}
	if value, ok := csuo.mutation.CheckoutInvoiceID(); ok {
		_spec.SetField(checkoutsession.FieldCheckoutInvoiceID, field.TypeString, value)
	}
	if csuo.mutation.CheckoutInvoiceIDCleared() {
		_spec.ClearField(checkoutsession.FieldCheckoutInvoiceID, field.TypeString)
	}
	if value, ok := csuo.mutation.CheckoutPaymentID(); ok {
		_spec.SetField(checkoutsession.FieldCheckoutPaymentID, field.TypeString, value)
	}
	if csuo.mutation.CheckoutPaymentIDCleared() {
		_spec.ClearField(checkoutsession.FieldCheckoutPaymentID, field.TypeString)
	}
	if value, ok := csuo.mutation.Configuration(); ok {
		_spec.SetField(checkoutsession.FieldConfiguration, field.TypeJSON, value)
	}
	if value, ok := csuo.mutation.PaymentProviderConfig(); ok {
		_spec.SetField(checkoutsession.FieldPaymentProviderConfig, field.TypeJSON, value)
	}
	if csuo.mutation.PaymentProviderConfigCleared() {
		_spec.ClearField(checkoutsession.FieldPaymentProviderConfig, field.TypeJSON)
	}
	if value, ok := csuo.mutation.Result(); ok {
		_spec.SetField(checkoutsession.FieldResult, field.TypeJSON, value)
	}
	if csuo.mutation.ResultCleared() {
		_spec.ClearField(checkoutsession.FieldResult, field.TypeJSON)
	}
	if value, ok := csuo.mutation.ProviderResult(); ok {
		_spec.SetField(checkoutsession.FieldProviderResult, field.TypeJSON, value)
	}
	if csuo.mutation.ProviderResultCleared() {
		_spec.ClearField(checkoutsession.FieldProviderResult, field.TypeJSON)
	}
	if value, ok := csuo.mutation.IdempotencyKey(); ok {
		_spec.SetField(checkoutsession.FieldIdempotencyKey, field.TypeString, value)
	}
	if csuo.mutation.IdempotencyKeyCleared() {
		_spec.ClearField(checkoutsession.FieldIdempotencyKey, field.TypeString)
	}
	if value, ok := csuo.mutation.SuccessURL(); ok {
		_spec.SetField(checkoutsession.FieldSuccessURL, field.TypeString, value)
	}
	if csuo.mutation.SuccessURLCleared() {
		_spec.ClearField(checkoutsession.FieldSuccessURL, field.TypeString)
	}
	if value, ok := csuo.mutation.FailureURL(); ok {
		_spec.SetField(checkoutsession.FieldFailureURL, field.TypeString, value)
	}
	if csuo.mutation.FailureURLCleared() {
		_spec.ClearField(checkoutsession.FieldFailureURL, field.TypeString)
	}
	if value, ok := csuo.mutation.CancelURL(); ok {
		_spec.SetField(checkoutsession.FieldCancelURL, field.TypeString, value)
	}
	if csuo.mutation.CancelURLCleared() {
		_spec.ClearField(checkoutsession.FieldCancelURL, field.TypeString)
	}
	if value, ok := csuo.mutation.ExpiresAt(); ok {
		_spec.SetField(checkoutsession.FieldExpiresAt, field.TypeTime, value)
	}
	if csuo.mutation.ExpiresAtCleared() {
		_spec.ClearField(checkoutsession.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := csuo.mutation.CompletedAt(); ok {
		_spec.SetField(checkoutsession.FieldCompletedAt, field.TypeTime, value)
	}
	if csuo.mutation.CompletedAtCleared() {
		_spec.ClearField(checkoutsession.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := csuo.mutation.CancelledAt(); ok {
		_spec.SetField(checkoutsession.FieldCancelledAt, field.TypeTime, value)
	}
	if csuo.mutation.CancelledAtCleared() {
		_spec.ClearField(checkoutsession.FieldCancelledAt, field.TypeTime)
	}
	if value, ok := csuo.mutation.FailureReason(); ok {
		_spec.SetField(checkoutsession.FieldFailureReason, field.TypeString, value)
	}
	if csuo.mutation.FailureReasonCleared() {
		_spec.ClearField(checkoutsession.FieldFailureReason, field.TypeString)
	}
	if value, ok := csuo.mutation.Metadata(); ok {
		_spec.SetField(checkoutsession.FieldMetadata, field.TypeJSON, value)
	}
	if csuo.mutation.MetadataCleared() {
		_spec.ClearField(checkoutsession.FieldMetadata, field.TypeJSON)
	}
	_node = &CheckoutSession{config: csuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, csuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{checkoutsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	csuo.mutation.done = true
	return _node, nil
}
