// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/entitlement"
	"github.com/flexprice/flexprice/ent/predicate"
	"github.com/flexprice/flexprice/internal/types"
)

// EntitlementUpdate is the builder for updating Entitlement entities.
type EntitlementUpdate struct {
	config
	hooks    []Hook
	mutation *EntitlementMutation
}

// Where appends a list predicates to the EntitlementUpdate builder.
func (_u *EntitlementUpdate) Where(ps ...predicate.Entitlement) *EntitlementUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *EntitlementUpdate) SetStatus(v string) *EntitlementUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EntitlementUpdate) SetNillableStatus(v *string) *EntitlementUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EntitlementUpdate) SetUpdatedAt(v time.Time) *EntitlementUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *EntitlementUpdate) SetUpdatedBy(v string) *EntitlementUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *EntitlementUpdate) SetNillableUpdatedBy(v *string) *EntitlementUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *EntitlementUpdate) ClearUpdatedBy() *EntitlementUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetEntityType sets the "entity_type" field.
func (_u *EntitlementUpdate) SetEntityType(v types.EntitlementEntityType) *EntitlementUpdate {
	_u.mutation.SetEntityType(v)
	return _u
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (_u *EntitlementUpdate) SetNillableEntityType(v *types.EntitlementEntityType) *EntitlementUpdate {
	if v != nil {
		_u.SetEntityType(*v)
	}
	return _u
}

// ClearEntityType clears the value of the "entity_type" field.
func (_u *EntitlementUpdate) ClearEntityType() *EntitlementUpdate {
	_u.mutation.ClearEntityType()
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *EntitlementUpdate) SetEntityID(v string) *EntitlementUpdate {
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *EntitlementUpdate) SetNillableEntityID(v *string) *EntitlementUpdate {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// ClearEntityID clears the value of the "entity_id" field.
func (_u *EntitlementUpdate) ClearEntityID() *EntitlementUpdate {
	_u.mutation.ClearEntityID()
	return _u
}

// SetFeatureID sets the "feature_id" field.
func (_u *EntitlementUpdate) SetFeatureID(v string) *EntitlementUpdate {
	_u.mutation.SetFeatureID(v)
	return _u
}

// SetNillableFeatureID sets the "feature_id" field if the given value is not nil.
func (_u *EntitlementUpdate) SetNillableFeatureID(v *string) *EntitlementUpdate {
	if v != nil {
		_u.SetFeatureID(*v)
	}
	return _u
}

// SetFeatureType sets the "feature_type" field.
func (_u *EntitlementUpdate) SetFeatureType(v types.FeatureType) *EntitlementUpdate {
	_u.mutation.SetFeatureType(v)
	return _u
}

// SetNillableFeatureType sets the "feature_type" field if the given value is not nil.
func (_u *EntitlementUpdate) SetNillableFeatureType(v *types.FeatureType) *EntitlementUpdate {
	if v != nil {
		_u.SetFeatureType(*v)
	}
	return _u
}

// SetIsEnabled sets the "is_enabled" field.
func (_u *EntitlementUpdate) SetIsEnabled(v bool) *EntitlementUpdate {
	_u.mutation.SetIsEnabled(v)
	return _u
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_u *EntitlementUpdate) SetNillableIsEnabled(v *bool) *EntitlementUpdate {
	if v != nil {
		_u.SetIsEnabled(*v)
	}
	return _u
}

// SetUsageLimit sets the "usage_limit" field.
func (_u *EntitlementUpdate) SetUsageLimit(v int64) *EntitlementUpdate {
	_u.mutation.ResetUsageLimit()
	_u.mutation.SetUsageLimit(v)
	return _u
}

// SetNillableUsageLimit sets the "usage_limit" field if the given value is not nil.
func (_u *EntitlementUpdate) SetNillableUsageLimit(v *int64) *EntitlementUpdate {
	if v != nil {
		_u.SetUsageLimit(*v)
	}
	return _u
}

// AddUsageLimit adds value to the "usage_limit" field.
func (_u *EntitlementUpdate) AddUsageLimit(v int64) *EntitlementUpdate {
	_u.mutation.AddUsageLimit(v)
	return _u
}

// ClearUsageLimit clears the value of the "usage_limit" field.
func (_u *EntitlementUpdate) ClearUsageLimit() *EntitlementUpdate {
	_u.mutation.ClearUsageLimit()
	return _u
}

// SetUsageResetPeriod sets the "usage_reset_period" field.
func (_u *EntitlementUpdate) SetUsageResetPeriod(v types.EntitlementUsageResetPeriod) *EntitlementUpdate {
	_u.mutation.SetUsageResetPeriod(v)
	return _u
}

// SetNillableUsageResetPeriod sets the "usage_reset_period" field if the given value is not nil.
func (_u *EntitlementUpdate) SetNillableUsageResetPeriod(v *types.EntitlementUsageResetPeriod) *EntitlementUpdate {
	if v != nil {
		_u.SetUsageResetPeriod(*v)
	}
	return _u
}

// ClearUsageResetPeriod clears the value of the "usage_reset_period" field.
func (_u *EntitlementUpdate) ClearUsageResetPeriod() *EntitlementUpdate {
	_u.mutation.ClearUsageResetPeriod()
	return _u
}

// SetIsSoftLimit sets the "is_soft_limit" field.
func (_u *EntitlementUpdate) SetIsSoftLimit(v bool) *EntitlementUpdate {
	_u.mutation.SetIsSoftLimit(v)
	return _u
}

// SetNillableIsSoftLimit sets the "is_soft_limit" field if the given value is not nil.
func (_u *EntitlementUpdate) SetNillableIsSoftLimit(v *bool) *EntitlementUpdate {
	if v != nil {
		_u.SetIsSoftLimit(*v)
	}
	return _u
}

// SetStaticValue sets the "static_value" field.
func (_u *EntitlementUpdate) SetStaticValue(v string) *EntitlementUpdate {
	_u.mutation.SetStaticValue(v)
	return _u
}

// SetNillableStaticValue sets the "static_value" field if the given value is not nil.
func (_u *EntitlementUpdate) SetNillableStaticValue(v *string) *EntitlementUpdate {
	if v != nil {
		_u.SetStaticValue(*v)
	}
	return _u
}

// ClearStaticValue clears the value of the "static_value" field.
func (_u *EntitlementUpdate) ClearStaticValue() *EntitlementUpdate {
	_u.mutation.ClearStaticValue()
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *EntitlementUpdate) SetDisplayOrder(v int) *EntitlementUpdate {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *EntitlementUpdate) SetNillableDisplayOrder(v *int) *EntitlementUpdate {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *EntitlementUpdate) AddDisplayOrder(v int) *EntitlementUpdate {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// SetParentEntitlementID sets the "parent_entitlement_id" field.
func (_u *EntitlementUpdate) SetParentEntitlementID(v string) *EntitlementUpdate {
	_u.mutation.SetParentEntitlementID(v)
	return _u
}

// SetNillableParentEntitlementID sets the "parent_entitlement_id" field if the given value is not nil.
func (_u *EntitlementUpdate) SetNillableParentEntitlementID(v *string) *EntitlementUpdate {
	if v != nil {
		_u.SetParentEntitlementID(*v)
	}
	return _u
}

// ClearParentEntitlementID clears the value of the "parent_entitlement_id" field.
func (_u *EntitlementUpdate) ClearParentEntitlementID() *EntitlementUpdate {
	_u.mutation.ClearParentEntitlementID()
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *EntitlementUpdate) SetStartDate(v time.Time) *EntitlementUpdate {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *EntitlementUpdate) SetNillableStartDate(v *time.Time) *EntitlementUpdate {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// ClearStartDate clears the value of the "start_date" field.
func (_u *EntitlementUpdate) ClearStartDate() *EntitlementUpdate {
	_u.mutation.ClearStartDate()
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *EntitlementUpdate) SetEndDate(v time.Time) *EntitlementUpdate {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *EntitlementUpdate) SetNillableEndDate(v *time.Time) *EntitlementUpdate {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// ClearEndDate clears the value of the "end_date" field.
func (_u *EntitlementUpdate) ClearEndDate() *EntitlementUpdate {
	_u.mutation.ClearEndDate()
	return _u
}

// Mutation returns the EntitlementMutation object of the builder.
func (_u *EntitlementUpdate) Mutation() *EntitlementMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EntitlementUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EntitlementUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EntitlementUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EntitlementUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EntitlementUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := entitlement.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EntitlementUpdate) check() error {
	if v, ok := _u.mutation.EntityType(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "entity_type", err: fmt.Errorf(`ent: validator failed for field "Entitlement.entity_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FeatureID(); ok {
		if err := entitlement.FeatureIDValidator(v); err != nil {
			return &ValidationError{Name: "feature_id", err: fmt.Errorf(`ent: validator failed for field "Entitlement.feature_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FeatureType(); ok {
		if err := entitlement.FeatureTypeValidator(string(v)); err != nil {
			return &ValidationError{Name: "feature_type", err: fmt.Errorf(`ent: validator failed for field "Entitlement.feature_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UsageResetPeriod(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "usage_reset_period", err: fmt.Errorf(`ent: validator failed for field "Entitlement.usage_reset_period": %w`, err)}
		}
	}
	return nil
}

func (_u *EntitlementUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(entitlement.Table, entitlement.Columns, sqlgraph.NewFieldSpec(entitlement.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(entitlement.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(entitlement.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(entitlement.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(entitlement.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(entitlement.FieldUpdatedBy, field.TypeString)
	}
	if _u.mutation.EnvironmentIDCleared() {
		_spec.ClearField(entitlement.FieldEnvironmentID, field.TypeString)
	}
	if value, ok := _u.mutation.EntityType(); ok {
		_spec.SetField(entitlement.FieldEntityType, field.TypeString, value)
	}
	if _u.mutation.EntityTypeCleared() {
		_spec.ClearField(entitlement.FieldEntityType, field.TypeString)
	}
	if value, ok := _u.mutation.EntityID(); ok {
		_spec.SetField(entitlement.FieldEntityID, field.TypeString, value)
	}
	if _u.mutation.EntityIDCleared() {
		_spec.ClearField(entitlement.FieldEntityID, field.TypeString)
	}
	if value, ok := _u.mutation.FeatureID(); ok {
		_spec.SetField(entitlement.FieldFeatureID, field.TypeString, value)
	}
	if value, ok := _u.mutation.FeatureType(); ok {
		_spec.SetField(entitlement.FieldFeatureType, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsEnabled(); ok {
		_spec.SetField(entitlement.FieldIsEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UsageLimit(); ok {
		_spec.SetField(entitlement.FieldUsageLimit, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageLimit(); ok {
		_spec.AddField(entitlement.FieldUsageLimit, field.TypeInt64, value)
	}
	if _u.mutation.UsageLimitCleared() {
		_spec.ClearField(entitlement.FieldUsageLimit, field.TypeInt64)
	}
	if value, ok := _u.mutation.UsageResetPeriod(); ok {
		_spec.SetField(entitlement.FieldUsageResetPeriod, field.TypeString, value)
	}
	if _u.mutation.UsageResetPeriodCleared() {
		_spec.ClearField(entitlement.FieldUsageResetPeriod, field.TypeString)
	}
	if value, ok := _u.mutation.IsSoftLimit(); ok {
		_spec.SetField(entitlement.FieldIsSoftLimit, field.TypeBool, value)
	}
	if value, ok := _u.mutation.StaticValue(); ok {
		_spec.SetField(entitlement.FieldStaticValue, field.TypeString, value)
	}
	if _u.mutation.StaticValueCleared() {
		_spec.ClearField(entitlement.FieldStaticValue, field.TypeString)
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(entitlement.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(entitlement.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ParentEntitlementID(); ok {
		_spec.SetField(entitlement.FieldParentEntitlementID, field.TypeString, value)
	}
	if _u.mutation.ParentEntitlementIDCleared() {
		_spec.ClearField(entitlement.FieldParentEntitlementID, field.TypeString)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(entitlement.FieldStartDate, field.TypeTime, value)
	}
	if _u.mutation.StartDateCleared() {
		_spec.ClearField(entitlement.FieldStartDate, field.TypeTime)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(entitlement.FieldEndDate, field.TypeTime, value)
	}
	if _u.mutation.EndDateCleared() {
		_spec.ClearField(entitlement.FieldEndDate, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entitlement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EntitlementUpdateOne is the builder for updating a single Entitlement entity.
type EntitlementUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EntitlementMutation
}

// SetStatus sets the "status" field.
func (_u *EntitlementUpdateOne) SetStatus(v string) *EntitlementUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EntitlementUpdateOne) SetNillableStatus(v *string) *EntitlementUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EntitlementUpdateOne) SetUpdatedAt(v time.Time) *EntitlementUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *EntitlementUpdateOne) SetUpdatedBy(v string) *EntitlementUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *EntitlementUpdateOne) SetNillableUpdatedBy(v *string) *EntitlementUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *EntitlementUpdateOne) ClearUpdatedBy() *EntitlementUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetEntityType sets the "entity_type" field.
func (_u *EntitlementUpdateOne) SetEntityType(v types.EntitlementEntityType) *EntitlementUpdateOne {
	_u.mutation.SetEntityType(v)
	return _u
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (_u *EntitlementUpdateOne) SetNillableEntityType(v *types.EntitlementEntityType) *EntitlementUpdateOne {
	if v != nil {
		_u.SetEntityType(*v)
	}
	return _u
}

// ClearEntityType clears the value of the "entity_type" field.
func (_u *EntitlementUpdateOne) ClearEntityType() *EntitlementUpdateOne {
	_u.mutation.ClearEntityType()
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *EntitlementUpdateOne) SetEntityID(v string) *EntitlementUpdateOne {
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *EntitlementUpdateOne) SetNillableEntityID(v *string) *EntitlementUpdateOne {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// ClearEntityID clears the value of the "entity_id" field.
func (_u *EntitlementUpdateOne) ClearEntityID() *EntitlementUpdateOne {
	_u.mutation.ClearEntityID()
	return _u
}

// SetFeatureID sets the "feature_id" field.
func (_u *EntitlementUpdateOne) SetFeatureID(v string) *EntitlementUpdateOne {
	_u.mutation.SetFeatureID(v)
	return _u
}

// SetNillableFeatureID sets the "feature_id" field if the given value is not nil.
func (_u *EntitlementUpdateOne) SetNillableFeatureID(v *string) *EntitlementUpdateOne {
	if v != nil {
		_u.SetFeatureID(*v)
	}
	return _u
}

// SetFeatureType sets the "feature_type" field.
func (_u *EntitlementUpdateOne) SetFeatureType(v types.FeatureType) *EntitlementUpdateOne {
	_u.mutation.SetFeatureType(v)
	return _u
}

// SetNillableFeatureType sets the "feature_type" field if the given value is not nil.
func (_u *EntitlementUpdateOne) SetNillableFeatureType(v *types.FeatureType) *EntitlementUpdateOne {
	if v != nil {
		_u.SetFeatureType(*v)
	}
	return _u
}

// SetIsEnabled sets the "is_enabled" field.
func (_u *EntitlementUpdateOne) SetIsEnabled(v bool) *EntitlementUpdateOne {
	_u.mutation.SetIsEnabled(v)
	return _u
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_u *EntitlementUpdateOne) SetNillableIsEnabled(v *bool) *EntitlementUpdateOne {
	if v != nil {
		_u.SetIsEnabled(*v)
	}
	return _u
}

// SetUsageLimit sets the "usage_limit" field.
func (_u *EntitlementUpdateOne) SetUsageLimit(v int64) *EntitlementUpdateOne {
	_u.mutation.ResetUsageLimit()
	_u.mutation.SetUsageLimit(v)
	return _u
}

// SetNillableUsageLimit sets the "usage_limit" field if the given value is not nil.
func (_u *EntitlementUpdateOne) SetNillableUsageLimit(v *int64) *EntitlementUpdateOne {
	if v != nil {
		_u.SetUsageLimit(*v)
	}
	return _u
}

// AddUsageLimit adds value to the "usage_limit" field.
func (_u *EntitlementUpdateOne) AddUsageLimit(v int64) *EntitlementUpdateOne {
	_u.mutation.AddUsageLimit(v)
	return _u
}

// ClearUsageLimit clears the value of the "usage_limit" field.
func (_u *EntitlementUpdateOne) ClearUsageLimit() *EntitlementUpdateOne {
	_u.mutation.ClearUsageLimit()
	return _u
}

// SetUsageResetPeriod sets the "usage_reset_period" field.
func (_u *EntitlementUpdateOne) SetUsageResetPeriod(v types.EntitlementUsageResetPeriod) *EntitlementUpdateOne {
	_u.mutation.SetUsageResetPeriod(v)
	return _u
}

// SetNillableUsageResetPeriod sets the "usage_reset_period" field if the given value is not nil.
func (_u *EntitlementUpdateOne) SetNillableUsageResetPeriod(v *types.EntitlementUsageResetPeriod) *EntitlementUpdateOne {
	if v != nil {
		_u.SetUsageResetPeriod(*v)
	}
	return _u
}

// ClearUsageResetPeriod clears the value of the "usage_reset_period" field.
func (_u *EntitlementUpdateOne) ClearUsageResetPeriod() *EntitlementUpdateOne {
	_u.mutation.ClearUsageResetPeriod()
	return _u
}

// SetIsSoftLimit sets the "is_soft_limit" field.
func (_u *EntitlementUpdateOne) SetIsSoftLimit(v bool) *EntitlementUpdateOne {
	_u.mutation.SetIsSoftLimit(v)
	return _u
}

// SetNillableIsSoftLimit sets the "is_soft_limit" field if the given value is not nil.
func (_u *EntitlementUpdateOne) SetNillableIsSoftLimit(v *bool) *EntitlementUpdateOne {
	if v != nil {
		_u.SetIsSoftLimit(*v)
	}
	return _u
}

// SetStaticValue sets the "static_value" field.
func (_u *EntitlementUpdateOne) SetStaticValue(v string) *EntitlementUpdateOne {
	_u.mutation.SetStaticValue(v)
	return _u
}

// SetNillableStaticValue sets the "static_value" field if the given value is not nil.
func (_u *EntitlementUpdateOne) SetNillableStaticValue(v *string) *EntitlementUpdateOne {
	if v != nil {
		_u.SetStaticValue(*v)
	}
	return _u
}

// ClearStaticValue clears the value of the "static_value" field.
func (_u *EntitlementUpdateOne) ClearStaticValue() *EntitlementUpdateOne {
	_u.mutation.ClearStaticValue()
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *EntitlementUpdateOne) SetDisplayOrder(v int) *EntitlementUpdateOne {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *EntitlementUpdateOne) SetNillableDisplayOrder(v *int) *EntitlementUpdateOne {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *EntitlementUpdateOne) AddDisplayOrder(v int) *EntitlementUpdateOne {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// SetParentEntitlementID sets the "parent_entitlement_id" field.
func (_u *EntitlementUpdateOne) SetParentEntitlementID(v string) *EntitlementUpdateOne {
	_u.mutation.SetParentEntitlementID(v)
	return _u
}

// SetNillableParentEntitlementID sets the "parent_entitlement_id" field if the given value is not nil.
func (_u *EntitlementUpdateOne) SetNillableParentEntitlementID(v *string) *EntitlementUpdateOne {
	if v != nil {
		_u.SetParentEntitlementID(*v)
	}
	return _u
}

// ClearParentEntitlementID clears the value of the "parent_entitlement_id" field.
func (_u *EntitlementUpdateOne) ClearParentEntitlementID() *EntitlementUpdateOne {
	_u.mutation.ClearParentEntitlementID()
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *EntitlementUpdateOne) SetStartDate(v time.Time) *EntitlementUpdateOne {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *EntitlementUpdateOne) SetNillableStartDate(v *time.Time) *EntitlementUpdateOne {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// ClearStartDate clears the value of the "start_date" field.
func (_u *EntitlementUpdateOne) ClearStartDate() *EntitlementUpdateOne {
	_u.mutation.ClearStartDate()
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *EntitlementUpdateOne) SetEndDate(v time.Time) *EntitlementUpdateOne {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *EntitlementUpdateOne) SetNillableEndDate(v *time.Time) *EntitlementUpdateOne {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// ClearEndDate clears the value of the "end_date" field.
func (_u *EntitlementUpdateOne) ClearEndDate() *EntitlementUpdateOne {
	_u.mutation.ClearEndDate()
	return _u
}

// Mutation returns the EntitlementMutation object of the builder.
func (_u *EntitlementUpdateOne) Mutation() *EntitlementMutation {
	return _u.mutation
}

// Where appends a list predicates to the EntitlementUpdate builder.
func (_u *EntitlementUpdateOne) Where(ps ...predicate.Entitlement) *EntitlementUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EntitlementUpdateOne) Select(field string, fields ...string) *EntitlementUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Entitlement entity.
func (_u *EntitlementUpdateOne) Save(ctx context.Context) (*Entitlement, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EntitlementUpdateOne) SaveX(ctx context.Context) *Entitlement {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EntitlementUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EntitlementUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EntitlementUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := entitlement.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EntitlementUpdateOne) check() error {
	if v, ok := _u.mutation.EntityType(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "entity_type", err: fmt.Errorf(`ent: validator failed for field "Entitlement.entity_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FeatureID(); ok {
		if err := entitlement.FeatureIDValidator(v); err != nil {
			return &ValidationError{Name: "feature_id", err: fmt.Errorf(`ent: validator failed for field "Entitlement.feature_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FeatureType(); ok {
		if err := entitlement.FeatureTypeValidator(string(v)); err != nil {
			return &ValidationError{Name: "feature_type", err: fmt.Errorf(`ent: validator failed for field "Entitlement.feature_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UsageResetPeriod(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "usage_reset_period", err: fmt.Errorf(`ent: validator failed for field "Entitlement.usage_reset_period": %w`, err)}
		}
	}
	return nil
}

func (_u *EntitlementUpdateOne) sqlSave(ctx context.Context) (_node *Entitlement, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(entitlement.Table, entitlement.Columns, sqlgraph.NewFieldSpec(entitlement.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Entitlement.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entitlement.FieldID)
		for _, f := range fields {
			if !entitlement.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != entitlement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(entitlement.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(entitlement.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(entitlement.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(entitlement.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(entitlement.FieldUpdatedBy, field.TypeString)
	}
	if _u.mutation.EnvironmentIDCleared() {
		_spec.ClearField(entitlement.FieldEnvironmentID, field.TypeString)
	}
	if value, ok := _u.mutation.EntityType(); ok {
		_spec.SetField(entitlement.FieldEntityType, field.TypeString, value)
	}
	if _u.mutation.EntityTypeCleared() {
		_spec.ClearField(entitlement.FieldEntityType, field.TypeString)
	}
	if value, ok := _u.mutation.EntityID(); ok {
		_spec.SetField(entitlement.FieldEntityID, field.TypeString, value)
	}
	if _u.mutation.EntityIDCleared() {
		_spec.ClearField(entitlement.FieldEntityID, field.TypeString)
	}
	if value, ok := _u.mutation.FeatureID(); ok {
		_spec.SetField(entitlement.FieldFeatureID, field.TypeString, value)
	}
	if value, ok := _u.mutation.FeatureType(); ok {
		_spec.SetField(entitlement.FieldFeatureType, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsEnabled(); ok {
		_spec.SetField(entitlement.FieldIsEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UsageLimit(); ok {
		_spec.SetField(entitlement.FieldUsageLimit, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageLimit(); ok {
		_spec.AddField(entitlement.FieldUsageLimit, field.TypeInt64, value)
	}
	if _u.mutation.UsageLimitCleared() {
		_spec.ClearField(entitlement.FieldUsageLimit, field.TypeInt64)
	}
	if value, ok := _u.mutation.UsageResetPeriod(); ok {
		_spec.SetField(entitlement.FieldUsageResetPeriod, field.TypeString, value)
	}
	if _u.mutation.UsageResetPeriodCleared() {
		_spec.ClearField(entitlement.FieldUsageResetPeriod, field.TypeString)
	}
	if value, ok := _u.mutation.IsSoftLimit(); ok {
		_spec.SetField(entitlement.FieldIsSoftLimit, field.TypeBool, value)
	}
	if value, ok := _u.mutation.StaticValue(); ok {
		_spec.SetField(entitlement.FieldStaticValue, field.TypeString, value)
	}
	if _u.mutation.StaticValueCleared() {
		_spec.ClearField(entitlement.FieldStaticValue, field.TypeString)
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(entitlement.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(entitlement.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ParentEntitlementID(); ok {
		_spec.SetField(entitlement.FieldParentEntitlementID, field.TypeString, value)
	}
	if _u.mutation.ParentEntitlementIDCleared() {
		_spec.ClearField(entitlement.FieldParentEntitlementID, field.TypeString)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(entitlement.FieldStartDate, field.TypeTime, value)
	}
	if _u.mutation.StartDateCleared() {
		_spec.ClearField(entitlement.FieldStartDate, field.TypeTime)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(entitlement.FieldEndDate, field.TypeTime, value)
	}
	if _u.mutation.EndDateCleared() {
		_spec.ClearField(entitlement.FieldEndDate, field.TypeTime)
	}
	_node = &Entitlement{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entitlement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
