// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/flexprice/flexprice/ent/usagerecord"
	"github.com/shopspring/decimal"
)

// UsageRecord is the model entity for the UsageRecord schema.
type UsageRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID string `json:"tenant_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy string `json:"updated_by,omitempty"`
	// EnvironmentID holds the value of the "environment_id" field.
	EnvironmentID string `json:"environment_id,omitempty"`
	// CustomerID holds the value of the "customer_id" field.
	CustomerID string `json:"customer_id,omitempty"`
	// CustomerExternalID holds the value of the "customer_external_id" field.
	CustomerExternalID string `json:"customer_external_id,omitempty"`
	// SubscriptionID holds the value of the "subscription_id" field.
	SubscriptionID string `json:"subscription_id,omitempty"`
	// PlanID holds the value of the "plan_id" field.
	PlanID string `json:"plan_id,omitempty"`
	// Quantity holds the value of the "quantity" field.
	Quantity decimal.Decimal `json:"quantity,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount decimal.Decimal `json:"amount,omitempty"`
	// PeriodStart holds the value of the "period_start" field.
	PeriodStart time.Time `json:"period_start,omitempty"`
	// PeriodEnd holds the value of the "period_end" field.
	PeriodEnd time.Time `json:"period_end,omitempty"`
	// Syncs holds the value of the "syncs" field.
	Syncs map[string]interface{} `json:"syncs,omitempty"`
	// AllProvidersSynced holds the value of the "all_providers_synced" field.
	AllProvidersSynced bool `json:"all_providers_synced,omitempty"`
	selectValues       sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UsageRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usagerecord.FieldSyncs:
			values[i] = new([]byte)
		case usagerecord.FieldQuantity, usagerecord.FieldAmount:
			values[i] = new(decimal.Decimal)
		case usagerecord.FieldAllProvidersSynced:
			values[i] = new(sql.NullBool)
		case usagerecord.FieldID, usagerecord.FieldTenantID, usagerecord.FieldStatus, usagerecord.FieldCreatedBy, usagerecord.FieldUpdatedBy, usagerecord.FieldEnvironmentID, usagerecord.FieldCustomerID, usagerecord.FieldCustomerExternalID, usagerecord.FieldSubscriptionID, usagerecord.FieldPlanID:
			values[i] = new(sql.NullString)
		case usagerecord.FieldCreatedAt, usagerecord.FieldUpdatedAt, usagerecord.FieldPeriodStart, usagerecord.FieldPeriodEnd:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UsageRecord fields.
func (ur *UsageRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usagerecord.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				ur.ID = value.String
			}
		case usagerecord.FieldTenantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				ur.TenantID = value.String
			}
		case usagerecord.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				ur.Status = value.String
			}
		case usagerecord.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ur.CreatedAt = value.Time
			}
		case usagerecord.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ur.UpdatedAt = value.Time
			}
		case usagerecord.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				ur.CreatedBy = value.String
			}
		case usagerecord.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				ur.UpdatedBy = value.String
			}
		case usagerecord.FieldEnvironmentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field environment_id", values[i])
			} else if value.Valid {
				ur.EnvironmentID = value.String
			}
		case usagerecord.FieldCustomerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field customer_id", values[i])
			} else if value.Valid {
				ur.CustomerID = value.String
			}
		case usagerecord.FieldCustomerExternalID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field customer_external_id", values[i])
			} else if value.Valid {
				ur.CustomerExternalID = value.String
			}
		case usagerecord.FieldSubscriptionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_id", values[i])
			} else if value.Valid {
				ur.SubscriptionID = value.String
			}
		case usagerecord.FieldPlanID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field plan_id", values[i])
			} else if value.Valid {
				ur.PlanID = value.String
			}
		case usagerecord.FieldQuantity:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field quantity", values[i])
			} else if value != nil {
				ur.Quantity = *value
			}
		case usagerecord.FieldAmount:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value != nil {
				ur.Amount = *value
			}
		case usagerecord.FieldPeriodStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field period_start", values[i])
			} else if value.Valid {
				ur.PeriodStart = value.Time
			}
		case usagerecord.FieldPeriodEnd:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field period_end", values[i])
			} else if value.Valid {
				ur.PeriodEnd = value.Time
			}
		case usagerecord.FieldSyncs:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field syncs", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &ur.Syncs); err != nil {
					return fmt.Errorf("unmarshal field syncs: %w", err)
				}
			}
		case usagerecord.FieldAllProvidersSynced:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field all_providers_synced", values[i])
			} else if value.Valid {
				ur.AllProvidersSynced = value.Bool
			}
		default:
			ur.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UsageRecord.
// This includes values selected through modifiers, order, etc.
func (ur *UsageRecord) Value(name string) (ent.Value, error) {
	return ur.selectValues.Get(name)
}

// Update returns a builder for updating this UsageRecord.
// Note that you need to call UsageRecord.Unwrap() before calling this method if this UsageRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (ur *UsageRecord) Update() *UsageRecordUpdateOne {
	return NewUsageRecordClient(ur.config).UpdateOne(ur)
}

// Unwrap unwraps the UsageRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ur *UsageRecord) Unwrap() *UsageRecord {
	_tx, ok := ur.config.driver.(*txDriver)
	if !ok {
		panic("ent: UsageRecord is not a transactional entity")
	}
	ur.config.driver = _tx.drv
	return ur
}

// String implements the fmt.Stringer.
func (ur *UsageRecord) String() string {
	var builder strings.Builder
	builder.WriteString("UsageRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ur.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(ur.TenantID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(ur.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(ur.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(ur.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(ur.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(ur.UpdatedBy)
	builder.WriteString(", ")
	builder.WriteString("environment_id=")
	builder.WriteString(ur.EnvironmentID)
	builder.WriteString(", ")
	builder.WriteString("customer_id=")
	builder.WriteString(ur.CustomerID)
	builder.WriteString(", ")
	builder.WriteString("customer_external_id=")
	builder.WriteString(ur.CustomerExternalID)
	builder.WriteString(", ")
	builder.WriteString("subscription_id=")
	builder.WriteString(ur.SubscriptionID)
	builder.WriteString(", ")
	builder.WriteString("plan_id=")
	builder.WriteString(ur.PlanID)
	builder.WriteString(", ")
	builder.WriteString("quantity=")
	builder.WriteString(fmt.Sprintf("%v", ur.Quantity))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", ur.Amount))
	builder.WriteString(", ")
	builder.WriteString("period_start=")
	builder.WriteString(ur.PeriodStart.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("period_end=")
	builder.WriteString(ur.PeriodEnd.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("syncs=")
	builder.WriteString(fmt.Sprintf("%v", ur.Syncs))
	builder.WriteString(", ")
	builder.WriteString("all_providers_synced=")
	builder.WriteString(fmt.Sprintf("%v", ur.AllProvidersSynced))
	builder.WriteByte(')')
	return builder.String()
}

// UsageRecords is a parsable slice of UsageRecord.
type UsageRecords []*UsageRecord
