// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/predicate"
	"github.com/flexprice/flexprice/ent/usagerecord"
)

// UsageRecordQuery is the builder for querying UsageRecord entities.
type UsageRecordQuery struct {
	config
	ctx        *QueryContext
	order      []usagerecord.OrderOption
	inters     []Interceptor
	predicates []predicate.UsageRecord
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UsageRecordQuery builder.
func (urq *UsageRecordQuery) Where(ps ...predicate.UsageRecord) *UsageRecordQuery {
	urq.predicates = append(urq.predicates, ps...)
	return urq
}

// Limit the number of records to be returned by this query.
func (urq *UsageRecordQuery) Limit(limit int) *UsageRecordQuery {
	urq.ctx.Limit = &limit
	return urq
}

// Offset to start from.
func (urq *UsageRecordQuery) Offset(offset int) *UsageRecordQuery {
	urq.ctx.Offset = &offset
	return urq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (urq *UsageRecordQuery) Unique(unique bool) *UsageRecordQuery {
	urq.ctx.Unique = &unique
	return urq
}

// Order specifies how the records should be ordered.
func (urq *UsageRecordQuery) Order(o ...usagerecord.OrderOption) *UsageRecordQuery {
	urq.order = append(urq.order, o...)
	return urq
}

// First returns the first UsageRecord entity from the query.
// Returns a *NotFoundError when no UsageRecord was found.
func (urq *UsageRecordQuery) First(ctx context.Context) (*UsageRecord, error) {
	nodes, err := urq.Limit(1).All(setContextOp(ctx, urq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{usagerecord.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (urq *UsageRecordQuery) FirstX(ctx context.Context) *UsageRecord {
	node, err := urq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UsageRecord ID from the query.
// Returns a *NotFoundError when no UsageRecord ID was found.
func (urq *UsageRecordQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = urq.Limit(1).IDs(setContextOp(ctx, urq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{usagerecord.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (urq *UsageRecordQuery) FirstIDX(ctx context.Context) string {
	id, err := urq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UsageRecord entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UsageRecord entity is found.
// Returns a *NotFoundError when no UsageRecord entities are found.
func (urq *UsageRecordQuery) Only(ctx context.Context) (*UsageRecord, error) {
	nodes, err := urq.Limit(2).All(setContextOp(ctx, urq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{usagerecord.Label}
	default:
		return nil, &NotSingularError{usagerecord.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (urq *UsageRecordQuery) OnlyX(ctx context.Context) *UsageRecord {
	node, err := urq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UsageRecord ID in the query.
// Returns a *NotSingularError when more than one UsageRecord ID is found.
// Returns a *NotFoundError when no entities are found.
func (urq *UsageRecordQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = urq.Limit(2).IDs(setContextOp(ctx, urq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{usagerecord.Label}
	default:
		err = &NotSingularError{usagerecord.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (urq *UsageRecordQuery) OnlyIDX(ctx context.Context) string {
	id, err := urq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UsageRecords.
func (urq *UsageRecordQuery) All(ctx context.Context) ([]*UsageRecord, error) {
	ctx = setContextOp(ctx, urq.ctx, ent.OpQueryAll)
	if err := urq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UsageRecord, *UsageRecordQuery]()
	return withInterceptors[[]*UsageRecord](ctx, urq, qr, urq.inters)
}

// AllX is like All, but panics if an error occurs.
func (urq *UsageRecordQuery) AllX(ctx context.Context) []*UsageRecord {
	nodes, err := urq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UsageRecord IDs.
func (urq *UsageRecordQuery) IDs(ctx context.Context) (ids []string, err error) {
	if urq.ctx.Unique == nil && urq.path != nil {
		urq.Unique(true)
	}
	ctx = setContextOp(ctx, urq.ctx, ent.OpQueryIDs)
	if err = urq.Select(usagerecord.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (urq *UsageRecordQuery) IDsX(ctx context.Context) []string {
	ids, err := urq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (urq *UsageRecordQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, urq.ctx, ent.OpQueryCount)
	if err := urq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, urq, querierCount[*UsageRecordQuery](), urq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (urq *UsageRecordQuery) CountX(ctx context.Context) int {
	count, err := urq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (urq *UsageRecordQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, urq.ctx, ent.OpQueryExist)
	switch _, err := urq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (urq *UsageRecordQuery) ExistX(ctx context.Context) bool {
	exist, err := urq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UsageRecordQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (urq *UsageRecordQuery) Clone() *UsageRecordQuery {
	if urq == nil {
		return nil
	}
	return &UsageRecordQuery{
		config:     urq.config,
		ctx:        urq.ctx.Clone(),
		order:      append([]usagerecord.OrderOption{}, urq.order...),
		inters:     append([]Interceptor{}, urq.inters...),
		predicates: append([]predicate.UsageRecord{}, urq.predicates...),
		// clone intermediate query.
		sql:  urq.sql.Clone(),
		path: urq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UsageRecord.Query().
//		GroupBy(usagerecord.FieldTenantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (urq *UsageRecordQuery) GroupBy(field string, fields ...string) *UsageRecordGroupBy {
	urq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UsageRecordGroupBy{build: urq}
	grbuild.flds = &urq.ctx.Fields
	grbuild.label = usagerecord.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//	}
//
//	client.UsageRecord.Query().
//		Select(usagerecord.FieldTenantID).
//		Scan(ctx, &v)
func (urq *UsageRecordQuery) Select(fields ...string) *UsageRecordSelect {
	urq.ctx.Fields = append(urq.ctx.Fields, fields...)
	sbuild := &UsageRecordSelect{UsageRecordQuery: urq}
	sbuild.label = usagerecord.Label
	sbuild.flds, sbuild.scan = &urq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UsageRecordSelect configured with the given aggregations.
func (urq *UsageRecordQuery) Aggregate(fns ...AggregateFunc) *UsageRecordSelect {
	return urq.Select().Aggregate(fns...)
}

func (urq *UsageRecordQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range urq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, urq); err != nil {
				return err
			}
		}
	}
	for _, f := range urq.ctx.Fields {
		if !usagerecord.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if urq.path != nil {
		prev, err := urq.path(ctx)
		if err != nil {
			return err
		}
		urq.sql = prev
	}
	return nil
}

func (urq *UsageRecordQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UsageRecord, error) {
	var (
		nodes = []*UsageRecord{}
		_spec = urq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UsageRecord).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UsageRecord{config: urq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, urq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (urq *UsageRecordQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := urq.querySpec()
	_spec.Node.Columns = urq.ctx.Fields
	if len(urq.ctx.Fields) > 0 {
		_spec.Unique = urq.ctx.Unique != nil && *urq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, urq.driver, _spec)
}

func (urq *UsageRecordQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(usagerecord.Table, usagerecord.Columns, sqlgraph.NewFieldSpec(usagerecord.FieldID, field.TypeString))
	_spec.From = urq.sql
	if unique := urq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if urq.path != nil {
		_spec.Unique = true
	}
	if fields := urq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usagerecord.FieldID)
		for i := range fields {
			if fields[i] != usagerecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := urq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := urq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := urq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := urq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (urq *UsageRecordQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(urq.driver.Dialect())
	t1 := builder.Table(usagerecord.Table)
	columns := urq.ctx.Fields
	if len(columns) == 0 {
		columns = usagerecord.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if urq.sql != nil {
		selector = urq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if urq.ctx.Unique != nil && *urq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range urq.predicates {
		p(selector)
	}
	for _, p := range urq.order {
		p(selector)
	}
	if offset := urq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := urq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UsageRecordGroupBy is the group-by builder for UsageRecord entities.
type UsageRecordGroupBy struct {
	selector
	build *UsageRecordQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (urgb *UsageRecordGroupBy) Aggregate(fns ...AggregateFunc) *UsageRecordGroupBy {
	urgb.fns = append(urgb.fns, fns...)
	return urgb
}

// Scan applies the selector query and scans the result into the given value.
func (urgb *UsageRecordGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, urgb.build.ctx, ent.OpQueryGroupBy)
	if err := urgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UsageRecordQuery, *UsageRecordGroupBy](ctx, urgb.build, urgb, urgb.build.inters, v)
}

func (urgb *UsageRecordGroupBy) sqlScan(ctx context.Context, root *UsageRecordQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(urgb.fns))
	for _, fn := range urgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*urgb.flds)+len(urgb.fns))
		for _, f := range *urgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*urgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := urgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UsageRecordSelect is the builder for selecting fields of UsageRecord entities.
type UsageRecordSelect struct {
	*UsageRecordQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (urs *UsageRecordSelect) Aggregate(fns ...AggregateFunc) *UsageRecordSelect {
	urs.fns = append(urs.fns, fns...)
	return urs
}

// Scan applies the selector query and scans the result into the given value.
func (urs *UsageRecordSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, urs.ctx, ent.OpQuerySelect)
	if err := urs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UsageRecordQuery, *UsageRecordSelect](ctx, urs.UsageRecordQuery, urs, urs.inters, v)
}

func (urs *UsageRecordSelect) sqlScan(ctx context.Context, root *UsageRecordQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(urs.fns))
	for _, fn := range urs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*urs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := urs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
