// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/usagerecord"
	"github.com/shopspring/decimal"
)

// UsageRecordCreate is the builder for creating a UsageRecord entity.
type UsageRecordCreate struct {
	config
	mutation *UsageRecordMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (urc *UsageRecordCreate) SetTenantID(s string) *UsageRecordCreate {
	urc.mutation.SetTenantID(s)
	return urc
}

// SetStatus sets the "status" field.
func (urc *UsageRecordCreate) SetStatus(s string) *UsageRecordCreate {
	urc.mutation.SetStatus(s)
	return urc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (urc *UsageRecordCreate) SetNillableStatus(s *string) *UsageRecordCreate {
	if s != nil {
		urc.SetStatus(*s)
	}
	return urc
}

// SetCreatedAt sets the "created_at" field.
func (urc *UsageRecordCreate) SetCreatedAt(t time.Time) *UsageRecordCreate {
	urc.mutation.SetCreatedAt(t)
	return urc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (urc *UsageRecordCreate) SetNillableCreatedAt(t *time.Time) *UsageRecordCreate {
	if t != nil {
		urc.SetCreatedAt(*t)
	}
	return urc
}

// SetUpdatedAt sets the "updated_at" field.
func (urc *UsageRecordCreate) SetUpdatedAt(t time.Time) *UsageRecordCreate {
	urc.mutation.SetUpdatedAt(t)
	return urc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (urc *UsageRecordCreate) SetNillableUpdatedAt(t *time.Time) *UsageRecordCreate {
	if t != nil {
		urc.SetUpdatedAt(*t)
	}
	return urc
}

// SetCreatedBy sets the "created_by" field.
func (urc *UsageRecordCreate) SetCreatedBy(s string) *UsageRecordCreate {
	urc.mutation.SetCreatedBy(s)
	return urc
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (urc *UsageRecordCreate) SetNillableCreatedBy(s *string) *UsageRecordCreate {
	if s != nil {
		urc.SetCreatedBy(*s)
	}
	return urc
}

// SetUpdatedBy sets the "updated_by" field.
func (urc *UsageRecordCreate) SetUpdatedBy(s string) *UsageRecordCreate {
	urc.mutation.SetUpdatedBy(s)
	return urc
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (urc *UsageRecordCreate) SetNillableUpdatedBy(s *string) *UsageRecordCreate {
	if s != nil {
		urc.SetUpdatedBy(*s)
	}
	return urc
}

// SetEnvironmentID sets the "environment_id" field.
func (urc *UsageRecordCreate) SetEnvironmentID(s string) *UsageRecordCreate {
	urc.mutation.SetEnvironmentID(s)
	return urc
}

// SetNillableEnvironmentID sets the "environment_id" field if the given value is not nil.
func (urc *UsageRecordCreate) SetNillableEnvironmentID(s *string) *UsageRecordCreate {
	if s != nil {
		urc.SetEnvironmentID(*s)
	}
	return urc
}

// SetCustomerID sets the "customer_id" field.
func (urc *UsageRecordCreate) SetCustomerID(s string) *UsageRecordCreate {
	urc.mutation.SetCustomerID(s)
	return urc
}

// SetCustomerExternalID sets the "customer_external_id" field.
func (urc *UsageRecordCreate) SetCustomerExternalID(s string) *UsageRecordCreate {
	urc.mutation.SetCustomerExternalID(s)
	return urc
}

// SetNillableCustomerExternalID sets the "customer_external_id" field if the given value is not nil.
func (urc *UsageRecordCreate) SetNillableCustomerExternalID(s *string) *UsageRecordCreate {
	if s != nil {
		urc.SetCustomerExternalID(*s)
	}
	return urc
}

// SetSubscriptionID sets the "subscription_id" field.
func (urc *UsageRecordCreate) SetSubscriptionID(s string) *UsageRecordCreate {
	urc.mutation.SetSubscriptionID(s)
	return urc
}

// SetPlanID sets the "plan_id" field.
func (urc *UsageRecordCreate) SetPlanID(s string) *UsageRecordCreate {
	urc.mutation.SetPlanID(s)
	return urc
}

// SetQuantity sets the "quantity" field.
func (urc *UsageRecordCreate) SetQuantity(d decimal.Decimal) *UsageRecordCreate {
	urc.mutation.SetQuantity(d)
	return urc
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (urc *UsageRecordCreate) SetNillableQuantity(d *decimal.Decimal) *UsageRecordCreate {
	if d != nil {
		urc.SetQuantity(*d)
	}
	return urc
}

// SetAmount sets the "amount" field.
func (urc *UsageRecordCreate) SetAmount(d decimal.Decimal) *UsageRecordCreate {
	urc.mutation.SetAmount(d)
	return urc
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (urc *UsageRecordCreate) SetNillableAmount(d *decimal.Decimal) *UsageRecordCreate {
	if d != nil {
		urc.SetAmount(*d)
	}
	return urc
}

// SetCurrency sets the "currency" field.
func (urc *UsageRecordCreate) SetCurrency(s string) *UsageRecordCreate {
	urc.mutation.SetCurrency(s)
	return urc
}

// SetPeriodStart sets the "period_start" field.
func (urc *UsageRecordCreate) SetPeriodStart(t time.Time) *UsageRecordCreate {
	urc.mutation.SetPeriodStart(t)
	return urc
}

// SetPeriodEnd sets the "period_end" field.
func (urc *UsageRecordCreate) SetPeriodEnd(t time.Time) *UsageRecordCreate {
	urc.mutation.SetPeriodEnd(t)
	return urc
}

// SetSyncs sets the "syncs" field.
func (urc *UsageRecordCreate) SetSyncs(m map[string]interface{}) *UsageRecordCreate {
	urc.mutation.SetSyncs(m)
	return urc
}

// SetAllProvidersSynced sets the "all_providers_synced" field.
func (urc *UsageRecordCreate) SetAllProvidersSynced(b bool) *UsageRecordCreate {
	urc.mutation.SetAllProvidersSynced(b)
	return urc
}

// SetNillableAllProvidersSynced sets the "all_providers_synced" field if the given value is not nil.
func (urc *UsageRecordCreate) SetNillableAllProvidersSynced(b *bool) *UsageRecordCreate {
	if b != nil {
		urc.SetAllProvidersSynced(*b)
	}
	return urc
}

// SetID sets the "id" field.
func (urc *UsageRecordCreate) SetID(s string) *UsageRecordCreate {
	urc.mutation.SetID(s)
	return urc
}

// Mutation returns the UsageRecordMutation object of the builder.
func (urc *UsageRecordCreate) Mutation() *UsageRecordMutation {
	return urc.mutation
}

// Save creates the UsageRecord in the database.
func (urc *UsageRecordCreate) Save(ctx context.Context) (*UsageRecord, error) {
	urc.defaults()
	return withHooks(ctx, urc.sqlSave, urc.mutation, urc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (urc *UsageRecordCreate) SaveX(ctx context.Context) *UsageRecord {
	v, err := urc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (urc *UsageRecordCreate) Exec(ctx context.Context) error {
	_, err := urc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (urc *UsageRecordCreate) ExecX(ctx context.Context) {
	if err := urc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (urc *UsageRecordCreate) defaults() {
	if _, ok := urc.mutation.Status(); !ok {
		v := usagerecord.DefaultStatus
		urc.mutation.SetStatus(v)
	}
	if _, ok := urc.mutation.CreatedAt(); !ok {
		v := usagerecord.DefaultCreatedAt()
		urc.mutation.SetCreatedAt(v)
	}
	if _, ok := urc.mutation.UpdatedAt(); !ok {
		v := usagerecord.DefaultUpdatedAt()
		urc.mutation.SetUpdatedAt(v)
	}
	if _, ok := urc.mutation.EnvironmentID(); !ok {
		v := usagerecord.DefaultEnvironmentID
		urc.mutation.SetEnvironmentID(v)
	}
	if _, ok := urc.mutation.Quantity(); !ok {
		v := usagerecord.DefaultQuantity
		urc.mutation.SetQuantity(v)
	}
	if _, ok := urc.mutation.Amount(); !ok {
		v := usagerecord.DefaultAmount
		urc.mutation.SetAmount(v)
	}
	if _, ok := urc.mutation.AllProvidersSynced(); !ok {
		v := usagerecord.DefaultAllProvidersSynced
		urc.mutation.SetAllProvidersSynced(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (urc *UsageRecordCreate) check() error {
	if _, ok := urc.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "UsageRecord.tenant_id"`)}
	}
	if v, ok := urc.mutation.TenantID(); ok {
		if err := usagerecord.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "UsageRecord.tenant_id": %w`, err)}
		}
	}
	if _, ok := urc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "UsageRecord.status"`)}
	}
	if _, ok := urc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UsageRecord.created_at"`)}
	}
	if _, ok := urc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UsageRecord.updated_at"`)}
	}
	if _, ok := urc.mutation.CustomerID(); !ok {
		return &ValidationError{Name: "customer_id", err: errors.New(`ent: missing required field "UsageRecord.customer_id"`)}
	}
	if v, ok := urc.mutation.CustomerID(); ok {
		if err := usagerecord.CustomerIDValidator(v); err != nil {
			return &ValidationError{Name: "customer_id", err: fmt.Errorf(`ent: validator failed for field "UsageRecord.customer_id": %w`, err)}
		}
	}
	if _, ok := urc.mutation.SubscriptionID(); !ok {
		return &ValidationError{Name: "subscription_id", err: errors.New(`ent: missing required field "UsageRecord.subscription_id"`)}
	}
	if v, ok := urc.mutation.SubscriptionID(); ok {
		if err := usagerecord.SubscriptionIDValidator(v); err != nil {
			return &ValidationError{Name: "subscription_id", err: fmt.Errorf(`ent: validator failed for field "UsageRecord.subscription_id": %w`, err)}
		}
	}
	if _, ok := urc.mutation.PlanID(); !ok {
		return &ValidationError{Name: "plan_id", err: errors.New(`ent: missing required field "UsageRecord.plan_id"`)}
	}
	if v, ok := urc.mutation.PlanID(); ok {
		if err := usagerecord.PlanIDValidator(v); err != nil {
			return &ValidationError{Name: "plan_id", err: fmt.Errorf(`ent: validator failed for field "UsageRecord.plan_id": %w`, err)}
		}
	}
	if _, ok := urc.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "UsageRecord.quantity"`)}
	}
	if _, ok := urc.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "UsageRecord.amount"`)}
	}
	if _, ok := urc.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "UsageRecord.currency"`)}
	}
	if v, ok := urc.mutation.Currency(); ok {
		if err := usagerecord.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "UsageRecord.currency": %w`, err)}
		}
	}
	if _, ok := urc.mutation.PeriodStart(); !ok {
		return &ValidationError{Name: "period_start", err: errors.New(`ent: missing required field "UsageRecord.period_start"`)}
	}
	if _, ok := urc.mutation.PeriodEnd(); !ok {
		return &ValidationError{Name: "period_end", err: errors.New(`ent: missing required field "UsageRecord.period_end"`)}
	}
	if _, ok := urc.mutation.AllProvidersSynced(); !ok {
		return &ValidationError{Name: "all_providers_synced", err: errors.New(`ent: missing required field "UsageRecord.all_providers_synced"`)}
	}
	return nil
}

func (urc *UsageRecordCreate) sqlSave(ctx context.Context) (*UsageRecord, error) {
	if err := urc.check(); err != nil {
		return nil, err
	}
	_node, _spec := urc.createSpec()
	if err := sqlgraph.CreateNode(ctx, urc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected UsageRecord.ID type: %T", _spec.ID.Value)
		}
	}
	urc.mutation.id = &_node.ID
	urc.mutation.done = true
	return _node, nil
}

func (urc *UsageRecordCreate) createSpec() (*UsageRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &UsageRecord{config: urc.config}
		_spec = sqlgraph.NewCreateSpec(usagerecord.Table, sqlgraph.NewFieldSpec(usagerecord.FieldID, field.TypeString))
	)
	if id, ok := urc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := urc.mutation.TenantID(); ok {
		_spec.SetField(usagerecord.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := urc.mutation.Status(); ok {
		_spec.SetField(usagerecord.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := urc.mutation.CreatedAt(); ok {
		_spec.SetField(usagerecord.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := urc.mutation.UpdatedAt(); ok {
		_spec.SetField(usagerecord.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := urc.mutation.CreatedBy(); ok {
		_spec.SetField(usagerecord.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := urc.mutation.UpdatedBy(); ok {
		_spec.SetField(usagerecord.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := urc.mutation.EnvironmentID(); ok {
		_spec.SetField(usagerecord.FieldEnvironmentID, field.TypeString, value)
		_node.EnvironmentID = value
	}
	if value, ok := urc.mutation.CustomerID(); ok {
		_spec.SetField(usagerecord.FieldCustomerID, field.TypeString, value)
		_node.CustomerID = value
	}
	if value, ok := urc.mutation.CustomerExternalID(); ok {
		_spec.SetField(usagerecord.FieldCustomerExternalID, field.TypeString, value)
		_node.CustomerExternalID = value
	}
	if value, ok := urc.mutation.SubscriptionID(); ok {
		_spec.SetField(usagerecord.FieldSubscriptionID, field.TypeString, value)
		_node.SubscriptionID = value
	}
	if value, ok := urc.mutation.PlanID(); ok {
		_spec.SetField(usagerecord.FieldPlanID, field.TypeString, value)
		_node.PlanID = value
	}
	if value, ok := urc.mutation.Quantity(); ok {
		_spec.SetField(usagerecord.FieldQuantity, field.TypeOther, value)
		_node.Quantity = value
	}
	if value, ok := urc.mutation.Amount(); ok {
		_spec.SetField(usagerecord.FieldAmount, field.TypeOther, value)
		_node.Amount = value
	}
	if value, ok := urc.mutation.Currency(); ok {
		_spec.SetField(usagerecord.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := urc.mutation.PeriodStart(); ok {
		_spec.SetField(usagerecord.FieldPeriodStart, field.TypeTime, value)
		_node.PeriodStart = value
	}
	if value, ok := urc.mutation.PeriodEnd(); ok {
		_spec.SetField(usagerecord.FieldPeriodEnd, field.TypeTime, value)
		_node.PeriodEnd = value
	}
	if value, ok := urc.mutation.Syncs(); ok {
		_spec.SetField(usagerecord.FieldSyncs, field.TypeJSON, value)
		_node.Syncs = value
	}
	if value, ok := urc.mutation.AllProvidersSynced(); ok {
		_spec.SetField(usagerecord.FieldAllProvidersSynced, field.TypeBool, value)
		_node.AllProvidersSynced = value
	}
	return _node, _spec
}

// UsageRecordCreateBulk is the builder for creating many UsageRecord entities in bulk.
type UsageRecordCreateBulk struct {
	config
	err      error
	builders []*UsageRecordCreate
}

// Save creates the UsageRecord entities in the database.
func (urcb *UsageRecordCreateBulk) Save(ctx context.Context) ([]*UsageRecord, error) {
	if urcb.err != nil {
		return nil, urcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(urcb.builders))
	nodes := make([]*UsageRecord, len(urcb.builders))
	mutators := make([]Mutator, len(urcb.builders))
	for i := range urcb.builders {
		func(i int, root context.Context) {
			builder := urcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UsageRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, urcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, urcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, urcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (urcb *UsageRecordCreateBulk) SaveX(ctx context.Context) []*UsageRecord {
	v, err := urcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (urcb *UsageRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := urcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (urcb *UsageRecordCreateBulk) ExecX(ctx context.Context) {
	if err := urcb.Exec(ctx); err != nil {
		panic(err)
	}
}
