// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/predicate"
	"github.com/flexprice/flexprice/ent/usagerecord"
	"github.com/flexprice/flexprice/internal/types"
	"github.com/shopspring/decimal"
)

// UsageRecordUpdate is the builder for updating UsageRecord entities.
type UsageRecordUpdate struct {
	config
	hooks    []Hook
	mutation *UsageRecordMutation
}

// Where appends a list predicates to the UsageRecordUpdate builder.
func (uru *UsageRecordUpdate) Where(ps ...predicate.UsageRecord) *UsageRecordUpdate {
	uru.mutation.Where(ps...)
	return uru
}

// SetStatus sets the "status" field.
func (uru *UsageRecordUpdate) SetStatus(s string) *UsageRecordUpdate {
	uru.mutation.SetStatus(s)
	return uru
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (uru *UsageRecordUpdate) SetNillableStatus(s *string) *UsageRecordUpdate {
	if s != nil {
		uru.SetStatus(*s)
	}
	return uru
}

// SetUpdatedAt sets the "updated_at" field.
func (uru *UsageRecordUpdate) SetUpdatedAt(t time.Time) *UsageRecordUpdate {
	uru.mutation.SetUpdatedAt(t)
	return uru
}

// SetUpdatedBy sets the "updated_by" field.
func (uru *UsageRecordUpdate) SetUpdatedBy(s string) *UsageRecordUpdate {
	uru.mutation.SetUpdatedBy(s)
	return uru
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (uru *UsageRecordUpdate) SetNillableUpdatedBy(s *string) *UsageRecordUpdate {
	if s != nil {
		uru.SetUpdatedBy(*s)
	}
	return uru
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (uru *UsageRecordUpdate) ClearUpdatedBy() *UsageRecordUpdate {
	uru.mutation.ClearUpdatedBy()
	return uru
}

// SetCustomerID sets the "customer_id" field.
func (uru *UsageRecordUpdate) SetCustomerID(s string) *UsageRecordUpdate {
	uru.mutation.SetCustomerID(s)
	return uru
}

// SetNillableCustomerID sets the "customer_id" field if the given value is not nil.
func (uru *UsageRecordUpdate) SetNillableCustomerID(s *string) *UsageRecordUpdate {
	if s != nil {
		uru.SetCustomerID(*s)
	}
	return uru
}

// SetCustomerExternalID sets the "customer_external_id" field.
func (uru *UsageRecordUpdate) SetCustomerExternalID(s string) *UsageRecordUpdate {
	uru.mutation.SetCustomerExternalID(s)
	return uru
}

// SetNillableCustomerExternalID sets the "customer_external_id" field if the given value is not nil.
func (uru *UsageRecordUpdate) SetNillableCustomerExternalID(s *string) *UsageRecordUpdate {
	if s != nil {
		uru.SetCustomerExternalID(*s)
	}
	return uru
}

// ClearCustomerExternalID clears the value of the "customer_external_id" field.
func (uru *UsageRecordUpdate) ClearCustomerExternalID() *UsageRecordUpdate {
	uru.mutation.ClearCustomerExternalID()
	return uru
}

// SetSubscriptionID sets the "subscription_id" field.
func (uru *UsageRecordUpdate) SetSubscriptionID(s string) *UsageRecordUpdate {
	uru.mutation.SetSubscriptionID(s)
	return uru
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (uru *UsageRecordUpdate) SetNillableSubscriptionID(s *string) *UsageRecordUpdate {
	if s != nil {
		uru.SetSubscriptionID(*s)
	}
	return uru
}

// SetPlanID sets the "plan_id" field.
func (uru *UsageRecordUpdate) SetPlanID(s string) *UsageRecordUpdate {
	uru.mutation.SetPlanID(s)
	return uru
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (uru *UsageRecordUpdate) SetNillablePlanID(s *string) *UsageRecordUpdate {
	if s != nil {
		uru.SetPlanID(*s)
	}
	return uru
}

// SetQuantity sets the "quantity" field.
func (uru *UsageRecordUpdate) SetQuantity(d decimal.Decimal) *UsageRecordUpdate {
	uru.mutation.SetQuantity(d)
	return uru
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (uru *UsageRecordUpdate) SetNillableQuantity(d *decimal.Decimal) *UsageRecordUpdate {
	if d != nil {
		uru.SetQuantity(*d)
	}
	return uru
}

// SetAmount sets the "amount" field.
func (uru *UsageRecordUpdate) SetAmount(d decimal.Decimal) *UsageRecordUpdate {
	uru.mutation.SetAmount(d)
	return uru
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (uru *UsageRecordUpdate) SetNillableAmount(d *decimal.Decimal) *UsageRecordUpdate {
	if d != nil {
		uru.SetAmount(*d)
	}
	return uru
}

// SetCurrency sets the "currency" field.
func (uru *UsageRecordUpdate) SetCurrency(s string) *UsageRecordUpdate {
	uru.mutation.SetCurrency(s)
	return uru
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (uru *UsageRecordUpdate) SetNillableCurrency(s *string) *UsageRecordUpdate {
	if s != nil {
		uru.SetCurrency(*s)
	}
	return uru
}

// SetPeriodStart sets the "period_start" field.
func (uru *UsageRecordUpdate) SetPeriodStart(t time.Time) *UsageRecordUpdate {
	uru.mutation.SetPeriodStart(t)
	return uru
}

// SetNillablePeriodStart sets the "period_start" field if the given value is not nil.
func (uru *UsageRecordUpdate) SetNillablePeriodStart(t *time.Time) *UsageRecordUpdate {
	if t != nil {
		uru.SetPeriodStart(*t)
	}
	return uru
}

// SetPeriodEnd sets the "period_end" field.
func (uru *UsageRecordUpdate) SetPeriodEnd(t time.Time) *UsageRecordUpdate {
	uru.mutation.SetPeriodEnd(t)
	return uru
}

// SetNillablePeriodEnd sets the "period_end" field if the given value is not nil.
func (uru *UsageRecordUpdate) SetNillablePeriodEnd(t *time.Time) *UsageRecordUpdate {
	if t != nil {
		uru.SetPeriodEnd(*t)
	}
	return uru
}

// SetSynced sets the "synced" field.
func (uru *UsageRecordUpdate) SetSynced(b bool) *UsageRecordUpdate {
	uru.mutation.SetSynced(b)
	return uru
}

// SetNillableSynced sets the "synced" field if the given value is not nil.
func (uru *UsageRecordUpdate) SetNillableSynced(b *bool) *UsageRecordUpdate {
	if b != nil {
		uru.SetSynced(*b)
	}
	return uru
}

// SetSyncs sets the "syncs" field.
func (uru *UsageRecordUpdate) SetSyncs(mrse map[string]types.UsageRecordSyncEntry) *UsageRecordUpdate {
	uru.mutation.SetSyncs(mrse)
	return uru
}

// ClearSyncs clears the value of the "syncs" field.
func (uru *UsageRecordUpdate) ClearSyncs() *UsageRecordUpdate {
	uru.mutation.ClearSyncs()
	return uru
}

// Mutation returns the UsageRecordMutation object of the builder.
func (uru *UsageRecordUpdate) Mutation() *UsageRecordMutation {
	return uru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uru *UsageRecordUpdate) Save(ctx context.Context) (int, error) {
	uru.defaults()
	return withHooks(ctx, uru.sqlSave, uru.mutation, uru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uru *UsageRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := uru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uru *UsageRecordUpdate) Exec(ctx context.Context) error {
	_, err := uru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uru *UsageRecordUpdate) ExecX(ctx context.Context) {
	if err := uru.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uru *UsageRecordUpdate) defaults() {
	if _, ok := uru.mutation.UpdatedAt(); !ok {
		v := usagerecord.UpdateDefaultUpdatedAt()
		uru.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uru *UsageRecordUpdate) check() error {
	if v, ok := uru.mutation.CustomerID(); ok {
		if err := usagerecord.CustomerIDValidator(v); err != nil {
			return &ValidationError{Name: "customer_id", err: fmt.Errorf(`ent: validator failed for field "UsageRecord.customer_id": %w`, err)}
		}
	}
	if v, ok := uru.mutation.SubscriptionID(); ok {
		if err := usagerecord.SubscriptionIDValidator(v); err != nil {
			return &ValidationError{Name: "subscription_id", err: fmt.Errorf(`ent: validator failed for field "UsageRecord.subscription_id": %w`, err)}
		}
	}
	if v, ok := uru.mutation.PlanID(); ok {
		if err := usagerecord.PlanIDValidator(v); err != nil {
			return &ValidationError{Name: "plan_id", err: fmt.Errorf(`ent: validator failed for field "UsageRecord.plan_id": %w`, err)}
		}
	}
	if v, ok := uru.mutation.Currency(); ok {
		if err := usagerecord.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "UsageRecord.currency": %w`, err)}
		}
	}
	return nil
}

func (uru *UsageRecordUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := uru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(usagerecord.Table, usagerecord.Columns, sqlgraph.NewFieldSpec(usagerecord.FieldID, field.TypeString))
	if ps := uru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uru.mutation.Status(); ok {
		_spec.SetField(usagerecord.FieldStatus, field.TypeString, value)
	}
	if value, ok := uru.mutation.UpdatedAt(); ok {
		_spec.SetField(usagerecord.FieldUpdatedAt, field.TypeTime, value)
	}
	if uru.mutation.CreatedByCleared() {
		_spec.ClearField(usagerecord.FieldCreatedBy, field.TypeString)
	}
	if value, ok := uru.mutation.UpdatedBy(); ok {
		_spec.SetField(usagerecord.FieldUpdatedBy, field.TypeString, value)
	}
	if uru.mutation.UpdatedByCleared() {
		_spec.ClearField(usagerecord.FieldUpdatedBy, field.TypeString)
	}
	if uru.mutation.EnvironmentIDCleared() {
		_spec.ClearField(usagerecord.FieldEnvironmentID, field.TypeString)
	}
	if value, ok := uru.mutation.CustomerID(); ok {
		_spec.SetField(usagerecord.FieldCustomerID, field.TypeString, value)
	}
	if value, ok := uru.mutation.CustomerExternalID(); ok {
		_spec.SetField(usagerecord.FieldCustomerExternalID, field.TypeString, value)
	}
	if uru.mutation.CustomerExternalIDCleared() {
		_spec.ClearField(usagerecord.FieldCustomerExternalID, field.TypeString)
	}
	if value, ok := uru.mutation.SubscriptionID(); ok {
		_spec.SetField(usagerecord.FieldSubscriptionID, field.TypeString, value)
	}
	if value, ok := uru.mutation.PlanID(); ok {
		_spec.SetField(usagerecord.FieldPlanID, field.TypeString, value)
	}
	if value, ok := uru.mutation.Quantity(); ok {
		_spec.SetField(usagerecord.FieldQuantity, field.TypeOther, value)
	}
	if value, ok := uru.mutation.Amount(); ok {
		_spec.SetField(usagerecord.FieldAmount, field.TypeOther, value)
	}
	if value, ok := uru.mutation.Currency(); ok {
		_spec.SetField(usagerecord.FieldCurrency, field.TypeString, value)
	}
	if value, ok := uru.mutation.PeriodStart(); ok {
		_spec.SetField(usagerecord.FieldPeriodStart, field.TypeTime, value)
	}
	if value, ok := uru.mutation.PeriodEnd(); ok {
		_spec.SetField(usagerecord.FieldPeriodEnd, field.TypeTime, value)
	}
	if value, ok := uru.mutation.Synced(); ok {
		_spec.SetField(usagerecord.FieldSynced, field.TypeBool, value)
	}
	if value, ok := uru.mutation.Syncs(); ok {
		_spec.SetField(usagerecord.FieldSyncs, field.TypeJSON, value)
	}
	if uru.mutation.SyncsCleared() {
		_spec.ClearField(usagerecord.FieldSyncs, field.TypeJSON)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usagerecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uru.mutation.done = true
	return n, nil
}

// UsageRecordUpdateOne is the builder for updating a single UsageRecord entity.
type UsageRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UsageRecordMutation
}

// SetStatus sets the "status" field.
func (uruo *UsageRecordUpdateOne) SetStatus(s string) *UsageRecordUpdateOne {
	uruo.mutation.SetStatus(s)
	return uruo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (uruo *UsageRecordUpdateOne) SetNillableStatus(s *string) *UsageRecordUpdateOne {
	if s != nil {
		uruo.SetStatus(*s)
	}
	return uruo
}

// SetUpdatedAt sets the "updated_at" field.
func (uruo *UsageRecordUpdateOne) SetUpdatedAt(t time.Time) *UsageRecordUpdateOne {
	uruo.mutation.SetUpdatedAt(t)
	return uruo
}

// SetUpdatedBy sets the "updated_by" field.
func (uruo *UsageRecordUpdateOne) SetUpdatedBy(s string) *UsageRecordUpdateOne {
	uruo.mutation.SetUpdatedBy(s)
	return uruo
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (uruo *UsageRecordUpdateOne) SetNillableUpdatedBy(s *string) *UsageRecordUpdateOne {
	if s != nil {
		uruo.SetUpdatedBy(*s)
	}
	return uruo
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (uruo *UsageRecordUpdateOne) ClearUpdatedBy() *UsageRecordUpdateOne {
	uruo.mutation.ClearUpdatedBy()
	return uruo
}

// SetCustomerID sets the "customer_id" field.
func (uruo *UsageRecordUpdateOne) SetCustomerID(s string) *UsageRecordUpdateOne {
	uruo.mutation.SetCustomerID(s)
	return uruo
}

// SetNillableCustomerID sets the "customer_id" field if the given value is not nil.
func (uruo *UsageRecordUpdateOne) SetNillableCustomerID(s *string) *UsageRecordUpdateOne {
	if s != nil {
		uruo.SetCustomerID(*s)
	}
	return uruo
}

// SetCustomerExternalID sets the "customer_external_id" field.
func (uruo *UsageRecordUpdateOne) SetCustomerExternalID(s string) *UsageRecordUpdateOne {
	uruo.mutation.SetCustomerExternalID(s)
	return uruo
}

// SetNillableCustomerExternalID sets the "customer_external_id" field if the given value is not nil.
func (uruo *UsageRecordUpdateOne) SetNillableCustomerExternalID(s *string) *UsageRecordUpdateOne {
	if s != nil {
		uruo.SetCustomerExternalID(*s)
	}
	return uruo
}

// ClearCustomerExternalID clears the value of the "customer_external_id" field.
func (uruo *UsageRecordUpdateOne) ClearCustomerExternalID() *UsageRecordUpdateOne {
	uruo.mutation.ClearCustomerExternalID()
	return uruo
}

// SetSubscriptionID sets the "subscription_id" field.
func (uruo *UsageRecordUpdateOne) SetSubscriptionID(s string) *UsageRecordUpdateOne {
	uruo.mutation.SetSubscriptionID(s)
	return uruo
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (uruo *UsageRecordUpdateOne) SetNillableSubscriptionID(s *string) *UsageRecordUpdateOne {
	if s != nil {
		uruo.SetSubscriptionID(*s)
	}
	return uruo
}

// SetPlanID sets the "plan_id" field.
func (uruo *UsageRecordUpdateOne) SetPlanID(s string) *UsageRecordUpdateOne {
	uruo.mutation.SetPlanID(s)
	return uruo
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (uruo *UsageRecordUpdateOne) SetNillablePlanID(s *string) *UsageRecordUpdateOne {
	if s != nil {
		uruo.SetPlanID(*s)
	}
	return uruo
}

// SetQuantity sets the "quantity" field.
func (uruo *UsageRecordUpdateOne) SetQuantity(d decimal.Decimal) *UsageRecordUpdateOne {
	uruo.mutation.SetQuantity(d)
	return uruo
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (uruo *UsageRecordUpdateOne) SetNillableQuantity(d *decimal.Decimal) *UsageRecordUpdateOne {
	if d != nil {
		uruo.SetQuantity(*d)
	}
	return uruo
}

// SetAmount sets the "amount" field.
func (uruo *UsageRecordUpdateOne) SetAmount(d decimal.Decimal) *UsageRecordUpdateOne {
	uruo.mutation.SetAmount(d)
	return uruo
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (uruo *UsageRecordUpdateOne) SetNillableAmount(d *decimal.Decimal) *UsageRecordUpdateOne {
	if d != nil {
		uruo.SetAmount(*d)
	}
	return uruo
}

// SetCurrency sets the "currency" field.
func (uruo *UsageRecordUpdateOne) SetCurrency(s string) *UsageRecordUpdateOne {
	uruo.mutation.SetCurrency(s)
	return uruo
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (uruo *UsageRecordUpdateOne) SetNillableCurrency(s *string) *UsageRecordUpdateOne {
	if s != nil {
		uruo.SetCurrency(*s)
	}
	return uruo
}

// SetPeriodStart sets the "period_start" field.
func (uruo *UsageRecordUpdateOne) SetPeriodStart(t time.Time) *UsageRecordUpdateOne {
	uruo.mutation.SetPeriodStart(t)
	return uruo
}

// SetNillablePeriodStart sets the "period_start" field if the given value is not nil.
func (uruo *UsageRecordUpdateOne) SetNillablePeriodStart(t *time.Time) *UsageRecordUpdateOne {
	if t != nil {
		uruo.SetPeriodStart(*t)
	}
	return uruo
}

// SetPeriodEnd sets the "period_end" field.
func (uruo *UsageRecordUpdateOne) SetPeriodEnd(t time.Time) *UsageRecordUpdateOne {
	uruo.mutation.SetPeriodEnd(t)
	return uruo
}

// SetNillablePeriodEnd sets the "period_end" field if the given value is not nil.
func (uruo *UsageRecordUpdateOne) SetNillablePeriodEnd(t *time.Time) *UsageRecordUpdateOne {
	if t != nil {
		uruo.SetPeriodEnd(*t)
	}
	return uruo
}

// SetSynced sets the "synced" field.
func (uruo *UsageRecordUpdateOne) SetSynced(b bool) *UsageRecordUpdateOne {
	uruo.mutation.SetSynced(b)
	return uruo
}

// SetNillableSynced sets the "synced" field if the given value is not nil.
func (uruo *UsageRecordUpdateOne) SetNillableSynced(b *bool) *UsageRecordUpdateOne {
	if b != nil {
		uruo.SetSynced(*b)
	}
	return uruo
}

// SetSyncs sets the "syncs" field.
func (uruo *UsageRecordUpdateOne) SetSyncs(mrse map[string]types.UsageRecordSyncEntry) *UsageRecordUpdateOne {
	uruo.mutation.SetSyncs(mrse)
	return uruo
}

// ClearSyncs clears the value of the "syncs" field.
func (uruo *UsageRecordUpdateOne) ClearSyncs() *UsageRecordUpdateOne {
	uruo.mutation.ClearSyncs()
	return uruo
}

// Mutation returns the UsageRecordMutation object of the builder.
func (uruo *UsageRecordUpdateOne) Mutation() *UsageRecordMutation {
	return uruo.mutation
}

// Where appends a list predicates to the UsageRecordUpdate builder.
func (uruo *UsageRecordUpdateOne) Where(ps ...predicate.UsageRecord) *UsageRecordUpdateOne {
	uruo.mutation.Where(ps...)
	return uruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uruo *UsageRecordUpdateOne) Select(field string, fields ...string) *UsageRecordUpdateOne {
	uruo.fields = append([]string{field}, fields...)
	return uruo
}

// Save executes the query and returns the updated UsageRecord entity.
func (uruo *UsageRecordUpdateOne) Save(ctx context.Context) (*UsageRecord, error) {
	uruo.defaults()
	return withHooks(ctx, uruo.sqlSave, uruo.mutation, uruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uruo *UsageRecordUpdateOne) SaveX(ctx context.Context) *UsageRecord {
	node, err := uruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uruo *UsageRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := uruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uruo *UsageRecordUpdateOne) ExecX(ctx context.Context) {
	if err := uruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uruo *UsageRecordUpdateOne) defaults() {
	if _, ok := uruo.mutation.UpdatedAt(); !ok {
		v := usagerecord.UpdateDefaultUpdatedAt()
		uruo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uruo *UsageRecordUpdateOne) check() error {
	if v, ok := uruo.mutation.CustomerID(); ok {
		if err := usagerecord.CustomerIDValidator(v); err != nil {
			return &ValidationError{Name: "customer_id", err: fmt.Errorf(`ent: validator failed for field "UsageRecord.customer_id": %w`, err)}
		}
	}
	if v, ok := uruo.mutation.SubscriptionID(); ok {
		if err := usagerecord.SubscriptionIDValidator(v); err != nil {
			return &ValidationError{Name: "subscription_id", err: fmt.Errorf(`ent: validator failed for field "UsageRecord.subscription_id": %w`, err)}
		}
	}
	if v, ok := uruo.mutation.PlanID(); ok {
		if err := usagerecord.PlanIDValidator(v); err != nil {
			return &ValidationError{Name: "plan_id", err: fmt.Errorf(`ent: validator failed for field "UsageRecord.plan_id": %w`, err)}
		}
	}
	if v, ok := uruo.mutation.Currency(); ok {
		if err := usagerecord.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "UsageRecord.currency": %w`, err)}
		}
	}
	return nil
}

func (uruo *UsageRecordUpdateOne) sqlSave(ctx context.Context) (_node *UsageRecord, err error) {
	if err := uruo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usagerecord.Table, usagerecord.Columns, sqlgraph.NewFieldSpec(usagerecord.FieldID, field.TypeString))
	id, ok := uruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UsageRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usagerecord.FieldID)
		for _, f := range fields {
			if !usagerecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usagerecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uruo.mutation.Status(); ok {
		_spec.SetField(usagerecord.FieldStatus, field.TypeString, value)
	}
	if value, ok := uruo.mutation.UpdatedAt(); ok {
		_spec.SetField(usagerecord.FieldUpdatedAt, field.TypeTime, value)
	}
	if uruo.mutation.CreatedByCleared() {
		_spec.ClearField(usagerecord.FieldCreatedBy, field.TypeString)
	}
	if value, ok := uruo.mutation.UpdatedBy(); ok {
		_spec.SetField(usagerecord.FieldUpdatedBy, field.TypeString, value)
	}
	if uruo.mutation.UpdatedByCleared() {
		_spec.ClearField(usagerecord.FieldUpdatedBy, field.TypeString)
	}
	if uruo.mutation.EnvironmentIDCleared() {
		_spec.ClearField(usagerecord.FieldEnvironmentID, field.TypeString)
	}
	if value, ok := uruo.mutation.CustomerID(); ok {
		_spec.SetField(usagerecord.FieldCustomerID, field.TypeString, value)
	}
	if value, ok := uruo.mutation.CustomerExternalID(); ok {
		_spec.SetField(usagerecord.FieldCustomerExternalID, field.TypeString, value)
	}
	if uruo.mutation.CustomerExternalIDCleared() {
		_spec.ClearField(usagerecord.FieldCustomerExternalID, field.TypeString)
	}
	if value, ok := uruo.mutation.SubscriptionID(); ok {
		_spec.SetField(usagerecord.FieldSubscriptionID, field.TypeString, value)
	}
	if value, ok := uruo.mutation.PlanID(); ok {
		_spec.SetField(usagerecord.FieldPlanID, field.TypeString, value)
	}
	if value, ok := uruo.mutation.Quantity(); ok {
		_spec.SetField(usagerecord.FieldQuantity, field.TypeOther, value)
	}
	if value, ok := uruo.mutation.Amount(); ok {
		_spec.SetField(usagerecord.FieldAmount, field.TypeOther, value)
	}
	if value, ok := uruo.mutation.Currency(); ok {
		_spec.SetField(usagerecord.FieldCurrency, field.TypeString, value)
	}
	if value, ok := uruo.mutation.PeriodStart(); ok {
		_spec.SetField(usagerecord.FieldPeriodStart, field.TypeTime, value)
	}
	if value, ok := uruo.mutation.PeriodEnd(); ok {
		_spec.SetField(usagerecord.FieldPeriodEnd, field.TypeTime, value)
	}
	if value, ok := uruo.mutation.Synced(); ok {
		_spec.SetField(usagerecord.FieldSynced, field.TypeBool, value)
	}
	if value, ok := uruo.mutation.Syncs(); ok {
		_spec.SetField(usagerecord.FieldSyncs, field.TypeJSON, value)
	}
	if uruo.mutation.SyncsCleared() {
		_spec.ClearField(usagerecord.FieldSyncs, field.TypeJSON)
	}
	_node = &UsageRecord{config: uruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usagerecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uruo.mutation.done = true
	return _node, nil
}
